Add transformation definition docs
Alluxio/alluxio pull request #12122
Opened 2020-09-22 00:48 UTC by bradyoo

2020-09-22 00:54 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-09-22 00:54 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11291/
Test PASSed.

2020-09-22 17:42 UTC, bradyoo commented
@gpang

2020-09-22 18:58 UTC, gpang requested changes
@bradyoo I just had a minor comment.

2020-09-22 18:58 UTC, gpang commented on docs/en/operation/User-CLI.md
> +file.size.min=<num> (minimum file size of the output)
Is this is bytes? If so, please specify this doc.

2020-09-22 22:14 UTC, bradyoo commented
Good catch. Fixed.

2020-09-22 22:18 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-09-22 22:18 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11299/
Test PASSed.

2020-09-23 00:51 UTC, gpang approved these changes
LGTM

2020-09-23 00:51 UTC, gpang commented
alluxio-bot, merge this please

2020-09-23 00:51 UTC, merged

2020-09-23 00:51 UTC, gpang commented
alluxio-bot, cherry-pick this to branch-2.3 please