Add metadata operations saved metrics
Alluxio/alluxio pull request #12124
Opened 2020-09-22 03:01 UTC by yuzhu

2020-09-22 03:04 UTC, yuzhu commented
@calvinjia It was not clear to me which metadata operations we plan to account for. so I purposely did only a few to start, but the code is in place to expand the amount of metadata ops we track relatively easily. The overall idea is to use the actual operations done against alluxio - all the operations we did to ufs (during sync , load metadata etc)  and that difference should be the savings. Does that sound about right to you?

2020-09-22 03:14 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2020-09-22 03:14 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11293/
Test FAILed.

2020-09-22 03:52 UTC, yuzhu commented
jenkins, test this please

2020-09-22 04:17 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2020-09-22 04:17 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11295/
Test FAILed.

2020-09-22 17:27 UTC, yuzhu commented
alluxio-bot, test this please

2020-09-22 18:25 UTC, calvinjia requested changes
Can we also track the number of `listStatus` calls?

2020-09-22 19:34 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2020-09-22 19:34 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11296/
Test FAILed.

2020-09-22 20:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-09-22 20:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11298/
Test PASSed.

2020-10-08 21:47 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-10-08 21:47 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11410/
Test PASSed.

2020-10-08 22:17 UTC, yuzhu commented
@calvinjia  updated to add listStatus and fine tuned the previous calculations.

2020-10-09 02:48 UTC, yuzhu commented
![image](https://user-images.githubusercontent.com/736171/95536193-3e069180-099f-11eb-9873-55b43a343c96.png)

2020-10-09 02:49 UTC, yuzhu commented
@tieujason330 please review the front end part. @calvinjia PTAL the saved ufs operation metrics
Thanks

2020-10-09 03:14 UTC, AmplabJenkins commented
Merged build finished. Test FAILed.

2020-10-09 03:14 UTC, AmplabJenkins commented
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11412/
Test FAILed.

2020-10-09 18:09 UTC, calvinjia approved these changes

2020-10-09 18:10 UTC, tieujason330 reviewed
did you run `npm run test` and `npm run format` to see if any tests/formatting was changed?

2020-10-09 18:10 UTC, tieujason330 commented on webui/master/src/containers/pages/Metrics/Metrics.tsx
> +
you can remove this empty line

2020-10-09 18:10 UTC, tieujason330 commented on webui/master/src/containers/pages/Metrics/Metrics.tsx
> +              <tbody>
are table headers needed?

2020-10-09 18:30 UTC, yuzhu commented on webui/master/src/containers/pages/Metrics/Metrics.tsx
> +
removed

2020-10-09 18:30 UTC, yuzhu commented on webui/master/src/containers/pages/Metrics/Metrics.tsx
> +              <tbody>
nope, to be consistent with above block

2020-10-09 18:31 UTC, yuzhu commented
@tieujason330 ran npm tests and all passed. PTAL

2020-10-09 18:40 UTC, tieujason330 approved these changes

2020-10-09 18:45 UTC, yuzhu commented
alluxio-bot, merge this please

2020-10-09 18:45 UTC, merged

2020-10-09 18:45 UTC, yuzhu commented
alluxio-bot, cherry-pick this to branch-2.4 please

2020-10-09 19:02 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-10-09 19:02 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11416/
Test PASSed.