[DOCFIX] Include new collectInfo features into the doc
Alluxio/alluxio pull request #12157
Opened 2020-09-28 13:26 UTC by jiacheliu3

2020-09-28 13:31 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-09-28 13:31 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11331/
Test PASSed.

2020-09-29 19:56 UTC, gpang requested changes
@jiacheliu3 just a minor comment

2020-09-29 19:56 UTC, gpang commented on docs/en/operation/Troubleshooting.md
> +1. `--start-time <datetime>` specifis a datetime before with the log files can be ignored.
```suggestion
1. `--start-time <datetime>` specifies a datetime before with the log files can be ignored.
```

2020-09-30 01:40 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-09-30 01:40 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11350/
Test PASSed.

2020-09-30 17:11 UTC, gpang approved these changes
LGTM

2020-09-30 17:11 UTC, gpang commented
alluxio-bot, merge this please

2020-09-30 17:11 UTC, merged

2020-10-07 01:14 UTC, jiacheliu3 commented
alluxio-bot, cherry-pick this to branch-2.3 please