[DOCFIX] Update upgrade docs
Alluxio/alluxio pull request #12188
Opened 2020-10-06 22:28 UTC by LuQQiu

2020-10-06 22:35 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-10-06 22:35 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11395/
Test PASSed.

2020-10-06 23:36 UTC, bf8086 requested changes
Thanks, I added some minor comments.

2020-10-06 23:36 UTC, bf8086 commented on docs/en/operation/Upgrade.md
> +are not compatible.
```suggestion
There are two cases where master journals are not backward compatible and additional steps are required to upgrade Alluxio cluster:

- Upgrading from Alluxio 1.x to Alluxio 2.x
- Upgrading from Alluxio 2.3.x and below to Alluxio 2.4.0 and above, and the embedded journal is used.
```

2020-10-06 23:36 UTC, bf8086 commented on docs/en/operation/Upgrade.md
> +the upgrade method provided in the later sections is still preferred and less error-prone.
```suggestion
This document goes over how to upgrade Alluxio to a non-backward compatible version.
Even when upgrading to a backward compatible version, it is still recommended to follow the steps below to create a backup before upgrading.
```

2020-10-06 23:42 UTC, AmplabJenkins commented
Merged build finished. Test PASSed.

2020-10-06 23:42 UTC, AmplabJenkins commented
Test PASSed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Alluxio-PR-Builder/11396/
Test PASSed.

2020-10-06 23:53 UTC, LuQQiu commented
@bf8086 PTAL, thanks

2020-10-06 23:53 UTC, bf8086 approved these changes
LGTM.

2020-10-07 00:21 UTC, LuQQiu commented
alluxio-bot, merge this please

2020-10-07 00:21 UTC, merged

2020-10-07 00:21 UTC, LuQQiu commented
alluxio-bot, cherry-pick this to branch-2.4 please