Wait at most 60 seconds to join the JvmMonitorThread
Alluxio/alluxio pull request #12243
Opened 2020-10-12 20:31 UTC by bradyoo

2020-10-13 00:08 UTC, bradyoo commented
@gpang can you please take a look? This is the main blocker for java 11 github-actions

2020-10-13 16:15 UTC, bradyoo commented
@gpang

2020-10-13 20:17 UTC, gpang requested changes
@bradyoo I left a comment

2020-10-13 20:17 UTC, gpang commented on core/common/src/main/java/alluxio/util/JvmPauseMonitor.java
> +      mJvmMonitorThread.join(60 * 1000);
I don't think the jvm monitor is doing very much, so we probably don't need to wait so long. Maybe: `5 * Constants.SECOND_MS`?

Also, I think the thread while loop should be something like `while (!Thread.currentThread().isInterrupted())`

2020-10-14 02:08 UTC, bradyoo commented
@gpang's suggested fix reflected. Though !Thread.currentThread().isInterrupted() didn't end up working.

2020-10-14 03:09 UTC, gpang approved these changes
LGTM

2020-10-14 03:09 UTC, gpang commented
alluxio-bot, merge this please

2020-10-14 03:10 UTC, merged

2020-10-15 03:33 UTC, LuQQiu commented
alluxio-bot, merge this to branch-2.4 please

2020-10-15 03:38 UTC, LuQQiu commented
alluxio-bot, cherry-pick this to branch-2.4 please