Add footprint to UFS docs
Alluxio/alluxio pull request #12495
Opened 2020-11-12 22:20 UTC by LuQQiu

2020-11-12 22:27 UTC, Xenorith requested changes
i commented on one doc, but applies to all docs

2020-11-12 22:27 UTC, Xenorith commented on docs/en/ufs/GlusterFS.md
> +Source code locates at [here](https://github.com/Alluxio/alluxio-extensions/tree/master/underfs/glusterfs).
`The source code is located [here](link).`

2020-11-12 22:27 UTC, Xenorith commented on docs/en/ufs/GlusterFS.md
> +GlusterFS UFS integration is contributed and maintained by Alluxio community.
`by the Alluxio community.`

2020-11-12 22:27 UTC, Xenorith commented on docs/en/ufs/GlusterFS.md
> +Welcome to submit pull requests to improve the integration!
`Feel free submit pull requests to improve the integration and update the documentation [here](https://github.com/Alluxio/alluxio/edit/master/docs/en/ufs/GlusterFS.md) if any information is missing or out of date.`

2020-11-13 04:17 UTC, Xenorith approved these changes

2020-11-13 19:46 UTC, LuQQiu commented
alluxio-bot, merge this please

2020-11-13 19:46 UTC, merged

2020-11-18 00:39 UTC, LuQQiu commented
alluxio-bot, cherry-pick this to branch-2.4 please