Add cosn under file system to support higher performance read and write cos of tencent
Alluxio/alluxio pull request #12493
Opened 2020-11-12 09:25 UTC by jayzhenghan

2020-11-13 00:47 UTC, gpang commented
@jayzhenghan Thanks! Could you add a PR description, including how this is different from the other `cos` scheme?

2020-11-13 02:32 UTC, jayzhenghan commented
> @jayzhenghan Thanks! Could you add a PR description, including how this is different from the other `cos` scheme?

ok~,I am considering whether to directly replace cos or coexist with cos. first one, compatibility is smoother; second one is more secure but document the difference between cosn and cos and how to use it，compatibility is not good as first one.

2020-11-16 03:15 UTC, maobaolong commented
@jayzhenghan Thanks for this contribution. You can create an issue label it with feature-request, and add description with motivation.

Then, you can insert `Fix #ISSUE_ID` to the start of PR description, so that when this PR merged, the related issue can be closed.

2020-11-16 03:37 UTC, maobaolong requested changes
This PR looks like to create a new ufs module to make it possible to using cosn in Alluxio global namespace. I left some minor comments inline.

And, I noticed the `CosFileSystem` is an implementation of `Hadoop compatible filesystem`, so suggest to reference the https://www.youtube.com/watch?v=D65V3WpS5zQ  to reuse the `HdfsUnderFileSystem ` to avoid lots of redundant codes.

2020-11-16 03:37 UTC, maobaolong commented on underfs/cosn/pom.xml
> +      <version>3.1.0-5.8.5</version>
You can remove the `version` tag here, and maven can use the `hadoop-cos` definition from root pom.xml dependencyManagement.

2020-11-16 03:37 UTC, maobaolong commented on underfs/cosn/pom.xml
> +      <version>5.6.19</version>
ditto

2020-11-16 03:37 UTC, maobaolong commented on underfs/cosn/pom.xml
> +    <hadoop.version>3.1.0</hadoop.version>
If you want to specify the `hadoop version` for this ufs, you can use another property name other than this `hadoop.version` to keep difference to alluxio main framework. For example, `cosn.hadoop.version`

2020-11-20 02:49 UTC, maobaolong reviewed
`webui/npm-shrinkwrap.json`

Please revert this file changes

2020-11-20 02:53 UTC, maobaolong commented on shaded/cosn/pom.xml
> +  <profiles>
As now, we have only one profile, and it is active by default, you can put these dependencies directly, when you need to define another profile, we can bring this back.

2020-11-20 02:54 UTC, jayzhenghan commented
> `webui/npm-shrinkwrap.json`
> 
> Please revert this file changes

Ok,I get it

2020-11-20 02:55 UTC, maobaolong requested changes
@jayzhenghan Thanks for this changes, it looks good overall, left some minor comments inline.

2020-11-20 06:37 UTC, jayzhenghan commented
![alluxio_rw_test](https://user-images.githubusercontent.com/68948288/99767366-e3378c80-2b3d-11eb-906f-0afbc7aa5bad.png)

2020-11-24 03:35 UTC, maobaolong approved these changes
LGTM, thanks

2020-11-24 03:44 UTC, jayzhenghan commented
> @jayzhenghan Thanks! Could you add a PR description, including how this is different from the other `cos` scheme?

Thank you for your suggestion，I have added the description in cos.md and cosn.md.

2020-11-24 03:47 UTC, jayzhenghan commented
> @jayzhenghan Thanks! Could you add a PR description, including how this is different from the other `cos` scheme?

Thank you for your suggestion，I have added a description in cos.md and cosn.md.

2020-11-25 03:30 UTC, maobaolong commented
@apc999 Could you please take another look?

2020-11-25 18:19 UTC, maobaolong approved these changes
LGTM, thanks for your contribution.

2020-11-26 02:59 UTC, jayzhenghan commented
Fix #12581

2020-12-01 18:35 UTC, apc999 commented
@maobaolong , how about replace original COS module with this new Cosn module?

2020-12-02 02:16 UTC, jayzhenghan commented
> @maobaolong , how about replace original COS module with this new Cosn module?

Taking into account the compatibility of cos, it is reserved, but maintenance will be stopped in version 2.6.0, and users are strongly recommended to use cosn

2020-12-02 14:08 UTC, maobaolong commented
@apc999 I'm ok to replace the original COS module if there are no objection from users.

2020-12-02 18:33 UTC, gpang commented
@jayzhenghan Thanks for this great contribution! Can you update the PR description with more details about this new/updated cos connector?

2020-12-03 02:30 UTC, jayzhenghan commented
> @jayzhenghan Thanks for this great contribution! Can you update the PR description with more details about this new/updated cos connector?

@gpang @apc999 COS UFS has the problem of poor and unstable reader performance. In order to solve this problem, a file system like [COSN UFS] (COSN.html) has been introduced. Compared with COS, it has been deeply optimized, and its reading performance is doubled compared with COS, and it also brings better stability. For more usage, please refer to cos.md and cosn.md in pr.

2020-12-09 23:28 UTC, apc999 approved these changes

2020-12-09 23:28 UTC, apc999 commented
alluxio-bot, merge this please

2020-12-09 23:29 UTC, merged

2020-12-09 23:29 UTC, apc999 commented
thanks @jayzhenghan for the contribution!