Get a chunk of PartitionColumnStatistics at a time from Hive
Alluxio/alluxio pull request #12574
Opened 2020-11-24 01:20 UTC by bradyoo

2020-11-24 18:49 UTC, gpang requested changes
@bradyoo

2020-11-24 18:49 UTC, gpang commented on table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java
> +              .getPartitionColumnStatistics(mHiveDbName, tableName, partialPartitionNames, dataColumns)
```
HiveDatabase.java:231: error: Line is longer than 100 characters (found 103).
```

2020-11-24 23:26 UTC, gpang commented
@bradyoo Have you performed any sanity checks that the batching will actually happen and the results are correct?

2020-11-25 17:08 UTC, bradyoo commented
Tested on autobots that it works just the same with small chunks. Reverting back to larger chunks.

2020-11-25 19:58 UTC, gpang approved these changes
LGTM

2020-11-25 19:58 UTC, gpang commented
alluxio-bot, merge this please

2020-11-25 19:58 UTC, merged