add documents to introducte running alluxio on tencent cloud EMR
Alluxio/alluxio pull request #12693
Opened 2021-01-04 13:03 UTC by wheatxiong

This guide describes how to configure Alluxio to run on Tencent Cloud EMR.

fix this:
https://github.com/Alluxio/alluxio/issues/12692

2021-01-04 13:50 UTC, wheatxiong commented
> alluxio-bot, check this please

2021-01-04 14:00 UTC, wheatxiong commented
alluxio-bot, check this please

2021-01-04 14:53 UTC, wheatxiong commented
alluxio-bot, check this please

2021-01-05 18:49 UTC, apc999 requested changes
thanks for the contribution!

2021-01-05 18:49 UTC, apc999 commented on docs/cn/cloud/Tencent-Cloud-EMR.md
> +有关EMR中版本中支持具体的Alluxio的版本支持可参考[这里](https://cloud.tencent.com/document/product/589/20279)
```suggestion
- 腾讯云EMR的Hadoop标准版本>=2.1.0
- 腾讯云EMR的Hadoop天穹版本>=1.0
- 有关EMR中版本中支持具体的Alluxio的版本支持可参考[这里](https://cloud.tencent.com/document/product/589/20279)
```

2021-01-05 18:49 UTC, apc999 commented on docs/cn/cloud/Tencent-Cloud-EMR.md
> +[重启服务](https://cloud.tencent.com/document/product/589/32823)
```suggestion
- [配置管理](https://cloud.tencent.com/document/product/589/14628)
- [重启服务](https://cloud.tencent.com/document/product/589/32823)
```

2021-01-05 18:49 UTC, apc999 commented on docs/cn/cloud/Tencent-Cloud-EMR.md
> +
```suggestion
```

2021-01-05 18:49 UTC, apc999 commented on docs/en/cloud/Tencent-Cloud-EMR.md
> +For the specific Alluxio version supported in EMR, please refer to [ Component Version supported Tencent Cloud EMR](https://intl.cloud.tencent.com/document/product/1026/31095).
```suggestion
- Hadoop standard version of Tencent Cloud EMR >= 2.1.0
- Hadoop Skydome version of Tencent Cloud EMR >= 1.0
- For the specific Alluxio version supported in EMR, please refer to [Component Version supported Tencent Cloud EMR](https://intl.cloud.tencent.com/document/product/1026/31095).
```

2021-01-05 18:49 UTC, apc999 commented on docs/en/cloud/Tencent-Cloud-EMR.md
> +
```suggestion
```

2021-01-06 03:20 UTC, wheatxiong commented
> thanks for the contribution!

Thank you very much for reviewing it ! 

I had changes as requested, pls review again.

2021-01-06 19:27 UTC, apc999 approved these changes
Thanks for the contribution!

2021-01-06 19:28 UTC, apc999 commented
alluxio-bot, merge this please

2021-01-06 19:28 UTC, merged

2021-01-19 19:18 UTC, apc999 commented
alluxio-bot, cherry-pick this to branch-2.4 please