Add CI Command to list state lock thread holders
Alluxio/alluxio pull request #12769
Opened 2021-01-28 18:20 UTC by bradyoo

2021-01-28 20:58 UTC, yuzhu requested changes
Thanks for the change. One minor suggestion to include the thread id. and could we add a test for this command?

2021-01-28 20:58 UTC, yuzhu commented on core/transport/src/main/proto/grpc/file_system_master.proto
> +  repeated string threads = 1;
We might as well return the thread id as well. Just in case we have duplicate thread names?

2021-01-28 23:20 UTC, bradyoo commented
I thought about writing tests for this but there really isn't a good idea on how to write tests for this. Do you have any good ideas?

2021-01-28 23:31 UTC, bradyoo commented
I'll write tests for the actual underlying method in StateLockManager but probably not for the CI.

2021-01-28 23:41 UTC, bradyoo commented
added a test on StateLockManager and changed from name to identifier

2021-01-29 17:18 UTC, bradyoo commented
@yuzhu

2021-01-29 17:24 UTC, yuzhu approved these changes
LGTM, thanks

2021-01-29 17:26 UTC, bradyoo commented
alluxio-bot, merge this please.

2021-01-29 17:26 UTC, merged

2021-01-29 17:28 UTC, bradyoo commented
alluxio-bot, cherry-pick this to branch-2.4 please.

2021-03-12 20:37 UTC, bradyoo commented
alluxio-bot cherry-pick this to branch-2.3 please.

2021-03-12 20:45 UTC, bradyoo commented
alluxio-bot, cherry-pick this to branch-2.3 please.