Fix "Allocation after freeing space" log message
Alluxio/alluxio pull request #12801
Opened 2021-02-03 19:26 UTC by bradyoo

dirView has no toString implementation. So it is certainly not what you want.

2021-02-04 04:26 UTC, gpang requested changes
@bradyoo Thanks! Can you update the PR description with the before and after? It is not clear to me what the old and new message look like.

2021-02-04 04:26 UTC, gpang commented on core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
> +            LOG.debug("Allocation after freeing space for block expansion: {}",
This should probably be something like "Allocation after freeing space for block expansion. availableBytes: {}". Is the goal of this message to show the available bytes after freeing?

2021-02-04 05:13 UTC, jiacheliu3 approved these changes
DItto for Gene's comment above. LGTM if the comment is resolved. Thanks!

2021-02-04 06:34 UTC, gpang commented
```
+ say '\033[0;31m-->\033[0m No coverage report found.'
+ echo -e '\033[0;31m-->\033[0m No coverage report found.'
--> No coverage report found.
+ say '    Please visit \033[0;36mhttp://docs.codecov.io/docs/supported-languages\033[0m'
+ echo -e '    Please visit \033[0;36mhttp://docs.codecov.io/docs/supported-languages\033[0m'
+ exit 1
    Please visit http://docs.codecov.io/docs/supported-languages
Error: Codecov failed with the following error: The process '/bin/bash' failed with exit code 1
```

2021-02-04 17:10 UTC, bradyoo commented
generate code coverage flaked. Code Coverage generation has been flaky. Upload code coverage failed because generating it failed.

2021-02-04 17:13 UTC, bradyoo commented
done.

2021-02-05 01:08 UTC, jiacheliu3 approved these changes
LGTM, thanks!

2021-02-05 19:18 UTC, bradyoo commented
alluxio-bot, merge this please.

2021-02-05 19:18 UTC, merged