Add GCS Version 2 integration using Google cloud API
Alluxio/alluxio pull request #12842
Opened 2021-02-11 21:25 UTC by LuQQiu

Add GCS Version 2 integration using Google cloud API

2021-02-11 21:46 UTC, LuQQiu commented
This PR has already tested with nested mount + bin/alluxio runTests 
and 
```
bin/alluxio runUfsTests --path gs://<bucket> -Dalluxio.underfs.gcs.version=2 -Ds.gcs.credential.path=<credential>
```

2021-02-12 19:39 UTC, LuQQiu commented
@bf8086 PTAL， thanks!

2021-02-18 00:17 UTC, bf8086 requested changes
I took a look at mostly the documentation assuming we have already reviewed the code previously.

2021-02-18 00:17 UTC, bf8086 commented on docs/en/ufs/GCS.md
> +Choose your desired GCS implementation way and provide the corresponding Google credentials.
```suggestion
Choose your preferred GCS UFS version and provide the corresponding Google credentials.
```

2021-02-18 00:17 UTC, bf8086 commented on docs/en/ufs/GCS.md
> +Alluxio has two GCS integrations. The default GCS UFS module (GCS version 1) is implemented based on
```suggestion
Alluxio provides two ways to access GCS. The default GCS UFS module (GCS version 1) is implemented based on 
```

2021-02-18 00:17 UTC, bf8086 commented on docs/en/ufs/GCS.md
> +The conjuction of Google interoperability API and jets3t library also impact the performance of default GCS UFS module.
```suggestion
The conjunction of Google interoperability API and jets3t library also impact the performance of the default GCS UFS module. 
```

2021-02-18 18:01 UTC, LuQQiu commented
@bf8086 Applied all your suggestions, PTAL, thanks!

2021-02-19 00:17 UTC, bf8086 approved these changes
LGTM. Thanks!

2021-02-19 00:18 UTC, LuQQiu commented
alluxio-bot, sync-merge this please

2021-02-19 00:18 UTC, LuQQiu commented
alluxio-bot, merge this please

2021-02-19 00:19 UTC, merged