Add logging on slow UFS calls
Alluxio/alluxio pull request #12948
Opened 2021-02-26 00:49 UTC by apc999

Add information on UFS call logging:
(1) time elapsed for each UFS call
(2) add a new flag to control log UFS calls that takes time longer than defined threshold.

2021-02-26 12:26 UTC, gpang requested changes
@apc999 Thanks!

What about any data read/write operations? This won't be able to log any of those UFS calls.

2021-02-26 12:26 UTC, gpang commented on core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
> +  private static final long THRESHOLD = new InstancedConfiguration(ConfigurationUtils.defaults())
Should this just use the `mConf` to get the property?

2021-02-26 12:26 UTC, gpang commented on core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
> +          methodName, callable, e.getMessage(), durationMs);
I think the arguments are in the wrong order. `e.getMessage()` and `durationMs` should be switched.

2021-02-26 12:26 UTC, gpang commented on core/common/src/main/java/alluxio/underfs/UnderFileSystemWithLogging.java
> +        LOG.warn("{}({}) returned {} in {} ms (>={} ms)", methodName,
NIT: maybe enclose the error message in "" or ``?

2021-02-27 00:47 UTC, gpang approved these changes
LGTM

2021-02-27 03:10 UTC, apc999 commented
alluxio-bot, merge this please

2021-02-27 03:10 UTC, merged