[Feat]: Add nondeterministic LRU
Alluxio/alluxio pull request #13068
Opened 2021-03-15 03:51 UTC by sunnyszy

Fix https://github.com/Alluxio/alluxio/issues/13062.

Add a class LRUNondeterministicCacheEvictor. Instead of evicting the tail element like LRU, it evicts uniformly from the last n elements at the LRU tail. 

A configurable parameter "alluxio.user.client.cache.evictor.lru.nondeterministic.numofcandidate" is exposed and the default value is 4.

2021-03-15 03:55 UTC, sunnyszy commented
> Automated checks report:
> 
> * Commits associated with Github account: PASS
> * PR title follows the conventions: FAIL
>   
>   * The title of the PR does not pass all the checks. Please fix the following issues:
>     
>     * First word must be capitalized
>     * First word of title (":") is not an imperative verb. Please use one of the [valid words](https://raw.githubusercontent.com/Alluxio/alluxio/master/docs/resources/pr/pr_title_words.md)
>     * Supported title prefixes are: [WIP], [SMALLFIX], [DOCFIX]
> 
> Some checks failed. Please fix the reported issues and reply 'alluxio-bot, check this please' to re-run checks.

alluxio-bot, check this please

2021-03-18 22:24 UTC, apc999 commented on core/client/fs/src/main/java/alluxio/client/file/cache/evictor/LRUNondeterministicCacheEvictor.java
> +    mNumOfCandidate =
I don't think it is necessary to introduce another property here. I am fine to leave it as a arbitrary constant int like 8 or 16

2021-03-18 22:30 UTC, apc999 requested changes
THanks for the improvement! I left some high level comments

2021-03-18 22:30 UTC, apc999 commented on core/client/fs/src/main/java/alluxio/client/file/cache/evictor/LRUNondeterministicCacheEvictor.java
> +public class LRUNondeterministicCacheEvictor implements CacheEvictor {
Nit: `NondeterministicLRUCacheEvictor`, also, how about extending `LRUCacheEvictor` since most structure is the same

2021-03-18 22:30 UTC, apc999 commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +  public static final PropertyKey USER_CLIENT_CACHE_EVICTOR_LRU_NONDETERMINISTIC_NUMOFCANDIDATE =
Mentioned previously, let's not introduce such a flag for tthe number of candidate.

Instead, we can introduce `PropertyKey.USER_CLIENT_CACHE_EVICTOR_NONDETERMINISTIC`  as a boolean flag. Once this flag is `true` and `alluxio.user.client.cache.evictor.class` is LRUCacheEvictor, in `alluxio.client.file.cache.evictor.CacheEvictor#create` (the factory method of CacheEvictor, we can return this new NondeterministicLRUCacheEvictor`

2021-03-20 20:21 UTC, sunnyszy commented
Thanks. I addressed the suggestions.

BTW for the testing part, I basically copy the test from LRU and consider the non-deterministic evictions.

2021-03-21 17:52 UTC, sunnyszy commented
@apc999 would you like to help me check the integration error msg? I didn't see this when running the test locally and also it seems unrelated to my changes.

2021-03-25 23:10 UTC, apc999 approved these changes
Thanks for the contribution!

2021-03-25 23:10 UTC, apc999 commented
alluxio-bot, merge this please

2021-03-25 23:10 UTC, merged