Add absent cache metrics
Alluxio/alluxio pull request #13088
Opened 2021-03-16 21:03 UTC by yuzhu

Add some metrics for the absent cache

2021-03-18 05:15 UTC, calvinjia requested changes
Should we also track number of invalidations?

2021-03-18 23:03 UTC, calvinjia commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +    public static final String MASTER_JOURNAL_TYPE = "alluxio.master.journal.typelog";
Is this change intended?

2021-03-19 15:34 UTC, yuzhu commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +    public static final String MASTER_JOURNAL_TYPE = "alluxio.master.journal.typelog";
oops fixed.

2021-03-19 18:49 UTC, calvinjia approved these changes

2021-03-19 18:49 UTC, calvinjia commented
alluxio-bot, merge this please.

2021-03-19 18:50 UTC, merged

2021-04-01 21:17 UTC, yuzhu commented
alluxio-bot, cherry-pick this to branch-2.4 please

2021-04-05 22:18 UTC, yuzhu commented
alluxio-bot, cherry-pick this to branch-2.3 please