Reserve real blockSize for distributedLoad
Alluxio/alluxio pull request #13093
Opened 2021-03-18 05:42 UTC by apc999

Fix https://github.com/Alluxio/alluxio/issues/13005

2021-03-18 05:45 UTC, apc999 commented on core/client/fs/src/main/java/alluxio/client/block/AlluxioBlockStore.java
> -    if (blockSize == -1) {
I checked the src code, blockSize will never be -1 after this PR.
using blockSize as a switch to indicate existence is anyway a bad practise.

2021-03-18 05:45 UTC, apc999 commented on core/client/fs/src/main/java/alluxio/client/block/stream/DataWriter.java
> -        return LocalFileDataWriter.create(context, address, blockId, options);
`LocalFileDataWriter.create` was not taking advantage of block size information

2021-03-18 05:46 UTC, apc999 commented on job/server/src/main/java/alluxio/job/util/JobUtils.java
> -    URIStatus status = fs.getStatus(new AlluxioURI(path));
take RPC out of the loop

2021-03-18 05:47 UTC, apc999 commented on job/server/src/main/java/alluxio/job/util/JobUtils.java
> -        blockStore.getOutStream(blockId, -1, localNetAddress, outOptions)) {
we know blockSize, just fill it, using -1 is very confusing

2021-03-18 18:22 UTC, calvinjia requested changes
Thanks for cleaning this up!

2021-03-18 18:22 UTC, calvinjia commented on job/server/src/main/java/alluxio/job/plan/load/LoadDefinition.java
> +          status, context.getFsContext(), task.getBlockId());
One line

2021-03-18 18:22 UTC, calvinjia commented on job/server/src/main/java/alluxio/job/util/JobUtils.java
> +    BlockInfo blockInfo = status.getBlockInfo(blockId);
Remove the comment above?

2021-03-19 21:00 UTC, calvinjia approved these changes

2021-03-20 00:34 UTC, apc999 commented
alluxio-bot, merge this please

2021-03-20 00:34 UTC, merged