Add index file option for distributedLoad command
Alluxio/alluxio pull request #13170
Opened 2021-04-03 21:12 UTC by jenoudet

Close #12553

2021-04-05 17:23 UTC, yuzhu requested changes
@jenoudet Thanks for the fix! Left a few comments and also could you fix the checkstyle? 

Thanks.

2021-04-05 17:23 UTC, yuzhu commented on shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
> +      FileInStream is = mFileSystem.openFile(path);
did we decide to use local file system for the index file path? if  that is the case, perhaps use `BufferedReader` ? something like `BufferedReader br = new BufferedReader(path);`

2021-04-05 17:23 UTC, yuzhu commented on tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java
> +    FileOutStream out = sFileSystem.createFile(uri);
Similarly, could we use a local file system path for the index file?

2021-04-06 02:18 UTC, yuzhu requested changes
@jenoudet Overall looks good, just one minor comment.

2021-04-06 02:18 UTC, yuzhu commented on tests/src/test/java/alluxio/client/cli/fs/command/DistributedLoadCommandTest.java
> +    String dir = System.getProperty("user.dir");
Consider using a `TemporaryFolder` provided by JUnit? 
```  
@Rule
  public TemporaryFolder mTestFolder = new TemporaryFolder();
```

2021-04-06 17:56 UTC, yuzhu approved these changes
LGTM. thanks

2021-04-08 22:38 UTC, apc999 commented on shell/src/main/java/alluxio/cli/fs/command/DistributedLoadCommand.java
> +          .required(false)
how about
```
      Option.builder()
          .longOpt("index")
```

2021-04-08 22:39 UTC, apc999 commented
@jenoudet one minor comment left on the option name. I prefer to use `--index` and leave `-f` for some other future use.
Otherwise, this looks good to me. Thanks!

2021-04-19 05:15 UTC, apc999 approved these changes
Thanks for your contribution!

2021-04-19 05:16 UTC, apc999 commented
alluxio-bot, merge this please

2021-04-19 05:16 UTC, merged