Update default client pool size to accommodate more concurrent computes
Alluxio/alluxio pull request #13197
Opened 2021-04-08 16:43 UTC by ns1123

In light of some recent findings with Presto concurrency, updating the pool max can save users some trouble with hitting concurrency bottlenecks with high load clients (e.g. Presto Coordinator split-loading)

2021-04-08 21:24 UTC, calvinjia requested changes
Do you mind regenerating the conf documentation?

2021-04-09 17:18 UTC, ns1123 commented
docGen shows that a bunch of our prior commits didn't update docs. I'll raise a PR after this to reset and then we can try to keep doc changes in line with the commits from then on.

2021-04-09 17:24 UTC, calvinjia approved these changes

2021-04-09 17:24 UTC, calvinjia commented
alluxio-bot, merge this please.

2021-04-09 17:24 UTC, merged