Create target path for csv sink
Alluxio/alluxio pull request #13202
Opened 2021-04-08 22:06 UTC by HelloHorizon

Fix #12702

2021-04-09 07:11 UTC, apc999 requested changes
thanks for the improvement!
minor comments left

2021-04-09 07:11 UTC, apc999 commented on core/common/src/main/java/alluxio/metrics/sink/CsvSink.java
> +
nit: unnecessary empty line

2021-04-09 07:11 UTC, apc999 commented on core/common/src/main/java/alluxio/metrics/sink/CsvSink.java
> +
ditto

2021-04-09 07:11 UTC, apc999 commented on core/common/src/main/java/alluxio/metrics/sink/CsvSink.java
> +  private File mFile;
- `final` ? put `final` whenever possible
- should be `mDir` as this indicates poll dir?

2021-04-09 07:11 UTC, apc999 commented on core/common/src/main/java/alluxio/metrics/sink/CsvSink.java
> +        LOG.warn("Fail to create path {} for CSV sink, {}", path.toString(), e.getMessage());
nit: `toString()` is implied here

```suggestion
        LOG.warn("Fail to create path {} for CSV sink, {}", path, e.getMessage());
```

2021-04-09 19:34 UTC, HelloHorizon commented
Thanks @apc999 for the review! Addressed your comments.

2021-04-10 05:48 UTC, apc999 approved these changes

2021-04-10 05:48 UTC, apc999 commented
alluxio-bot, merge this please

2021-04-10 05:48 UTC, merged