Fix shell command "test " cannot differentiate exception and "false" result
Alluxio/alluxio pull request #13293
Opened 2021-04-26 08:00 UTC by codings-dan

Fix #10385

2021-04-26 12:19 UTC, gpang requested changes
@codings-dan Thanks for the improvement!

2021-04-26 12:19 UTC, gpang commented on shell/src/main/java/alluxio/cli/fs/command/TestCommand.java
> +    } catch (IOException e){
```suggestion
    } catch (IOException e) {
```

2021-04-26 12:19 UTC, gpang commented on shell/src/main/java/alluxio/cli/fs/command/TestCommand.java
> +    }catch (AlluxioException e){
```suggestion
    } catch (AlluxioException e) {
```

2021-04-26 13:49 UTC, codings-dan commented
> Automated checks report:
> 
> * Commits associated with Github account: PASS
> * PR title follows the conventions: PASS
> 
> All checks passed!

2021-04-26 13:50 UTC, codings-dan commented
@gpang Thanks for reviewing my code

2021-04-26 13:52 UTC, codings-dan commented
> > Automated checks report:
> > 
> > * Commits associated with Github account: PASS
> > * PR title follows the conventions: PASS
> > 
> > All checks passed!

2021-04-26 19:40 UTC, apc999 approved these changes

2021-04-27 21:10 UTC, LuQQiu commented
```
Error: 1.293 [ERROR] Failures: 
Error: 1.293 [ERROR] alluxio.client.cli.fs.command.TestCommandIntegrationTest.testDirNotEmptyWhenPathNotExist
Error: 1.293 [ERROR]   Run 1: TestCommandIntegrationTest.testDirNotEmptyWhenPathNotExist:92 expected:<1> but was:<3>
Error: 1.293 [ERROR]   Run 2: TestCommandIntegrationTest.testDirNotEmptyWhenPathNotExist:92 expected:<1> but was:<3>
20:24:31.293 [INFO] 
Error: 1.293 [ERROR] alluxio.client.cli.fs.command.TestCommandIntegrationTest.testFileZeroLengthWhenPathNotExist
Error: 1.294 [ERROR]   Run 1: TestCommandIntegrationTest.testFileZeroLengthWhenPathNotExist:133 expected:<1> but was:<3>
Error: 1.294 [ERROR]   Run 2: TestCommandIntegrationTest.testFileZeroLengthWhenPathNotExist:133 expected:<1> but was:<3>
20:24:31.294 [INFO] 
Error: 1.294 [ERROR] alluxio.client.cli.fs.command.TestCommandIntegrationTest.testPathExistWhenPathNotExist
Error: 1.294 [ERROR]   Run 1: TestCommandIntegrationTest.testPathExistWhenPathNotExist:71 expected:<1> but was:<3>
Error: 1.294 [ERROR]   Run 2: TestCommandIntegrationTest.testPathExistWhenPathNotExist:71 expected:<1> but was:<3>
20:24:31.295 [INFO] 
Error: 1.295 [ERROR] alluxio.client.cli.fs.command.TestCommandIntegrationTest.testPathIsDirectoryWhenPathNotExist
Error: 1.295 [ERROR]   Run 1: TestCommandIntegrationTest.testPathIsDirectoryWhenPathNotExist:29 expected:<1> but was:<3>
Error: 1.295 [ERROR]   Run 2: TestCommandIntegrationTest.testPathIsDirectoryWhenPathNotExist:29 expected:<1> but was:<3>
20:24:31.295 [INFO] 
Error: 1.295 [ERROR] alluxio.client.cli.fs.command.TestCommandIntegrationTest.testPathIsFileWhenPathNotExist
Error: 1.296 [ERROR]   Run 1: TestCommandIntegrationTest.testPathIsFileWhenPathNotExist:50 expected:<1> but was:<3>
Error: 1.296 [ERROR]   Run 2: TestCommandIntegrationTest.testPathIsFileWhenPathNotExist:50 expected:<1> but was:<3>
```
@codings-dan Looks like our integration tests failed because of the changes, can you help update the test as well?

2021-04-29 04:00 UTC, codings-dan commented
@LuQQiu Thanks for reveiwing my code, I have updated the test file

2021-04-29 10:54 UTC, gpang approved these changes
LGTM

2021-04-29 17:51 UTC, apc999 commented
alluxio-bot, merge this please

2021-04-29 17:51 UTC, merged