Print all live masters addresses to fsadmin report
Alluxio/alluxio pull request #13330
Opened 2021-05-01 22:19 UTC by ssz1997

When doing command `fsadmin report`, not only the leader master address is showed, all addresses of live masters are now being printed for more complete information.

2021-05-02 00:17 UTC, LuQQiu commented
@ssz1997 As you can see there is some error message saying that "Some checks were not successful". In this PR, the Java 8/11 unit tests failed. 
- Click the `Details` button of the failed Java 8/11 Unit tests
- Close the `Generate coverage report` and open the `Run tests`
- The console shows mvn failure results ` [ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project alluxio-shell: There are test failures.`
- Search `[ERROR] Tests run` and find
```
Error: 7.720 [ERROR] alluxio.cli.fsadmin.report.SummaryCommandTest.summary  Time elapsed: 1.227 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: iterable containing ["Alluxio cluster summary: ", "    Master Address: testAddress", "    Web Port: 1231", "    Rpc Port: 8462", "    Started: 11-06-2005 01:59:03:122", "    Uptime: 143 day(s), 15 hour(s), 53 minute(s), and 32 second(s)", "    Version: testVersion", "    Safe Mode: false", "    Zookeeper Enabled: true", "    Zookeeper Addresses: ", "        [zookeeper_hostname1]:2181", "        [zookeeper_hostname2]:2181", "        [zookeeper_hostname3]:2181", "    Live Workers: 12", "    Lost Workers: 4", "    Total Capacity: 1309.92KB", "        Tier: MEM  Size: 1309.92KB", "        Tier: DOM  Size: 230.96KB", "        Tier: RAM  Size: 22.57KB", "    Used Capacity: 60.97KB", "        Tier: MEM  Size: 60.97KB", "        Tier: DOM  Size: 72.50KB", "        Tier: RAM  Size: 6.10KB", "    Free Capacity: 1248.94KB"]
     but: item 1: was "    Leader Master Address: testAddress"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
```
Please fix the `SummaryCommandTest`.

2021-05-05 03:08 UTC, ssz1997 commented
@LuQQiu I'm only printing out the host of each NetworkAddress object, which I think is the same as the "address"?

2021-05-05 17:20 UTC, LuQQiu requested changes
Thanks for modifying the Summary command and the related tests. Left some comments

2021-05-05 17:20 UTC, LuQQiu commented on shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
> +        .addMasterAddresses(NetAddress.newBuilder().setHost("testAddress2").build())
Can we test multiple master addresses, like 3 masters here including the leader master address?

2021-05-05 17:20 UTC, LuQQiu commented on shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
> +        "    Number of Other Live Masters: 1",
An Alluxio cluster in fault-tolerant mode only has 3 or 5 masters, unlike workers which can be hundreds or thousands. If the information can be shown obviously in one line, we don't need to use two lines.

2021-05-05 17:20 UTC, LuQQiu commented on shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
> +        .addMasterAddresses(NetAddress.newBuilder().setHost("testAddress2").build())
The master addresses should include the leader master address and are better to include three master net addresses. Three is a typical number to achieve fault tolerance.

2021-05-10 20:59 UTC, LuQQiu commented
@ssz1997 I ran the command locally the result is
```
 ~/alluxioFolder/alluxio  pr-now *151 ?2  bin/alluxio fsadmin report                                                                                                              255
Alluxio cluster summary:
    Number of Live Masters: 2
    Leader Master Address: localhost:19998
    Live Masters Addresses: localhost:19998, localhost
```
The conf is
```
alluxio.master.hostname=localhost
```
Please help 
1. Remove the number of live masters since in our use cases, the master number is usually no more than 5. The master number is obvious and no need to use an extra line to show this information.
2. Do not add the leader master address to live master addresses since the live master addresses already include the leader master address
3. Include the ports information in the live masters addresses information. (e.g. localhost:19998 instead of localhost)

2021-05-13 20:06 UTC, LuQQiu requested changes
Left two minor comments, otherwise LGTM

2021-05-13 20:06 UTC, LuQQiu commented on shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
>          .setLeaderMasterAddress("testAddress")
add port information? like "testAddress:19998" to similar to local test results?

2021-05-13 20:06 UTC, LuQQiu commented on shell/src/test/java/alluxio/cli/fsadmin/report/SummaryCommandTest.java
> +        .addMasterAddresses(NetAddress.newBuilder().setHost("testAddress").build())
set Port as well?

2021-05-13 22:11 UTC, LuQQiu approved these changes
LGTM! Thanks for making those helpful changes!

2021-05-13 22:12 UTC, LuQQiu commented
alluxio-bot, merge this please!

2021-05-13 22:12 UTC, merged