Fix Alluxio/new-contributor-tasks#586
Alluxio/alluxio pull request #13392
Opened 2021-05-11 11:03 UTC by kuszz

issue586

2021-05-11 21:01 UTC, apc999 commented on core/common/src/main/java/alluxio/Constants.java
> +  public static final String MEDIUM_HDD = "HDD";
@LuQQiu @ggezer  shall we create a static class `Medium.java` and make three static member String constants called `MEM`, `SSD`, `HDD` ?  I slightly incline for this approach as we can make more fancy changes in the future in this class. But I am also cool for the current solution.. I will leave this up to you

2021-05-12 02:13 UTC, maobaolong requested changes
@kuszz Thank you for your contribution
 `/usr/src/alluxio/core/common/src/test/java/alluxio/wire/BlockMasterInfoTest.java:15: error: 'com.fasterxml.jackson.databind.ObjectMapper' should be separated from previous import group.`

From the build log, you can find that there are a style issue, please take a look.

2021-05-12 07:44 UTC, kuszz commented
> @kuszz Thank you for your contribution
> `/usr/src/alluxio/core/common/src/test/java/alluxio/wire/BlockMasterInfoTest.java:15: error: 'com.fasterxml.jackson.databind.ObjectMapper' should be separated from previous import group.`
> 
> From the build log, you can find that there are a style issue, please take a look.

hi, i have modified the code for the style issue, please take a look.

2021-05-12 16:08 UTC, maobaolong commented
@kuszz There is a conflicting file issue, please take a look, thank you.

2021-05-12 17:52 UTC, LuQQiu commented
@kuszz the following commands help solve the conflicts:
```
git fetch upstream
git merge upstream/aster
git commit -am "before solving conflicts"
# make actual changes to solve the conflicting files
git commit -am "solve conflicts"
git push origin iss586
```

2021-05-15 05:11 UTC, LuQQiu commented
```
Error: 3.022 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project alluxio-core-server-master: Failed during checkstyle execution: There are 54 errors reported by Checkstyle 6.11.2 with /usr/src/alluxio/build/checkstyle/alluxio_checks.xml ruleset. -> [Help 1]
Error: 3.023 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project alluxio-job-server: Failed during checkstyle execution: There is 1 error reported by Checkstyle 6.11.2 with /usr/src/alluxio/build/checkstyle/alluxio_checks.xml ruleset. -> [Help 1]
Error: 3.024 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.17:check (checkstyle) on project alluxio-core-server-worker: Failed during checkstyle execution: There are 37 errors reported by Checkstyle 6.11.2 with /usr/src/alluxio/build/checkstyle/alluxio_checks.xml ruleset. -> [Help 1]
```
@kuszz Please make sure `mvn checkstyle:checkstyle` passed

2021-05-17 11:39 UTC, closed without merging