Consolidate usage of tier names in the repo
Alluxio/alluxio pull request #13431
Opened 2021-05-17 11:41 UTC by kuszz

solve the checkstyle errors #586

2021-05-17 17:49 UTC, maobaolong requested changes
There are so many wrap line indent issue,  i just left comments within some of them, please take a complete look at this PR, ensure you fix all the wrap line issue.

2021-05-17 17:49 UTC, maobaolong commented on core/server/master/src/test/java/alluxio/master/file/FileSystemMasterTest.java
> +            Arrays.asList(Constants.MEDIUM_MEM, Constants.MEDIUM_SSD),
Fix the wrap indent  from 8 to 4 to keep consistent with others

2021-05-17 17:49 UTC, maobaolong commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +
Remove this empty line.

2021-05-17 17:49 UTC, maobaolong commented on core/common/src/test/java/alluxio/conf/InstancedConfigurationTest.java
> +            Constants.MEDIUM_SSD, "hdd", "unknown")) {
Fix the wrap indent from 8 to 4 to keep consistent with others

2021-05-17 17:49 UTC, maobaolong commented on core/server/common/src/test/java/alluxio/AbstractStorageTierAssocTest.java
> +            Constants.MEDIUM_HDD, "SOMETHINGELSE", Constants.MEDIUM_SSD);
Fix the wrap indent from 8 to 4 to keep consistent with others

2021-05-17 17:49 UTC, maobaolong commented on core/server/common/src/test/java/alluxio/AbstractStorageTierAssocTest.java
> +            BlockStoreLocation.anyDirInTier(Constants.MEDIUM_MEM));
Fix the wrap indent from 8 to 4 to keep consistent with others

2021-05-17 17:49 UTC, maobaolong commented on core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
> +            ImmutableMap.of(Constants.MEDIUM_MEM, 10L, Constants.MEDIUM_SSD, 20L);
Fix the wrap indent from 8 to 4 to keep consistent with others

2021-05-17 17:49 UTC, maobaolong commented on core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
> +            ImmutableMap.of(Constants.MEDIUM_MEM, 100L),
Fix the wrap indent from 8 to 4 to keep consistent with others

2021-05-17 17:49 UTC, maobaolong commented on core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
> +            Constants.MEDIUM_MEM, Constants.MEDIUM_MEM, blockId, 20L);
Fix the wrap indent from 8 to 4 to keep consistent with others

2021-05-17 17:49 UTC, maobaolong commented on core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
> +            ImmutableMap.of(Constants.MEDIUM_MEM, 100L),
Fix the wrap indent from 8 to 4 to keep consistent with others

2021-05-17 17:49 UTC, maobaolong commented on core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
> +            memUsage, NO_BLOCKS, NO_BLOCKS_ON_LOCATION, NO_LOST_STORAGE, mMetrics);
Fix the wrap indent from 8 to 4 to keep consistent with others

2021-05-17 17:49 UTC, maobaolong commented on core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
> +            ImmutableMap.of(Constants.MEDIUM_MEM, 100L),
Fix the wrap indent from 8 to 4 to keep consistent with others

2021-05-17 17:49 UTC, maobaolong commented on core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
> +            ImmutableMap.of(Constants.MEDIUM_MEM, 100L),
Fix the wrap indent from 8 to 4 to keep consistent with others

2021-05-17 17:49 UTC, maobaolong commented on core/server/master/src/test/java/alluxio/master/meta/AlluxioMasterRestServiceHandlerTest.java
> +          ImmutableMap.of(Constants.MEDIUM_MEM, 10L,
Fix the wrap indent from 8 to 4 to keep consistent with others

2021-05-18 12:53 UTC, kuszz commented
@LuQQiu @maobaolong  Thanks for pointing out the mistakes，please approve the pr , I have build and run in my machine,  thanks

2021-05-18 14:39 UTC, LuQQiu commented
@kuszz Every time you make changes to the PR, the PR build will be retriggered. Because you are the first-time contributor, the build needs to be approved to be run. Need to PR build to be passed to merge the PR

2021-05-18 14:41 UTC, LuQQiu commented
A good convention is that try not to use force-push unless necessary. Through normal push, reviewers can see your changes according to the reviews instead of need to review the whole PR again. No worry for this PR but please follow in the next PRs

2021-05-18 18:58 UTC, LuQQiu commented
alluxio-bot, merge this please

2021-05-18 18:58 UTC, merged

2021-05-18 18:59 UTC, LuQQiu commented
Congrats! @kuszz This PR is actually much more complicated than a new contributor PR, you have done a great job! Thanks a lot for making those useful changes!

2021-05-19 02:24 UTC, kuszz commented
> A good convention is that try not to use force-push unless necessary. Through normal push, reviewers can see your changes according to the reviews instead of need to review the whole PR again. No worry for this PR but please follow in the next PRs

Thanks for your help and advice, I will be careful to follow the convention in the next PRs