Add maven and pom instructions
Alluxio/alluxio pull request #13432
Opened 2021-05-17 15:47 UTC by yuzhu

2021-05-17 19:25 UTC, Xenorith requested changes
would like more content about maven with relation to the PR checks

2021-05-17 19:25 UTC, Xenorith commented on docs/en/contribution-roadmap/Knowledge.md
> +mvn -T 4C clean  install -Dmaven.javadoc.skip=true -DskipTests -Dlicense.skip=true -Dcheckstyle.skip=true -Dfindbugs.skip=true  -Phadoop-2 -Dhadoop.version=2.7.3 -Pufs-hadoop-3  -Dufs.hadoop.version=
remove the double spaces? there are 3 of them, ex. between clean and install

2021-05-17 19:25 UTC, Xenorith commented on docs/en/contribution-roadmap/Knowledge.md
> +
can you give other example maven commands to run specific checks? for example, each of the skipped checks i believe can be run individually; this helps when fixing the build checks. ex. how do only run findbugs or only run checkstyle?

2021-05-17 19:25 UTC, Xenorith commented on docs/en/contribution-roadmap/Knowledge.md
> +
can you add a section about the maven build checks that are run by github actions? i found that most people will be able to get to the console log to see the BUILD FAILED at the bottom but it is not intuitive to find the specific failures.

2021-07-02 22:50 UTC, apc999 commented on docs/en/contribution-roadmap/Knowledge.md
> +```bash
```suggestion
```console
```

2021-07-02 22:50 UTC, apc999 commented on docs/en/contribution-roadmap/Knowledge.md
> +```bash
ditto

2021-07-02 22:50 UTC, apc999 commented
@yuzhu  do you plan to finish this PR?

2021-07-13 01:04 UTC, LuQQiu commented
@yuzhu i will merge this PR and solve the comments in next PR

2021-07-13 01:04 UTC, LuQQiu approved these changes

2021-07-13 01:05 UTC, LuQQiu commented
alluxio-bot, merge this please

2021-07-13 01:05 UTC, merged

2021-07-13 01:20 UTC, LuQQiu commented
@apc999 @Xenorith @HelloHorizon @yuzhu for contribution roadmap, I prefer to go with fast iteration instead of asking for a really high-quality roadmap. Will be much more efficient in a way that similar to google docs: everyone can modify the roadmap concurrently, no need to be perfect in the beginning. 

For faster iteration, I will prefer to leave TODOs for some bigger scope review comments in the contribution roadmap just like https://github.com/Alluxio/alluxio/pull/13780

what's your thoughts?

I am asking for this because I found a small section in the contribution roadmap can take me or David or other people a really long period to finish and thus ... the contribution roadmap will forever in the beginning state.