Store workerId
Alluxio/alluxio pull request #13474
Opened 2021-05-24 03:30 UTC by kuszz

#13473

2021-05-24 07:00 UTC, kuszz commented
It seems need to modify code: formatting worker need to clean the file

2021-05-24 16:20 UTC, maobaolong requested changes
@kuszz Thanks for this useful improvement, left some comments inline.

2021-05-24 16:20 UTC, maobaolong commented on core/transport/src/main/proto/proto/worker/worker_meta.proto
> +}
A new line is necessary

2021-05-24 16:20 UTC, maobaolong commented on core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
> +      throws BlockDoesNotExistException, IOException {
revert the unnecessary changes.

2021-05-24 16:20 UTC, maobaolong commented on core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
> +            .format("Failed to read block ID=%s from tiered storage and UFS tier: %s",
Revert the unnecessary

2021-05-24 16:20 UTC, maobaolong commented on core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
> +        new HeartbeatThread(HeartbeatContext.WORKER_BLOCK_SYNC, mBlockMasterSync,
Revert the unnecessary changes

2021-05-24 16:20 UTC, maobaolong commented on core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
> +  public long getWorkerId(WorkerNetAddress workerNetAddress, long workerId) {
abstract a method to reduce the duplicated code.

2021-05-24 16:20 UTC, maobaolong commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +              + File.separator + "workerInfo.properties")
Is this file human readable?

2021-05-24 16:20 UTC, maobaolong commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +    public static final String WORKER_INFO_FILE = "alluxio.work.info.file";
work -> worker

2021-05-25 08:20 UTC, kuszz commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +              + File.separator + "workerInfo.properties")
No, persistence by protobuf

2021-06-02 13:58 UTC, maobaolong requested changes
Left some comments, please take a look, and resolve the conflict issue.

2021-06-02 13:58 UTC, maobaolong commented on core/server/common/src/main/java/alluxio/cli/Format.java
> +        new File(ServerConfiguration.get(PropertyKey.WORKER_INFO_FILE)).delete();
Files.deleteIfExists(Paths.get(ServerConfiguration.get(PropertyKey.WORKER_INFO_FILE))

2021-06-02 13:58 UTC, maobaolong commented on core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
> +  private long _getWorkerId(WorkerNetAddress workerNetAddress) {
_getWorkerId -> getWorkerIdInternal

2021-06-02 13:58 UTC, maobaolong commented on core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
> +      try (FileInputStream input = new FileInputStream(file)) {
Abstract two private method to make the method body here be more clear

2021-06-02 13:58 UTC, maobaolong commented on core/server/worker/src/main/java/alluxio/worker/block/DefaultBlockWorker.java
> +      file.createNewFile();
CreateNewFile here is not necessary, because the new FileOutputStream(file) will create a file if it is not exist as far as I know. please verify.

2021-06-15 09:58 UTC, jiacheliu3 commented
Hi @kuszz I added my comment to your design doc https://docs.google.com/document/d/11MCHlgx0MP5_SN2JRP9Myd9A528TS0rTLt-3U-ssTaw/edit#
Can we first settle on the design doc then move on to the implementation? Thanks.

2021-06-16 02:55 UTC, kuszz commented
> Hi @kuszz I added my comment to your design doc https://docs.google.com/document/d/11MCHlgx0MP5_SN2JRP9Myd9A528TS0rTLt-3U-ssTaw/edit#
> Can we first settle on the design doc then move on to the implementation? Thanks.

Thanks, I have replied your comment in doc

2021-06-25 17:48 UTC, apc999 commented
@kuszz , we are working on optimizing worker registration (led by @jiacheliu3 ), hopefully by 2.7.

2021-06-30 20:01 UTC, apc999 commented
@kuszz @jiacheliu3 @maobaolong , as we discussed in offline sync, we want to resolve #13473 by reproducing the issue of losing data on a worker restarted. That should be bug if happening again. Keeping worker stateless is still preferred.

I'm closing this PR for now, we can re-open it if needed

2021-06-30 20:01 UTC, closed without merging

2021-07-01 02:10 UTC, kuszz commented
> @kuszz , we are working on optimizing worker registration (led by @jiacheliu3 ), hopefully by 2.7.
> When we are working on the design, we will include you and @maobaolong and see how to incorporate ideas here.
> For now, can we hold on implementing this feature as it may conflict with potential design.
> Better to be aligned before we start implementing this idea.

Ok, got it