Fix the wrong indentation to pass grammar check
Alluxio/alluxio pull request #13788
Opened 2021-07-14 06:18 UTC by maobaolong

Fix #13785

2021-07-14 10:34 UTC, jiacheliu3 approved these changes
LGTM, thanks @maobaolong !

2021-07-14 10:43 UTC, jiacheliu3 requested changes
Please also mention this change in the CHANGELOG
https://github.com/Alluxio/alluxio/blob/master/integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
and https://github.com/Alluxio/alluxio/blob/master/integration/kubernetes/helm-chart/alluxio/Chart.yaml
Thanks!

2021-07-14 10:44 UTC, jiacheliu3 commented
I will merge this change after the change above is added

2021-07-14 10:57 UTC, maobaolong commented
@jiacheliu3 Thanks for your review and suggestion, I upgrade the version and change log of alluxio helm chart,  PTAL.

2021-07-14 12:38 UTC, jiacheliu3 requested changes
@maobaolong One last minor typo to change. The version you see is 0.6.22 just because that guy forgot to update it to 0.6.23

2021-07-14 12:38 UTC, jiacheliu3 commented on integration/kubernetes/helm-chart/alluxio/Chart.yaml
> +version: 0.6.23
@maobaolong This should be 0.6.24?

2021-07-14 13:17 UTC, maobaolong commented on integration/kubernetes/helm-chart/alluxio/Chart.yaml
> +version: 0.6.23
Yeah, exactly.

2021-07-14 13:17 UTC, maobaolong commented
@jiacheliu3 Thanks for the quick review, PTAL.

2021-07-14 13:40 UTC, jiacheliu3 approved these changes
LGTM, thanks @maobaolong ! Will merge on tests all pass

2021-07-15 05:45 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2021-07-15 05:45 UTC, merged