Invalid cache after write operation
Alluxio/alluxio pull request #13790
Opened 2021-07-14 07:57 UTC by maobaolong

Fix #13186

2021-07-14 08:07 UTC, maobaolong commented
Hi @apc999 Please take a look at this PR, thanks.

2021-07-15 17:57 UTC, apc999 requested changes
@maobaolong thanks for the improvement. The code looks good to me. can you

1. update PR description, so we can see more details in git commit history
2. add unit test of invalidate?

2021-07-15 18:12 UTC, apc999 commented on core/client/fs/src/main/java/alluxio/client/file/MetadataCache.java
> +   * Invalidate the cache of path.
nit:
```suggestion
   * Invalidates the cache of path.
```

2021-07-15 18:12 UTC, apc999 commented on core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
> +      AlluxioException {
```suggestion
      throws IOException, AlluxioException {
```

2021-07-15 18:13 UTC, apc999 commented on core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
> +      AlluxioException {
can you fix the format and following?

2021-07-15 18:16 UTC, apc999 commented on core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
> +  public void delete(AlluxioURI path)
override this method, which is the default impl of `delete`
```suggestion
  rename(AlluxioURI src, AlluxioURI dst, RenamePOptions options)
```

2021-07-15 18:18 UTC, apc999 commented on core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
> +  }
default impl of `delete(AlluxioURI)` is based on `delete(AlluxioURI, DeletePOptions)`. 
So you don't need both

```suggestion
  public void delete(AlluxioURI path)
      throws IOException,
      AlluxioException {
    super.delete(path);
    mMetadataCache.invalidate(path.getParent());
    mMetadataCache.invalidate(path);
  }
```

2021-07-15 18:22 UTC, apc999 commented on core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
> +  public void createDirectory(AlluxioURI path, CreateDirectoryPOptions options)
add `public void createDirectory(AlluxioURI path)` too?

2021-07-15 18:25 UTC, apc999 commented on core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
> +    mMetadataCache.invalidate(path);
shall we invalidate the cache first before modifying file system, to be conservative?
```suggestion
    mMetadataCache.invalidate(path.getParent());
    mMetadataCache.invalidate(path);
    super.createDirectory(path, options);

```

2021-07-15 23:13 UTC, maobaolong commented on core/client/fs/src/main/java/alluxio/client/file/MetadataCachingBaseFileSystem.java
> +  public void createDirectory(AlluxioURI path, CreateDirectoryPOptions options)
Sure

2021-07-15 23:14 UTC, maobaolong commented
@apc999 Thanks for the review and suggestion, addressed your comments except the adding ut request, will add it soon

2021-07-16 02:45 UTC, apc999 commented on tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
> +//    o.sync();
revert change to this file?

2021-07-16 02:45 UTC, apc999 commented
Can you revert the change in `tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java`? Otherwise, LGTM

2021-07-16 03:28 UTC, maobaolong commented
@apc999 Thanks for pointing out my bad, I revert the accidental changes, PTAL

2021-07-16 04:35 UTC, apc999 approved these changes

2021-07-16 04:35 UTC, apc999 commented
alluxio-bot, merge this please

2021-07-16 04:35 UTC, merged