Update Security.md
Alluxio/alluxio pull request #13791
Opened 2021-07-14 13:12 UTC by langlaile1221

Added description of common exceptions

2021-07-14 18:00 UTC, apc999 requested changes
comments on translation. Thanks for the improvement

2021-07-15 02:22 UTC, langlaile1221 commented on docs/cn/operation/Security.md
> +这个错误意味着用户yarn正在试图冒充用户foo连接到Alluxio，但是Alluxio服务并没有配置允许用户yarn启用模拟。为了解决这个问题，Alluxio服务器必须配置允许有问题的用户启用模拟（示例中用户yarn）
Fixed

2021-07-15 18:38 UTC, apc999 approved these changes

2021-07-15 18:38 UTC, apc999 commented
alluxio-bot, merge this please

2021-07-15 18:38 UTC, merged