Fix unused builder for syncing when setting attributes
Alluxio/alluxio pull request #13805
Opened 2021-07-16 21:16 UTC by ZacBlanco

### What changes are proposed in this pull request?

Utilize the unused SetAttribute builder in the metadat sync code.

I confirmed in a previous incarnation of this code
(https://github.com/Alluxio/alluxio/blame/cc0f1308f4a020cab6099a6622e26a729fe4b755/core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java#L3567-L3580)
That the builder was in-fact being used. Seems like it was lost in
translation when migrating the sync code.

### Why are the changes needed?

Could potentially miss updating the owner on the file.

### Does this PR introduce any user facing changes?

no

2021-07-16 22:42 UTC, apc999 commented
possibly to add a UT covering this case?

2021-07-19 20:54 UTC, ggezer approved these changes

2021-07-19 22:32 UTC, ggezer requested changes
lgtm after fixing failing UT.

2021-07-19 22:32 UTC, ggezer commented on core/server/master/src/test/java/alluxio/master/file/FileSystemMasterSyncMetadataTest.java
>    public void listStatusWithSyncMetadataAndEmptyS3Owner() throws Exception {
This is failing consistently.

2021-07-20 17:27 UTC, apc999 approved these changes

2021-07-21 17:19 UTC, ggezer approved these changes

2021-07-21 17:20 UTC, ggezer commented
alluxio-bot, merge this please

2021-07-21 17:20 UTC, merged