Cache filter
Alluxio/alluxio pull request #13844
Opened 2021-07-23 20:27 UTC by BlueStalker

### What changes are proposed in this pull request?

This PR adds the cache filter support in the LocalCacheFileSystem.

### Why are the changes needed?
In a real production system, a local caching node would be able to identify whether need to cache the specific path based on some configuration, eg, particular schema, table, or partitions or even some complicated algo.

### Does this PR introduce any user facing changes?
N/A

2021-07-31 07:17 UTC, apc999 requested changes
I left some minor style comments first. 
Feel free to read:
https://docs.alluxio.io/os/user/stable/en/contributor/Code-Conventions.html#coding-style
I will get back to this PR earlier next week

2021-07-31 07:17 UTC, apc999 commented on core/common/src/main/java/alluxio/client/hive/HiveCacheContext.java
> +        && java.util.Objects.equals(mPartition, that.mPartition);
```suggestion
    return Objects.equals(mDatabase, that.mDatabase)
        && Objects.equals(mTable, that.mTable)
        && Objects.equals(mPartition, that.mPartition);
```

2021-07-31 07:17 UTC, apc999 commented on core/common/src/main/java/alluxio/client/hive/HiveCacheContext.java
> +    this.mPartition = partition;
```suggestion
    mDatabase = database;
    mTable = table;
    mPartition = partition;
```

2021-07-31 07:17 UTC, apc999 commented on core/common/src/main/java/alluxio/client/hive/HiveCacheContext.java
> +{
```suggestion
public class HiveCacheContext {
```

2021-07-31 07:17 UTC, apc999 commented on core/common/src/main/java/alluxio/client/hive/HiveCacheContext.java
> +  {
```suggestion
  public HiveCacheContext(String database, String table, String partition) {
```

2021-08-23 17:25 UTC, beinan approved these changes
lgtm

2021-08-30 23:01 UTC, BlueStalker commented
@apc999 I think there is a flaky tests can you guys probably re-run it?

2021-09-02 00:11 UTC, BlueStalker commented
@apc999 @beinan Can you guys merge the changes then I can do a rebase and internal release

2021-09-05 02:41 UTC, beinan commented
> @apc999 @beinan Can you guys merge the changes then I can do a rebase and internal release

@bin could you help to take a second look?

2021-10-13 05:58 UTC, yuzhu commented
@apc999 could you take a final look? i think @beinan accidentally tagged the wrong person 🤣

2021-11-01 03:13 UTC, maobaolong commented
@BlueStalker After go through this PR, i think this PR just include a cache filter framework with a default all cache filter, would you like to add a DefaultCacheFilterFromConfig?

2021-11-01 18:25 UTC, beinan commented
> @BlueStalker After go through this PR, i think this PR just include a cache filter framework with a default all cache filter, would you like to add a DefaultCacheFilterFromConfig?

@maobaolong I think the default impl has been there,  do you mean implement a cache filter based on a config file?

2021-11-03 02:17 UTC, maobaolong commented
@beinan Yeah, although we have a config key USER_CLIENT_CACHE_FILTER_CONFIG_FILE, but we don't use it from this PR.

2021-11-10 01:33 UTC, beinan commented
> @beinan Yeah, although we have a config key USER_CLIENT_CACHE_FILTER_CONFIG_FILE, but we don't use it from this PR.

We originally intended to leave this implementation to the users themselves,  but I can ask if uber team is able to contribute their implementation in this PR

2021-11-10 11:24 UTC, maobaolong commented
Thanks @beinan for your reply, i'm ok for merge this PR under this status, it would be better to have a DefaultCacheFilterFromConfig, but don't have to add it to this PR.

2021-11-22 11:10 UTC, maobaolong commented
Hi @beinan I'm ok to merge this PR into master branch

2021-11-22 11:10 UTC, maobaolong approved these changes
LGTM

2021-11-23 02:12 UTC, beinan commented
@apc999 do you still want to take a second look? otherwise I will merge this one.

2021-11-25 09:45 UTC, maobaolong commented on core/client/fs/src/main/java/alluxio/client/file/cache/filter/CacheFilter.java
> +        new Object[] {conf, conf.getOrDefault(
Do you think `conf.getOrDefault(PropertyKey.USER_CLIENT_CACHE_FILTER_CONFIG_FILE, "")` is redundant?

2021-11-26 02:10 UTC, maobaolong commented on core/client/fs/src/main/java/alluxio/client/file/cache/filter/CacheFilter.java
> +  /**
There should left an empty line to pass the checkstyle rule.

2021-11-26 02:11 UTC, maobaolong reviewed
@BlueStalker Thanks for the contribution, left two comments.

2022-01-23 08:44 UTC, maobaolong commented
Hi @beinan Would you like to take over this PR?

2022-02-10 06:51 UTC, maobaolong commented
Hi @beinan Look forward to use this great feature.

2022-03-23 09:15 UTC, maobaolong commented
ping @beinan

2022-03-29 20:58 UTC, beinan commented
created https://github.com/Alluxio/alluxio/pull/15226 to take over this PR.  Many thanks to @BlueStalker 's contribution

2022-03-29 20:58 UTC, closed without merging