Add soft kill option to all processes
Alluxio/alluxio pull request #13875
Opened 2021-08-01 02:52 UTC by yabola

### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

2021-08-01 03:37 UTC, yabola commented
My test step(I add test log for see what happened)
`sh bin/alluxio-stop.sh all -s` -->
![image](https://user-images.githubusercontent.com/31469905/127758236-e804f35b-1c7d-4166-8ea7-c01e35d347dd.png)

My umount fuse test step( after merge https://github.com/Alluxio/alluxio/pull/13876)
1. embed mounted dir:
```
alluxio.worker.fuse.enabled=true
alluxio.worker.fuse.mount.alluxio.path=/fuse_data
alluxio.worker.fuse.mount.point=/Users/chenliang.lu/soft/alluxio_data/fuse_data
```
2. open file on fuse dir:
`less /Users/chenliang.lu/soft/alluxio_data/fuse_data/a.txt`
3. stop worker with `-s` option:
   `sh bin/alluxio-stop.sh worker -s` -> worker process doesn't be killed.
![image](https://user-images.githubusercontent.com/31469905/127758308-a3a2edc8-b4f0-4515-b4f7-21f2b46dff01.png)

2021-08-01 22:59 UTC, LuQQiu commented on bin/alluxio
> +  echo -e "  killAll [-s] <WORD>\t Kill processes containing the WORD (if '-s' specified, processes won't be forcibly killed even if operation is timeout)."
processes that timeout with the termination signal won't be killed.

2021-08-02 19:31 UTC, ZhuTopher approved these changes
LGTM, thanks for the improvement!

2021-08-02 20:33 UTC, ZacBlanco requested changes

2021-08-03 15:07 UTC, yabola commented on bin/alluxio
> +    echo "Usage: alluxio killAll [-s] <WORD> (if '-s' specified, processes won't be forcibly killed even if operation is timeout.)" >&2
thanks, down

2021-08-03 15:33 UTC, ZacBlanco approved these changes

2021-08-03 16:07 UTC, ggezer commented
alluxio-bot, merge this please

2021-08-03 16:07 UTC, merged

2021-08-03 18:50 UTC, LuQQiu commented
Does any user-facing document need to be added/updated?
Where do we suggest users use this soft kill option? or it's only designed for advanced users?

2021-08-03 23:15 UTC, ZhuTopher commented
@LuQQiu I don't believe we have any user-facing docs which detail how to use these scripts; it's just the `USAGE:` message in the scripts themselves. If there is a direct use-case for which soft-kill would be useful then we should mention it in the corresponding use-case's doc (if it exists), but otherwise idk if there's anything more to be added. wdyt?