Extract HiveClientPool as an abstract class to facilitate testing
Alluxio/alluxio pull request #13885
Opened 2021-08-03 11:07 UTC by dbw9580

### What changes are proposed in this pull request?

Extract `HiveClientPool` as an abstract class to facilitate testing.

### Why are the changes needed?

Currently there is no way to inject a mocked `IMetaStoreClient` into `HiveDatabase`. Adding the ability to do so facilitates unit testing.

### Does this PR introduce any user facing changes?

No.

2021-08-03 20:22 UTC, HelloHorizon commented
@dbw9580 what is the test you want to add with hive metastore mock? @apc999 I remembered you mentioned we have some best practice guidelines about the mock tests, do you mind taking a look?

2021-08-04 02:09 UTC, dbw9580 commented
> what is the test you want to add with hive metastore mock

I'm adding unit tests for the group mount PR #13654. I need to mock a hive metastore client to emulate a hive database and its tables, so that I can test the group mount behaviour is working as expected.

2021-08-04 02:41 UTC, dbw9580 commented
> I need to mock a hive metastore client to emulate a hive database and its tables

The exact thing I want to do is write a `TestHiveClientPool` that extends the new `HiveClientPool` abstract class, and creates and returns mocked `IMetaStoreClient` from its `acquireClientResource`. With the mocked client, I can provide arbitrary tables and partitions to `HiveDatabase`, and I can test if the group mount behaviour proposed in #13654 is working correctly.

I have investigated some alternatives to the approach proposed in this PR. One is to use the compatibility layer provided by `HMSShim` and `CompatibleMetastoreClient`. They provide a way similar to a mocked client that can be used to return test databases and tables. But they themselves lack unit tests, and it is less straight forward if they are used in other components' unit tests

2021-08-04 05:54 UTC, apc999 requested changes
Minor comments left. Overall looks good to me

2021-08-04 05:54 UTC, apc999 commented on table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java
>      mClientPool = CLIENT_POOL_CACHE.getPool(connectionUri);
```java
private HiveDatabase(UdbContext udbContext, UdbConfiguration configuration,
      String connectionUri, String hiveDbName)  {
  this(udbContext, configuration, connectionUri, hiveDbName, CLIENT_POOL_CACHE.getPool(connectionUri));
}
```

2021-08-04 05:54 UTC, apc999 commented on table/server/underdb/hive/src/main/java/alluxio/table/under/hive/HiveDatabase.java
> +               HiveClientPool clientPool, String connectionUri, String hiveDbName) {
nit: i will recommend to put `clientPool` as the last arg here

2021-08-04 05:54 UTC, apc999 commented on table/server/underdb/hive/src/main/java/alluxio/table/under/hive/util/HiveClientPool.java
> +public abstract class HiveClientPool extends DynamicResourcePool<IMetaStoreClient> {
nit: `AbstractHiveClientPool`

2021-08-04 06:11 UTC, dbw9580 commented
Thanks for the comments @apc999. Revised in 15c42da342a927c9b79b8443abfbd2465d083cbd.

2021-08-04 06:14 UTC, HelloHorizon approved these changes
@dbw9580 Thanks for the improvement! LGTM

2021-08-04 17:28 UTC, HelloHorizon commented
alluxio-bot, merge this please

2021-08-04 17:28 UTC, merged