Stop leaking state-lock when journal is closed
Alluxio/alluxio pull request #13913
Opened 2021-08-09 23:03 UTC by ggezer

Fix https://github.com/Alluxio/alluxio/issues/13904

2021-08-09 23:24 UTC, jenoudet approved these changes

2021-08-10 00:59 UTC, apc999 requested changes
Thanks for the quick fix!

Possibly to create a UT to cover this case?
and we can link the UT to the issue for future references

2021-08-11 06:13 UTC, maobaolong approved these changes
LGTM. Thanks for this fix.

2021-08-11 16:55 UTC, apc999 commented on core/server/master/src/test/java/alluxio/master/journal/JournalContextTest.java
> +    assertTrue(failedAsExpected);
```suggestion
    try {
      mBlockMaster.createJournalContext();
      fail("Should have thrown an exception");
    } catch (UnavailableException e) {
      // expected to fail
    }
```

2021-08-11 16:56 UTC, apc999 approved these changes
Minor comments on the test pattern. 
LGTM modulo the comments

2021-08-11 16:57 UTC, apc999 commented on core/server/master/src/test/java/alluxio/master/journal/JournalContextTest.java
> +  @Test
nit: To link test case to the real issue for more context in the future.
```suggestion
  // See https://github.com/Alluxio/alluxio/issues/13904
  @Test
```

2021-08-11 19:33 UTC, ggezer commented
alluxio-bot, merge this please

2021-08-11 19:33 UTC, merged

2021-08-11 19:33 UTC, ggezer commented
alluxio-bot, cherry-pick this to branch-2.6 please

2021-08-11 19:33 UTC, ggezer commented
alluxio-bot, cherry-pick this to branch-2.5 please

2021-08-11 19:33 UTC, ggezer commented
alluxio-bot, cherry-pick this to branch-2.64 please

2021-08-11 19:33 UTC, ggezer commented
alluxio-bot, cherry-pick this to branch-2.4 please