WIP Mark sensitive information in rpc debug/error log
Alluxio/alluxio pull request #13971
Opened 2021-08-24 10:15 UTC by yyongycy

### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

2021-08-24 10:15 UTC, yyongycy commented
@ggezer @jiacheliu3  please help take a look.

2021-08-25 03:03 UTC, yyongycy commented
The message dumped after masked:
blockHeartbeat: request=bitField0_:3
workerId_:7292113489303911161
properties{
com.google.protobuf.MapField@129b5
}
removedBlockIds_:{
[]
}
metrics_:{
[instance: "Worker"
source: "alluxios-mbp"
name: "BlocksEvictionRate"
value: 0.0
metricType: METER
]
}
properties{
com.google.protobuf.MapField@aaab831d
}
memoizedIsInitialized:1
addedBlocks_:{
[]
}
memoizedIsInitialized:1

2021-08-25 05:07 UTC, yyongycy commented
'alluxio-bot, check this please'

2021-08-25 05:08 UTC, yyongycy commented
> alluxio-bot, check this please

alluxio-bot, check this please

2021-08-30 06:24 UTC, yyongycy commented
pr was updated accordingly.

2021-08-31 15:35 UTC, jiacheliu3 requested changes

2021-08-31 15:35 UTC, jiacheliu3 commented on core/server/common/src/main/java/alluxio/RpcUtils.java
> +  public static final SensitiveConfigMask SENSITIVE_MASKER =
`SENSITIVE_MASKER` grammatically does not make sense. Please just fix it. It is not so hard.

2021-08-31 15:46 UTC, jiacheliu3 approved these changes

2021-08-31 21:06 UTC, ggezer approved these changes
Thanks!

2021-08-31 21:06 UTC, ggezer commented on core/server/common/src/main/java/alluxio/RpcUtils.java
> +                  SENSITIVE_CONFIG_MASKER == null
Please move this macro into a method, e.g processArgs(), and use it instead.

2021-09-01 02:23 UTC, jiacheliu3 commented
Tests all passed and comments resolved

2021-09-01 02:23 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2021-09-01 02:23 UTC, merged

2021-09-01 04:16 UTC, jiacheliu3 commented
@ggezer Which branches should this be cherry-picked to?

2021-09-28 22:54 UTC, Xenorith commented
alluxio-bot, cherry-pick this to branch-2.6 please