[DOCFIX] Add some key metrics to the tuning docs
Alluxio/alluxio pull request #14049
Opened 2021-09-09 23:57 UTC by yuzhu

### What changes are proposed in this pull request?

Add descriptions of key metrics relevant to tuning

### Why are the changes needed?
Make it more clear and easy to find critical metrics

### Does this PR introduce any user facing changes?
Doc  changes

2021-09-16 01:12 UTC, apc999 requested changes
comments left. Thanks for the improvement!

2021-09-16 01:12 UTC, apc999 commented on docs/en/operation/Performance-Tuning.md
> +When we are going to UFS for the data, we are sacrificing performance and incurring additional cost. This is usually the biggest red flag.
let's avoid using "we" but "Alluxio" to be more precise?

2021-09-16 01:12 UTC, apc999 commented on docs/en/operation/Performance-Tuning.md
> +### Slow metadata sync
can you give a example here when we can tell we have slow metadata sync?

2021-09-16 01:12 UTC, apc999 commented on docs/en/operation/Scalability-Tuning.md
> +* Master.TotalBlocks
I think this one is replaced by Master.UniqueBlocks and Master.BlockReplicaCount?

2021-09-16 01:12 UTC, apc999 commented on docs/en/operation/Performance-Tuning.md
> + * Check dmesg -T | egrep -i 'killed process'
```suggestion
 * Check `dmesg -T | egrep -i 'killed process'`
```

2021-09-20 23:33 UTC, yuzhu commented
@apc999 PTAL again thanks.

2021-09-21 19:04 UTC, apc999 approved these changes

2021-09-21 19:04 UTC, apc999 commented
alluxio-bot, merge this please

2021-09-21 19:04 UTC, merged