Fix `startMasters()` from receiving unchecked exceptions
Alluxio/alluxio pull request #14353
Opened 2021-10-29 20:11 UTC by jenoudet

`FaultTolerantAlluxioMasterProcess` calls `startMasters` when gaining primacy, which can throw a `NotLeaderException` if the master has already lost the leadership, crashing the master. This PR handles this error

2021-10-29 21:51 UTC, ggezer requested changes

2021-10-29 21:51 UTC, ggezer commented on core/server/master/src/main/java/alluxio/master/AlluxioMasterProcess.java
> +  protected void startMasters(boolean isLeader) throws IOException {
This method will never throw `IOException` but only `RuntimeException`.

2021-10-29 21:51 UTC, ggezer commented on core/server/master/src/main/java/alluxio/master/FaultTolerantAlluxioMasterProcess.java
> +      return false;
Need to stop already started masters before returning `false`.

2021-10-29 23:30 UTC, ggezer approved these changes

2021-11-01 19:30 UTC, jenoudet commented
Failed test: 
Java 11 & Java 8:
```
S3ClientRestApiTest.listAllMyBuckets
```

Java 11:
```
FileSystemMasterRestartIntegrationTest.updateAccessTimeAsyncFlushAfterDelete
BlockMasterRegisterStreamIntegrationTest.reregisterWithDelete
BlockMasterIntegrityIntegrationTest.deleteOrphanedBlocks
```
Java 8:
```
ConfigCheckerIntegrationTest.multiNodes
RocksInodeStoreTest
```

2021-11-01 20:01 UTC, ggezer commented
alluxio-bot, merge this please

2021-11-01 20:01 UTC, merged

2021-11-01 21:55 UTC, Xenorith commented
alluxio-bot, cherry-pick this to branch-2.7 please