Display unescape the ufs URI
Alluxio/alluxio pull request #14526
Opened 2021-11-16 08:28 UTC by ljl1988com

### What changes are proposed in this pull request?

Display unescape the ufs URI.

### Why are the changes needed?

Display unescape the ufs URI

### Does this PR introduce any user facing changes?

original:
![1637051193(1)](https://user-images.githubusercontent.com/3060835/141948394-a08edecd-a7fc-48ad-b932-875dbc5fc0c3.png)
now:
![1637051263(1)](https://user-images.githubusercontent.com/3060835/141948585-4d747f2f-b350-4d8a-82af-4463a376c24e.png)

2021-11-17 01:05 UTC, yuzhu requested changes
we should unescape on the browser side? i think http requires some characters to be escaped? @tieujason330 what do you think>?

2021-11-17 01:37 UTC, tieujason330 commented
@yuzhu since this is part of the response's body, i don't think it needs to be escaped. i think that'll get handled via json serialization.

2021-11-17 03:48 UTC, ljl1988com commented
@tieujason330 @yuzhu I find some codes as follows.

https://github.com/Alluxio/alluxio/blob/c642abc475878811c9e0dcbd28c842edd2639d5c/core/server/master/src/main/java/alluxio/master/meta/AlluxioMasterRestServiceHandler.java#L1062-L1070

If that'll get handled via json serialization. I think we still set serialization method of those properties. It's too complex.

2021-11-22 08:10 UTC, maobaolong approved these changes
Nice catch, LGTM, Thanks for this improvement.

2021-11-24 19:34 UTC, yuzhu approved these changes

2021-11-24 19:34 UTC, yuzhu commented
alluxio-bot, merge this please

2021-11-24 19:34 UTC, merged

2022-01-30 02:35 UTC, jiacheliu3 commented
alluxio-bot, cherry-pick this to branch-2.7 please