Add local cache used pages size metric
Alluxio/alluxio pull request #14585
Opened 2021-11-26 09:29 UTC by bzheng888

### What changes are proposed in this pull request?
Add local cache pages used metric 

### Why are the changes needed?
Sometimes we not only need space used information, but also the pages size information. The pages size give us meta information for future analyze.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

2021-11-26 11:59 UTC, maobaolong requested changes
Thanks for this metrics export, Left one comment inline.

2021-11-26 11:59 UTC, maobaolong commented on core/common/src/main/java/alluxio/metrics/MetricKey.java
> +          .setDescription("Amount of pages used by the client cache.")
As the description you gave, do you think the metric name `CLIENT_CACHE_PAGE_COUNT` can make sense more?

2021-11-26 13:04 UTC, maobaolong approved these changes
LGTM

2022-01-17 01:28 UTC, maobaolong commented
@beinan Would you please take another look?

2022-02-10 03:17 UTC, maobaolong commented
@beinan ping

2022-02-25 03:19 UTC, jiacheliu3 commented
/ping @beinan

2022-02-26 05:43 UTC, beinan commented on core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
> +          MetricsSystem.getMetricName(MetricKey.CLIENT_CACHE_PAGE_COUNT.getName()),
I think there has been a metrics key called client_cache_pages.    https://github.com/Alluxio/alluxio/blob/a10823a9523e200f1665228cd4eb3ea7659a0d15/core/common/src/main/java/alluxio/metrics/MetricKey.java#L1488

2022-02-26 05:43 UTC, beinan commented on core/client/fs/src/main/java/alluxio/client/file/cache/LocalCacheManager.java
> +          MetricsSystem.getMetricName(MetricKey.CLIENT_CACHE_PAGE_COUNT.getName()),
If you just wanna count the total number of the pages in our local cache, why not just use this metrics?

https://github.com/Alluxio/alluxio/blob/f2825833fbf5d473fe7265aae749e8b3d52df143/core/client/fs/src/main/java/alluxio/client/file/cache/DefaultMetaStore.java#L146

https://github.com/Alluxio/alluxio/blob/f2825833fbf5d473fe7265aae749e8b3d52df143/core/client/fs/src/main/java/alluxio/client/file/cache/DefaultMetaStore.java#L71

2022-03-04 03:31 UTC, maobaolong commented
Hi @beinan , we have some bad experience for the counter which counted by increase and decrease, it maybe wrong when we encounter exception, how about use `mPageMap.size()` instead of the `mPages` and `Metrics.PAGES`

2022-03-09 07:56 UTC, beinan commented
> Hi @beinan , we have some bad experience for the counter which counted by increase and decrease, it maybe wrong when we encounter exception, how about use `mPageMap.size()` instead of the `mPages` and `Metrics.PAGES`

Good call, create https://github.com/Alluxio/alluxio/pull/15121 to use the actual size of the map instead of the mPages

2022-03-09 07:59 UTC, beinan commented
hello @bzheng888 & @maobaolong , since the metrics of num of pages has been there already, can I shutdown this PR?

2022-03-09 09:00 UTC, bzheng888 commented
@beinan LGTM! Thanks!

2022-03-10 04:17 UTC, closed without merging