Alluxio preferentially move block to a lower tier when freeing space
Alluxio/alluxio pull request #14603
Opened 2021-12-01 08:47 UTC by Jackson-Wang-7

pr-link: Alluxio/alluxio#14518

### What changes are proposed in this pull request?
We want to modify this implementation so that when the space needs to be freed, the block that needs to be evicted will moved to the lower tier first. If it fails, we remove the block.

### Why are the changes needed?
Currently alluxio will directly remove blocks when freeing space. When the available space in MEM is used up，the evictable block is removed directly. The next time the data is read, it is reload from the UFS. In some cases, it will impose additional performance overhead.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

2021-12-02 03:23 UTC, apc999 commented
Suggest to have a PropertyKey to turn on and off this feature.

2021-12-15 19:28 UTC, beinan requested changes
I think this feature would be great for multi-tier use cases.  I just put a few comments and clarification questions.  Also as @apc999 suggested, could you add a alluxio property to turn on/off this feature?   Many thanks for the contribution!

2021-12-15 19:28 UTC, beinan commented on core/server/worker/src/main/java/alluxio/worker/block/allocator/MaxFreeAllocator.java
> +  public synchronized StorageDirView allocateBlockWithView(long sessionId, long blockSize,
Could you help clarify why we need add `synchronized ` here?

2021-12-15 19:28 UTC, beinan commented on core/server/worker/src/main/java/alluxio/worker/block/allocator/RoundRobinAllocator.java
> +  public synchronized StorageDirView allocateBlockWithView(long sessionId, long blockSize,
Could you help clarify why we need add synchronized here?

2021-12-15 19:28 UTC, beinan commented on core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
> +    if (!allocationDir.toBlockStoreLocation().equals(tempBlockMeta.getBlockLocation())) {
what if the tempBlockMeta got updated by other threads?  looks like you're shifting these lines out from the resource lock.  any particular reason for you doing this?

2021-12-15 19:28 UTC, beinan commented on core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
> -      StorageDirView dirView = allocateSpace(sessionId, options);
why do you shift allocateSpace out of the protection of mMetadataWriteLock?

2021-12-15 19:28 UTC, beinan commented on core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
> +          int tirLevel = mStorageTierAssoc.getOrdinal(blockMeta.getBlockLocation().tierAlias());
s/tirLevel/tierLevel?

2021-12-15 19:28 UTC, beinan commented on core/server/worker/src/main/java/alluxio/worker/block/TieredBlockStore.java
> +            MoveBlockResult result = moveBlockInternal(sessionId, blockMeta.getBlockId(),
what will happen if there is no enough space in the next tier?

2023-10-30 08:22 UTC, closed without merging