Upgrade log4j to 2.15.0 to address CVE-2021-44228
Alluxio/alluxio pull request #14665
Opened 2021-12-11 06:34 UTC by yuzhu

### What changes are proposed in this pull request?

Upgrade log4j to 2.15.0

### Why are the changes needed?
Address security vulnerability

2021-12-11 13:55 UTC, jiacheliu3 requested changes
LGTM, let's see how it works out

2021-12-11 13:55 UTC, jiacheliu3 approved these changes
Oops clicked the wrong button, this is an approval

2021-12-11 17:30 UTC, yuzhu commented
alluxio-bot, merge this please

2021-12-11 17:30 UTC, merged

2021-12-12 02:39 UTC, jiacheliu3 commented
@yuzhu According to https://unit42.paloaltonetworks.com/apache-log4j-vulnerability-cve-2021-44228/
should the version be 2.15.0-rc2?

2021-12-12 02:54 UTC, yuzhu commented
@jiacheliu3 good catch, there is a new article every day.. could you submit another PR?

2021-12-12 09:08 UTC, jiacheliu3 commented
Tried to change the depdendency version to `2.15.0-rc2` and that cannot be found. Checked https://mvnrepository.com/artifact/org.apache.logging.log4j/log4j-api and it seems `2.15.0` is the current latest version, no `rc2`.

From here it seems the rc2 is actually the `2.15.0` now.
https://github.com/apache/logging-log4j2/pull/608#issuecomment-991247673

Also from https://github.com/apache/logging-log4j2/commits/rel/2.15.0 it seems the `2.15.0-rc2` was promoted to `2.15.0`, which seems to be a confirmation. We should be good.

2021-12-14 02:07 UTC, Xenorith commented
alluxio-bot, cherry-pick this to branch-2.7 please

2021-12-18 03:15 UTC, Xenorith commented
alluxio-bot, cherry-pick this to branch-2.6 please