fix the single cluster document
Alluxio/alluxio pull request #14863
Opened 2022-01-18 06:54 UTC by xwzbupt

### What changes are proposed in this pull request?

add a statement describing that user must use sudo command without inputting password.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If not, the other nodes will waiting for inputting password but nobody will do it.

### Does this PR introduce any user facing changes?

   no

2022-01-18 06:55 UTC, xwzbupt commented
alluxio-bot, check it please.

2022-01-18 09:39 UTC, dbw9580 requested changes

2022-01-18 09:39 UTC, dbw9580 commented on docs/en/deploy/Running-Alluxio-On-a-Cluster.md
> +* Enable sudo command can be used without inputting password.
```suggestion
* Ensure that the user Alluxio will be running as can execute `sudo` without inputting a password.
```

Also can you please add a link to the section from the other doc where there are instructions on how to set `NOPASSWD` config for `sudo`?

2022-01-18 09:41 UTC, dbw9580 commented
Please prefix the title with `[DOCFIX]`. This skips all CI tests.

2022-01-18 10:00 UTC, xwzbupt commented
alluxio-bot, check it please.

2022-02-07 22:07 UTC, apc999 approved these changes

2022-02-07 22:14 UTC, apc999 commented
alluxio-bot, merge this please

2022-02-07 22:14 UTC, merged