Upgrade Ratis version to 2.2.0
Alluxio/alluxio pull request #14869
Opened 2022-01-18 19:08 UTC by jenoudet

From [this code comparison](https://github.com/apache/ratis/compare/ratis-2.0.0...ratis-2.2.0) it appears that Ratis 2.2.0 brings some fixes to the snapshotting logic. This draft PR serves to see if a version bump would break significant portions of the code.

2022-01-21 04:46 UTC, maobaolong requested changes
https://github.com/Alluxio/alluxio/pull/14872 Reference to this PR, it would be nice to pushdown the ratis dependencies into allxuio-core-server-common module

2022-01-23 15:29 UTC, maobaolong commented
@jenoudet Thanks for approved #14872 , now it has been merged, so would you like to solve the conflicts, besides, it lgtm.

2022-02-10 23:56 UTC, maobaolong commented
@jenoudet This PR looks nice, is there any update?

2022-02-11 01:54 UTC, jenoudet commented
> @jenoudet This PR looks nice, is there any update?

@maobaolong It is paused for now.

2022-04-01 20:10 UTC, closed without merging