Add cancel handling for distributedMV
Alluxio/alluxio pull request #14906
Opened 2022-01-25 00:43 UTC by jja725

### What changes are proposed in this pull request?

Add cancel handling for distributedMV. There's still the situation that we fail at the final step for renaming/deleting the destination file when overwrite files but we hardly can do anything about it. So when the user retry he would see temporary files.

### Why are the changes needed?

make distributedMV more reliable.

### Does this PR introduce any user facing changes?
na

2022-01-25 00:50 UTC, jja725 commented on job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
> +        if (fileSystem.exists(tmpUri) && !fileSystem.exists(destinationURI)) {
may need an extra eye on this condition @yuzhu

2022-01-25 01:07 UTC, yuzhu requested changes
could you add some highlevel comments on what this PR does?

2022-01-25 01:07 UTC, yuzhu commented on job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
> +      // this handles the situation that we get exception after we rename destination file and
I think you mean before rename?

2022-01-25 01:07 UTC, yuzhu commented on job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
> +            FileOutStream out = fileSystem.createFile(destinationURI, createOptions)) {
shouldn't we copy to tmpPath?

2022-01-25 23:24 UTC, jja725 commented on job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
> +          fileSystem.delete(tmpUri);
@yuzhu I update PR description so hopefully it makes sense now. And do you have better idea about how we can better handle file deletion/rename here?

2022-01-25 23:50 UTC, jja725 commented on job/server/src/main/java/alluxio/job/plan/migrate/MigrateDefinition.java
> +          fileSystem.delete(tmpUri);
And want to decide the correct process before I update the unit test.

2022-03-16 21:35 UTC, yuzhu commented
@jja725 can you fix the tests and use the assumption that remove and rename fails much less frequently than copy to implement this?

2022-03-25 00:45 UTC, yuzhu commented
can you include the tmp files the user expect to see in the PR description in the very rare cases? otherwise LGTM

2022-03-25 01:35 UTC, jja725 commented
> can you include the tmp files the user expect to see in the PR description in the very rare cases? otherwise LGTM

done

2022-03-26 02:28 UTC, yuzhu approved these changes

2022-03-26 02:29 UTC, yuzhu commented
alluxio-bot, merge this please

2022-03-26 02:29 UTC, merged