Add a metric to show the count of blocks to remove
Alluxio/alluxio pull request #15023
Opened 2022-02-18 02:18 UTC by codings-dan

### What changes are proposed in this pull request?

Add a metric to obtain the number of data blocks that have not been cleaned up temporarily.

### Why are the changes needed?

When the free command is executed, since the behavior of free to clear data blocks is asynchronous, even if free returns successfully, there are still data blocks that have not been cleared temporarily. If the load operation is executed again at this time, it will be found that the load execution speed is very fast, which is inaccurate. By increasing this metric, we can monitor the completion progress of the free command to a certain extent. Since the collection of this metric may affect performance, I set a switch to turn it on only when needed.

### Does this PR introduce any user facing changes?
No

2022-02-18 06:57 UTC, codings-dan commented
It seems that the ci test error has noting to do whith this code change

```
Error: 9.523 [ERROR] Errors: 
Error: 9.524 [ERROR] alluxio.client.cli.job.DistributedCommandsCancelStatsTest.testAsyncPersistCancelStats
Error: 9.524 [ERROR]   Run 1: DistributedCommandsCancelStatsTest.testAsyncPersistCancelStats:156 » Timeout T...
Error: 9.524 [ERROR]   Run 2: DistributedCommandsCancelStatsTest.testAsyncPersistCancelStats:156 » Timeout T...
02:58:49.524 [INFO] 
Warning: 524 [WARNING] Flakes: 
Warning: 524 [WARNING] alluxio.client.cli.JournalToolTest.dumpSimpleEmbeddedJournal
Error: 9.524 [ERROR]   Run 1: JournalToolTest.dumpSimpleEmbeddedJournal » Runtime java.lang.RuntimeException...
02:58:49.525 [INFO]   Run 2: PASS
02:58:49.525 [INFO] 
02:58:49.525 [INFO] 
Error: 9.525 [ERROR] Tests run: 71, Failures: 0, Errors: 1, Skipped: 0, Flakes: 1
```

2022-02-22 07:57 UTC, codings-dan commented
@ggezer Can you help review the code? Thanks!

2022-02-23 08:39 UTC, jiacheliu3 requested changes
Added a batch of comments. PTAL, thanks.

2022-02-23 08:39 UTC, jiacheliu3 commented on core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
> +        PropertyKey.MASTER_COUNT_TO_REMOVE_BLOCKS_ENABLE)) {
Adding this metric makes sense to me. And I don't think you need to use a configuration to turn it on/off. If we control all metrics this way the configuration will be too much.

The performance is a concern, I get it. You can use `MetricsSysmtem.registerCachedGaugeIfAbsent()`. If the cached gauge update interval is not what you want, you should change the method to set the cache time.

2022-02-23 08:39 UTC, jiacheliu3 commented on core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
> +    return mWorkers.stream().map(MasterWorkerInfo::getToRemoveBlockCount).reduce(0, Integer::sum);
Proper locking is required. You can follow the patter in `getCapacityBytes()`. Check the `MasterWorkerInfo` java doc too.

2022-02-23 08:39 UTC, jiacheliu3 commented on core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
> +    return mWorkers.stream().map(MasterWorkerInfo::getToRemoveBlockCount).reduce(0, Integer::sum);
Locking should not hurt your performance as long as you use the cached gauge.

2022-02-23 08:39 UTC, jiacheliu3 commented on core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
> -  @VisibleForTesting
?

2022-02-23 08:58 UTC, jiacheliu3 commented on core/server/master/src/main/java/alluxio/master/block/meta/MasterWorkerInfo.java
> -  @VisibleForTesting
hmm seems i forgot to mention this method needs locking too, will add to the comment

2022-03-04 02:52 UTC, jiacheliu3 approved these changes
LGTM except one minor comment. Thanks for the improvement!

2022-03-04 02:52 UTC, jiacheliu3 commented on core/common/src/main/java/alluxio/metrics/MetricKey.java
> +          .setDescription("Count of blocks to remove")
```suggestion
          .setDescription("Count of block replicas to be removed from the workers. If 1 block is to be removed from 2 workers, 2 will be counted here.")
```

2022-03-04 05:19 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2022-03-04 05:20 UTC, merged