fix volumeMounts format in helm chart
Alluxio/alluxio pull request #15029
Opened 2022-02-21 04:43 UTC by wuminorb

### What changes are proposed in this pull request?
fix volumeMounts format in helm chart

### Why are the changes needed?
fix https://github.com/Alluxio/alluxio/issues/14682

### Does this PR introduce any user facing changes?
Enable metrics in helm chart can working

2022-02-21 04:53 UTC, wuminorb commented
alluxio-bot, check this please

2022-02-23 02:32 UTC, jiacheliu3 requested changes
The change looks good to me. Could you also bump up the version in https://github.com/Alluxio/alluxio/blob/master/integration/kubernetes/helm-chart/alluxio/CHANGELOG.md and https://github.com/Alluxio/alluxio/blob/master/integration/kubernetes/helm-chart/alluxio/Chart.yaml

Thanks for the improvements!

2022-02-23 18:26 UTC, ZhuTopher requested changes
+1 with Jiacheng's request to bump the version in `Chart.yaml` and update the `CHANGELOG.md`. Make sure you pull the latest version before doing so as well!

2022-02-24 02:55 UTC, jiacheliu3 approved these changes
LGTM with a minor comment. Just commit that and it's good for merging.

Thanks for the fix!

2022-02-24 02:55 UTC, jiacheliu3 commented on integration/kubernetes/helm-chart/alluxio/CHANGELOG.md
> +- Fix volumeMounts format in master statefulset
```suggestion
- Fix volumeMounts indentations in master statefulset
```

2022-02-28 03:53 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2022-02-28 03:54 UTC, merged