Add GrpcExecutors metrcis
Alluxio/alluxio pull request #15101
Opened 2022-03-04 03:56 UTC by xichen01

### What changes are proposed in this pull request?
Added some GrpcExecutors ThreadPool metrics

### Why are the changes needed?
Add a way to monitor worker load info. Include worker read/write/cache thread pool.

### Does this PR introduce any user facing changes?

no

2022-03-17 04:24 UTC, maobaolong reviewed
@xichen01 Thanks for contributing these useful metrics, it really make it easy to know the worker status through these metrics.

Please take a double check is there any expensive operation of each metric？

2022-03-21 10:42 UTC, xichen01 commented
The time complexity of metrics operation is O(1), so it is a cheap operation

2022-03-25 07:45 UTC, maobaolong approved these changes
Thanks for your contribution, these metrics look worth to have

2022-03-27 14:39 UTC, jiacheliu3 requested changes
Mostly LGTM. My comments are mostly about formating. Thanks for the improvements!

My high level comment is, I can see you are trying to add metrics on all attributes of thread pools. Did you monitor the values of these metrics in your test environment? I think maybe some fields can be merged so that every metric means something, instead of we have all sorts of metrics but don't know which to look at.

In terms of performance, at this moment I'm not worried about monitoring many metrics at the worker because it's rarely an issue for the worker to serve metrics. But in general, I believe a good practice is to cache gauges as much as possible. If you cache some(if not all) of your gauges by a few seconds, that will be great.

2022-03-27 14:39 UTC, jiacheliu3 commented on core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
> +        CACHE_MANAGER_THREAD_POOL_EXECUTOR::getPoolSize);
What's the difference between these two?

2022-03-27 14:39 UTC, jiacheliu3 commented on core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
> +    MetricsSystem.registerGaugeIfAbsent(MetricsSystem.getMetricName(
I think this is a static value that does not change. So there's no need to monitor it.

2022-03-27 14:39 UTC, jiacheliu3 commented on core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
> +            MetricKey.WORKER_BLOCK_READER_THREAD_QUEUE_WAITING_TASK_COUNT.getName()),
same indentation as other lines

2022-03-27 14:39 UTC, jiacheliu3 commented on core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
> +        CACHE_MANAGER_THREAD_POOL_EXECUTOR::getCompletedTaskCount);
nit: Could you try to make the indentation and line wrapping identical for all these lines?

2022-03-27 14:39 UTC, jiacheliu3 commented on core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
> -          ThreadFactoryUtils.build("CacheManagerExecutor-%d", true)));
nit: restore indentation if there's no change in these lines

2022-03-27 14:39 UTC, jiacheliu3 commented on core/common/src/main/java/alluxio/metrics/MetricKey.java
> +              + "in the reader thread thread pool")
```suggestion
          .setDescription("The current number of tasks waiting in the work queue "
              + "in the reader thread thread pool, bounded by " + PropertyKey.WORKER_NETWORK_ASYNC_CACHE_MANAGER_QUEUE_MAX)
```

2022-03-27 14:39 UTC, jiacheliu3 commented on core/common/src/main/java/alluxio/metrics/MetricKey.java
> +              + "in the block write thread pool")
```suggestion
              + "in the block writer thread pool")
```
In this is bounded by a property key, pls include in the description as above

2022-03-27 14:39 UTC, jiacheliu3 commented on core/common/src/main/java/alluxio/metrics/MetricKey.java
> +          .setDescription("The current number of tasks waiting in the work queue "
Is this bounded by a property key? If so pls include that in the description.

2022-03-27 14:39 UTC, jiacheliu3 commented on core/common/src/main/java/alluxio/metrics/MetricKey.java
> +  public static final MetricKey WORKER_CACHE_MANAGER_THREAD_MAX_COUNT =
If this is actually bounded by a property key, i don't think we need to look at this?

2022-04-21 06:30 UTC, jiacheliu3 requested changes
Added a few minor comments, mostly LGTM, thanks!

2022-04-21 06:30 UTC, jiacheliu3 commented on core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
> +    MetricsSystem.registerGaugeIfAbsent(MetricsSystem.getMetricName(
see above

2022-04-21 06:30 UTC, jiacheliu3 commented on core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
> +        MetricKey.WORKER_CACHE_MANAGER_THREAD_QUEUE_WAITING_TASK_COUNT.getName()),
For these metrics, pls use cached gauges and at least cache for a few seconds.

2022-04-21 06:30 UTC, jiacheliu3 commented on core/common/src/main/java/alluxio/metrics/MetricKey.java
> +      new Builder("Worker.CacheMangerCompleteTaskCount")
typo

2022-04-25 02:54 UTC, jiacheliu3 approved these changes
LGTM with a minor comment, thanks for the improvement!

2022-04-25 02:54 UTC, jiacheliu3 commented on core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
> +    MetricsSystem.registerCachedGaugeIfAbsent(MetricsSystem.getMetricName(
nit: add a comment why this is different, like:
```
// This value does not change after the process starts
```

2022-04-25 03:12 UTC, dbw9580 approved these changes
LGTM with a minor comment

2022-04-25 03:12 UTC, dbw9580 commented on core/server/worker/src/main/java/alluxio/worker/grpc/GrpcExecutors.java
> +  public static final ThreadPoolExecutor CACHE_MANAGER_THREAD_POOL_EXECUTOR =
This one can be private. See other thread pool executor fields in this class.

2022-04-29 03:06 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2022-04-29 03:06 UTC, merged