Add delete lost worker feature
Alluxio/alluxio pull request #15155
Opened 2022-03-17 03:52 UTC by xichen01

### What changes are proposed in this pull request?
Add a `fsadmin deleteWorker [workerName]`command to delete Worker
Add a timeout PropertyKey, If the lost worker has no heartbeat for more than this time it will be completely deleted from the master. By default this time is Long.MAX_VALUE.

### Why are the changes needed?
https://github.com/Alluxio/alluxio/issues/9457

### Does this PR introduce any user-facing changes?

Please list the user-facing changes introduced by your change, including
add PropertyKey `MASTER_WORKER_DELETE_TIMEOUT_MS`
add a `fsadmin deleteWorker [workerName]`command

2022-03-17 04:02 UTC, xichen01 commented
@apc999 
A rough code, does it meet the expected design?
//TODO: unit tests, detail

2022-03-21 02:15 UTC, maobaolong requested changes
Please correct the style before a review request, thank you.

2022-03-21 02:15 UTC, maobaolong commented on shell/src/main/java/alluxio/cli/fsadmin/command/DeleteWorker.java
> +  @Override
All overloaded methods should be placed next to each other. Placing non-overloaded methods in between overloaded methods with the same type is a violation

2022-03-21 02:15 UTC, maobaolong commented on shell/src/main/java/alluxio/cli/fsadmin/command/DeleteWorker.java
> +   * todo.
TODO(xichen01):

2022-03-21 02:15 UTC, maobaolong commented on shell/src/main/java/alluxio/cli/fsadmin/command/DeleteWorker.java
> + * todo.
TODO(xichen01): xx

2022-03-21 10:40 UTC, xichen01 commented
This is an unfinished rough code. I want to confirm whether the design meets the expectations (https://github.com/Alluxio/alluxio/issues/9457). If it does, I will continue to complete the code.

2022-04-26 09:48 UTC, maobaolong commented
@xichen01 It looks your some of integration test are failed, please care about it, thanks!

2022-05-16 01:17 UTC, maobaolong commented on tests/src/test/java/alluxio/client/hadoop/FileSystemRenameIntegrationTest.java
> +//    o.sync();
Please revert this change

2022-05-16 01:20 UTC, maobaolong commented on shell/src/main/java/alluxio/cli/fsadmin/command/DeleteWorker.java
> +    return "deleteWorker [Worker Name]";
Worker name -> WorkerAddresses

2022-05-16 01:21 UTC, maobaolong commented on shell/src/main/java/alluxio/cli/fsadmin/command/DeleteWorker.java
> +    return "Delete a worker from the cluster. The data in the worker will not be deleted";
This command can delete more than one worker

2022-05-16 01:22 UTC, maobaolong commented on shell/src/main/java/alluxio/cli/fsadmin/command/DeleteWorker.java
> +public class DeleteWorker extends AbstractFsAdminCommand {
DeleteWorkerCommand

2022-05-30 00:40 UTC, maobaolong reviewed
Left some more comments, @xichen01 please take a look.

2022-05-30 00:40 UTC, maobaolong commented on core/client/fs/src/main/java/alluxio/client/block/BlockMasterClient.java
> +  void deleteWorker(final Long workerId) throws IOException;
Is this necessary to use `Long` rather than basic type `long`?

2022-05-30 00:40 UTC, maobaolong commented on core/client/fs/src/main/java/alluxio/client/block/RetryHandlingBlockMasterClient.java
> +   * @param workerId the worker ids
If it stand for only one id, please use id here

2022-05-30 00:40 UTC, maobaolong commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +              + "it will be completely deleted from the master. In default,"
By default

2022-05-30 00:40 UTC, maobaolong commented on shell/src/main/java/alluxio/cli/fsadmin/command/DeleteWorkerCommand.java
> +    return "deleteWorker [WorkerAddresses]";
You can print something to show separated by comma.

2022-06-13 12:36 UTC, maobaolong approved these changes
It LGTM. Thanks for your contribution on this useful PR!

2022-09-03 15:25 UTC, xichen01 commented
@jiacheliu3 
Commands that make it easier for SREs to manage clusters. For example, if the SRE clearly knows that a worker is to go offline, it can first stop the worker (maybe with other operations) and then delete the worker by command. 
Deleting a worker can be one of the steps to take a worker offline.

2022-10-31 07:07 UTC, jiacheliu3 requested changes
Added some high level comments, thanks a lot for the improvements!

2022-10-31 07:07 UTC, jiacheliu3 commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +              + " the lost worker will never be deleted.")
```suggestion
          .setDescription("If a worker has no heartbeat with the master for more than this timeout, "
              + "the master will totally forget this worker.")
```

2022-10-31 07:07 UTC, jiacheliu3 commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +          .setDefaultValue(Long.MAX_VALUE)
i think the default can be something like `3 * MASTER_WORKER_TIMEOUT_MS`. @maobaolong By default do you prefer a lost worker to be kept in the `lost workers` forever, or removed from that list after some time?

2022-10-31 07:07 UTC, jiacheliu3 commented on core/server/master/src/test/java/alluxio/master/block/BlockMasterTest.java
> +    List<WorkerInfo> info = mBlockMaster.getLostWorkersInfoList();
also check the worker is not in `BlockMaster.getWorkersInfoList()`

2022-10-31 07:07 UTC, jiacheliu3 commented on tests/src/test/java/alluxio/client/fs/BlockMasterDeleteLostWorkerIntegrationTest.java
> +                    Executors.newFixedThreadPool(10)));
nit: 4 more spaces from the previous line

2022-11-07 08:20 UTC, jiacheliu3 approved these changes
Thanks for the improvements! Only some minor comments before I merge this :)

2022-11-07 08:20 UTC, jiacheliu3 commented on core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
> +  private void deleteWorker(MasterWorkerInfo worker) {
```suggestion
  private void deleteWorkerMetadata(MasterWorkerInfo worker) {
```

2022-11-07 08:20 UTC, jiacheliu3 commented on core/server/master/src/main/java/alluxio/master/block/DefaultBlockMaster.java
> +                    worker.getWorkerAddress(), lastUpdate);
I'm not too sure, but the best indentation should look like this? Pls double check :)
```suggestion
            LOG.error("The worker {}({}) timed out after {}ms without a heartbeat! "
                + "Master will forget about this worker.", worker.getId(),
                worker.getWorkerAddress(), lastUpdate);
```

2022-11-10 03:04 UTC, jiacheliu3 commented
@xichen01 seems many tests are broken, could you take a look?

2022-11-16 09:38 UTC, jiacheliu3 approved these changes
LGTM, thanks a lot for the contribution!

2022-11-16 09:40 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2022-11-16 09:40 UTC, merged