Add missing override annotation
Alluxio/alluxio pull request #15188
Opened 2022-03-22 07:32 UTC by xichen01

### What changes are proposed in this pull request?

### Why are the changes needed?
- Add missing @override annotation
- Removed duplicate comments that already existed in the base class after adding @override annotation

### Does this PR introduce any user facing changes?
Please list the user-facing changes introduced by your change, including
No

2022-03-23 06:55 UTC, maobaolong approved these changes
It LGTM, thanks for clear the code.

2022-04-01 23:51 UTC, maobaolong commented
@jiacheliu3 @HelloHorizon Would you like to take another look?

2022-05-05 10:10 UTC, dbw9580 requested changes
A few minor issues. Thanks!

2022-05-05 10:10 UTC, dbw9580 commented on core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
>      if (changedFiles == null) {
Please preserve the comment on the behavior when `changedFiles` is `null`. Also please add a `@Nullable` annotation on this parameter.

2022-05-05 10:10 UTC, dbw9580 commented on stress/common/src/main/java/alluxio/stress/fuse/FuseIOTaskResult.java
> +  @Override
Remove these javadoc.

2022-05-05 10:15 UTC, dbw9580 commented on core/server/master/src/main/java/alluxio/master/file/DefaultFileSystemMaster.java
>      if (changedFiles == null) {
Actually this is more complicated: when `changedFiles` is not `null` but an empty collection, this method does nothing. It starts a full sync when `changedFiles` is `null`. Should update the comments to document this behavior.

2022-05-06 05:39 UTC, dbw9580 approved these changes
LGTM, thanks!

2022-05-13 02:23 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2022-05-13 02:23 UTC, merged