Improve fuse mount based on user configuration
Alluxio/alluxio pull request #15263
Opened 2022-04-05 22:56 UTC by LuQQiu

### What changes are proposed in this pull request?

User input > user alluxio config > alluxio default config when setting the Fuse mount options

### Why are the changes needed?

To provide a central way of configuring worker fuse and standalone fuse.

### Does this PR introduce any user facing changes?

Yeah, change how users launch Kubernetes scripts

2022-04-05 22:59 UTC, LuQQiu commented
FYI @liugs0213 @maobaolong @Nizifan this PR may break the kubernetes backward compatibility.
Instead of using environment variable to set the alluxio path and fuse mount point, we took the following configuration
```
alluxio.fuse.mount.point
alluxio.fuse.mount.alluxio.path
alluxio.fuse.mount.options
```
This is for code cleanness and for better maintainability

2022-04-05 23:09 UTC, LuQQiu commented on integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
> -            value: {{ .Values.fuse.mountPath }}
@liugs0213 @maobaolong @Nizifan those environment variables will not set the alluxioPath, mountPoint, requires alluxio.fuse.mount.point and alluxio.fuse.mount.alluxio.path

2022-04-05 23:09 UTC, LuQQiu commented on integration/fuse/bin/alluxio-fuse
> -When no argument is given, list the current mount point
@liugs0213 @maobaolong @Nizifan
when no argument is given, will not list the current mount point, but use the default `alluxio.fuse.mount.point` and `alluxio.fuse.mount.alluxio.path` to mount.

2022-04-05 23:11 UTC, LuQQiu commented on integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
> +                command: ["/opt/alluxio/integration/fuse/bin/alluxio-fuse", "unmount", "-f", "{{ .Values.fuse.mountPath }}"]
As a temporary fix, better to be soft umount first and then hard umount

2022-04-06 01:58 UTC, ssz1997 requested changes
Well something is broken

2022-04-06 02:05 UTC, LuQQiu commented on integration/fuse/bin/alluxio-fuse
> +    mount_point=$(${BIN}/alluxio getConf alluxio.fuse.mount.point)
getConf will process the environment variable and default alluxio configuration, why this command cannot get the mount point that user set?
if alluxio.fuse.mount.point is configured in ALLUXIO_FUSE_JAVA_OPTS, can we run this command to get the value?

2022-04-06 18:15 UTC, ssz1997 approved these changes
LGTM. Thanks for the improvement, mount and code

2022-04-06 20:00 UTC, LuQQiu commented
Error: 5.298 [ERROR] Errors: 
Error: 5.298 [ERROR] alluxio.client.cli.job.DistributedCommandsStatsTest.testAsyncPersistCancelStats
Error: 5.301 [ERROR]   Run 1: DistributedCommandsStatsTest.testAsyncPersistCancelStats:221 » Timeout Timed o...
Error: 5.303 [ERROR]   Run 2: DistributedCommandsStatsTest.testAsyncPersistCancelStats:221 » Timeout Timed o...

2022-04-06 20:27 UTC, LuQQiu commented
alluxio-bot, merge this please

2022-04-06 20:27 UTC, merged

2022-04-06 22:56 UTC, LuQQiu commented on integration/kubernetes/helm-chart/alluxio/templates/fuse/daemonset.yaml
> -            value: {{ .Values.fuse.mountPath }}
Changes will be reverted, those parameters will still be here to support multiple Fuse yaml mounts/files with one alluxio-configmap.yaml