Revert getLong API
Alluxio/alluxio pull request #15444
Opened 2022-04-22 13:46 UTC by xichen01

### What changes are proposed in this pull request?

Revert getLong API

### Why are the changes needed?
There are some offline discussions, it is believed that some `propertyKeys` may require a value of type Long, so the revert getLong API is required

### Does this PR introduce any user facing changes?
No

2022-04-25 06:19 UTC, maobaolong requested changes
Left some comment, Thanks for bring the getLong back @xichen01

2022-04-25 06:19 UTC, maobaolong commented on core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
> +  {
This should in the previous line.

2022-04-25 06:19 UTC, maobaolong commented on core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
> +    checkArgument(key.getType() == PropertyKey.PropertyType.INTEGER);
It should be `PropertyKey.PropertyType.INTEGER` or `PropertyKey.PropertyType.LONG` ?

2022-04-25 06:19 UTC, maobaolong commented on core/common/src/main/java/alluxio/conf/InstancedConfiguration.java
> +    return (int) get(key);
So we should cast it to long?

2022-04-25 17:42 UTC, rongrong commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +      longBuilder(Name.MASTER_JOURNAL_CHECKPOINT_PERIOD_ENTRIES)
I don't think these property keys need to be long. Integer can already go up to 2billion+, which is probably larger than what our system can handle already. If we really need a LONG type property key, let's add that. But these keys should not be of type LONG.

2022-04-25 22:25 UTC, maobaolong approved these changes
It LGTM for this PR, revert the getLong API can make users can use long propertykey. @xichen01 Would you please have a discussion with @rongrong and reach a consensus.

2022-04-28 10:31 UTC, xichen01 commented
failed UT
```
Error: 3.508 [ERROR] Tests run: 8, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 4.026 s <<< FAILURE! - in alluxio.util.JvmPauseMonitorTest
Error: 3.513 [ERROR] alluxio.util.JvmPauseMonitorTest.testMockedInfoPause  Time elapsed: 1.641 s  <<< FAILURE!
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at alluxio.util.JvmPauseMonitorTest.testMockedInfoPause(JvmPauseMonitorTest.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:258)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:364)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:237)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:158)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
```

2022-04-28 10:33 UTC, xichen01 commented
@rongrong PTAL

2022-09-03 15:54 UTC, xichen01 commented
@rongrong PTAL. Any comments?

2022-09-07 01:23 UTC, maobaolong commented
@rongrong I want to add a propertykey to limit the capacity of inode, it should be defined as long.

2022-09-07 01:25 UTC, maobaolong commented
@xichen01 Would you like to resolve the ci check issues?

2022-09-16 02:59 UTC, maobaolong approved these changes
It LGTM, thanks for your contribution!

2022-09-16 06:08 UTC, elega approved these changes

2022-09-26 01:15 UTC, maobaolong commented
@elega @jiacheliu3 Could you help to merge this PR?

2022-09-26 01:50 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2022-09-26 01:50 UTC, merged