[DOCFIX] Improve UFS ozone doc
Alluxio/alluxio pull request #15462
Opened 2022-04-26 14:17 UTC by xichen01

### What changes are proposed in this pull request?
Improve UFS ozone doc, Added:
- the mount about HA Ozone mode 
- the mount of the specified Ozone version

### Why are the changes needed?

Improve UFS ozone doc

### Does this PR introduce any user facing changes?
NO

2022-04-27 02:05 UTC, maobaolong requested changes
Left couple of comments, please take a look, otherwise, it LGTM.

2022-04-27 05:39 UTC, xichen01 commented on docs/cn/ufs/Ozone.md
> +    <value>tdw</value>
done

2022-04-27 05:39 UTC, xichen01 commented on docs/en/ufs/Ozone.md
> +    <value>tdw</value>
done

2022-04-27 13:10 UTC, maobaolong approved these changes
LGTM. Thanks @xichen01

2022-04-27 13:11 UTC, maobaolong commented
@jiacheliu3 Would you like to have another look?

2022-05-06 06:28 UTC, dbw9580 requested changes

2022-05-06 06:28 UTC, dbw9580 commented on docs/cn/ufs/Ozone.md
> +底层存储的地址可以是`o3fs://<OZONE_BUCKET>.<OZONE_VOLUME>/alluxio/data`。
```suggestion
如果仅将`<OZONE_VOLUME>`的`<OZONE_BUCKET>`ozone桶内的`/alluxio/data`目录映射到Alluxio的根目录，
则可以设置为`o3fs://<OZONE_BUCKET>.<OZONE_VOLUME>/alluxio/data`。
```

2022-05-06 06:28 UTC, dbw9580 commented on docs/cn/ufs/Ozone.md
> +可能的 `ozone-site.xml` 文件，从该文件中可以知道，`<OM_SERVICE_IDS>` 为 `omservice1`。
```suggestion
例如以下`ozone-site.xml`配置文件中`<OM_SERVICE_IDS>` 为 `omservice1`。
```

2022-05-06 06:28 UTC, dbw9580 commented on docs/cn/ufs/Ozone.md
> +如果需要挂载指定版本的Ozone可以通过`alluxio.underfs.version=<OZONE_VERSION>`指定。
```suggestion
如果需要挂载指定版本的Ozone，可以在挂载时通过`alluxio.underfs.version=<OZONE_VERSION>`参数指定版本。
```

2022-05-06 06:28 UTC, dbw9580 commented on docs/en/ufs/Ozone.md
> +Possible `ozone-site.xml` file, as known from the file, `<OM_SERVICE_IDS>` is `omservice1`
```suggestion
`<OM_SERVICE_IDS>` can be found in `ozone-site.xml`.
In the following example `ozone-site.xml` file, `<OM_SERVICE_IDS>` is `omservice1`:
```

2022-05-06 06:28 UTC, dbw9580 commented on docs/en/ufs/Ozone.md
> +User can mount an Ozone cluster with a specified version as an under storage into Alluxio namespace.
```suggestion
Users can mount an Ozone cluster of a specific version as an under storage into Alluxio namespace.
```

2022-05-06 06:28 UTC, dbw9580 commented on docs/en/ufs/Ozone.md
> +If you need mount an HDFS cluster with a specified version, you can specify it through `alluxio.underfs.version=<OZONE_VERSION>`.
```suggestion
If you need to mount an Ozone cluster of a specific version, you can specify it through the command line option `alluxio.underfs.version=<OZONE_VERSION>`.
```

2022-05-06 17:24 UTC, xichen01 commented on docs/cn/ufs/Ozone.md
> +例如，如果要将整个存储桶挂载到Alluxio底层存储的地址可以是`o3fs://<OZONE_BUCKET>.<s_VOLUME>/`
done

2022-05-06 17:24 UTC, xichen01 commented on docs/cn/ufs/Ozone.md
> +底层存储的地址可以是`o3fs://<OZONE_BUCKET>.<OZONE_VOLUME>/alluxio/data`。
done

2022-05-06 17:25 UTC, xichen01 commented on docs/cn/ufs/Ozone.md
> +可能的 `ozone-site.xml` 文件，从该文件中可以知道，`<OM_SERVICE_IDS>` 为 `omservice1`。
done

2022-05-06 17:25 UTC, xichen01 commented on docs/cn/ufs/Ozone.md
> +如果需要挂载指定版本的Ozone可以通过`alluxio.underfs.version=<OZONE_VERSION>`指定。
done

2022-05-06 17:25 UTC, xichen01 commented on docs/en/ufs/Ozone.md
> +Possible `ozone-site.xml` file, as known from the file, `<OM_SERVICE_IDS>` is `omservice1`
done

2022-05-06 17:25 UTC, xichen01 commented on docs/en/ufs/Ozone.md
> +User can mount an Ozone cluster with a specified version as an under storage into Alluxio namespace.
done

2022-05-06 17:25 UTC, xichen01 commented on docs/en/ufs/Ozone.md
> +If you need mount an HDFS cluster with a specified version, you can specify it through `alluxio.underfs.version=<OZONE_VERSION>`.
done

2022-05-07 02:25 UTC, dbw9580 approved these changes
LGTM

2022-05-07 03:20 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2022-05-07 03:20 UTC, merged