Support command to get filePath through fileId
Alluxio/alluxio pull request #15511
Opened 2022-05-06 08:16 UTC by maobaolong

### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

2022-05-14 23:56 UTC, maobaolong commented on shell/src/main/java/alluxio/cli/fsadmin/command/GetFilePathCommand.java
> +      String path = mFsClient.getFilePath(fileId);
Yeah, it is a simple path, something like `/file`

2022-05-14 23:57 UTC, maobaolong commented
@dbw9580 I just update this PR under the discussion between us, PTAL.

2022-05-16 07:35 UTC, dbw9580 requested changes

2022-05-16 07:35 UTC, dbw9580 commented on core/transport/src/main/proto/grpc/file_system_master.proto
> +  optional FileInfo fileInfo = 2;
We already have `FileSystemMasterClient#getStatus` for the same thing. Should not duplicate RPCs that do the same thing.

2022-05-16 07:35 UTC, dbw9580 commented on shell/src/main/java/alluxio/cli/fsadmin/command/GetFilePathCommand.java
> +      FileInfo fileInfo = mFsClient.getFilePath(fileId);
We can achieve the same thing with two steps: 

1. get the file path from file id with `client.getFilePath`; 
2. get detailed file info by calling `client.getStatus` with the path acquired from step 1.

Step 2 is the same thing as `alluxio fs stat /file`. It should be optional and should hide behind a `--stat` flag, which suggests it does an extra step to fetch the file stats as reported by `fs stat`.

2022-05-16 07:42 UTC, dbw9580 commented on shell/src/main/java/alluxio/cli/fsadmin/command/GetFilePathCommand.java
> +      FileInfo fileInfo = mFsClient.getFilePath(fileId);
On second thought, I think we should totally make `alluxio fs stat` accept a file id, and add a new format option to output the file path.

2022-05-26 12:49 UTC, dbw9580 commented
@maobaolong this should be superseded by #15565, can we close this PR?

2022-06-28 01:15 UTC, maobaolong commented
@dbw9580 Thanks for remind me, close this PR

2022-06-28 01:15 UTC, closed without merging