Fix async-persist cancel test timeout
Alluxio/alluxio pull request #15536
Opened 2022-05-10 22:36 UTC by luzhang6

### What changes are proposed in this pull request?
Increase time for sleepingUFS and move async-persist destination to non-sleeping UFS

2022-05-18 21:46 UTC, jja725 commented
I don't think this would solve the problem...basically when you write you should not write to sleep ufs because you would get blocked at the very first step.

2022-05-18 21:47 UTC, jja725 requested changes

2022-05-18 21:47 UTC, jja725 commented on tests/src/test/java/alluxio/client/cli/job/DistributedCommandsStatsTest.java
> +  private static final int TEST_TIMEOUT = 60;
this doesn't resolve the problem

2022-06-08 22:03 UTC, jja725 approved these changes

2022-06-09 22:35 UTC, HelloHorizon commented
alluxio-bot, merge this please

2022-06-09 22:35 UTC, merged