AE-2465: 2GB File Size Limitation with S3 Rest API
Alluxio/alluxio pull request #15717
Opened 2022-06-14 09:13 UTC by Jackson-Wang-7

### What changes are proposed in this pull request?

This PR changes the variable 'toRead' from Integer to Lang.

### Why are the changes needed?

```
When we increase the size of a put to 2GB, we the get the following error that I see on the proxy side:
2022-05-17 20:55:00,782 WARN S3RestUtils - Unexpected error invoking REST endpoint: For input string: “2147483648”

/Users/t_bisson/Documents/scripts$aws --profile test-aiml-dp-dsc-admin --endpoint http://wiccan-lab.g.apple.com:39999/api/v1/s3/ s3api put-object --bucket=testbucket --key=2gfile_wiccan.txt --body=~/Documents/scripts/2g.img

An error occurred (InternalError) when calling the PutObject operation (reached max retries: 4): For input string: "2147483648"
```
our S3 REST API parses the Content-Length header as a signed Java Integer so it caps at ~2 GB.
If the file is larger than 2GB, some errors will occure.

2022-06-14 17:48 UTC, yuzhu commented
@Jackson-Wang-7 please add some test cases and also after this change what is the cap on file size? is it the limit of long now?

2022-06-14 23:25 UTC, ZhuTopher requested changes
Thanks, the changes look good to me. As David mentioned we'd like to add some unit tests to verify this behaviour.

You can find our existing test cases in [S3ClientRestApiTest.java](https://github.com/Alluxio/alluxio/blob/master/tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java), and an example PutObject test [here](https://github.com/Alluxio/alluxio/blob/master/tests/src/test/java/alluxio/client/rest/S3ClientRestApiTest.java#L704-L727). You should add test cases for the following:

- Put an object <= 5GB, verify that it returns the correct file size
- Put an object > 5 GB, it should fail and return an `EntityTooLarge` [S3 error code](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html)
  - This will require some validation code to be added to `S3RestServiceHandler` 

We recommend if you are using an IDE like IntelliJ to run tests there, but otherwise you can do it manually with Maven. Our docs give some examples of how to do so [here](https://docs.alluxio.io/os/user/stable/en/contributor/Contributor-Tools.html#unit-tests).

2022-06-15 10:42 UTC, Jackson-Wang-7 commented
> @Jackson-Wang-7 please add some test cases and also after this change what is the cap on file size? is it the limit of long now?

in S3 with a single PUT operation, we can upload a single object up to 5 GB in size. Using the multipart upload API, we can upload a single large object, up to 5 TB in size. the limit of long is much bigger.

### test cases 

I have tested 3 cases about this PR with HTTP request and aws cli(UFS: S3):

1, Put 3G file success, check the file size is correct and Download it

![image](https://user-images.githubusercontent.com/39869597/173806007-e100acad-0322-4c8f-8c4d-003db3f06787.png)

2, put 1G file success, check the file size is correct and Download it

![image](https://user-images.githubusercontent.com/39869597/173805486-7a1e3829-c443-41ed-945b-efc1291016cf.png)

3, Put 6G file failed, check the error code

![image](https://user-images.githubusercontent.com/39869597/173807631-a6988c70-f647-4125-9cdb-afffefb35e58.png)

![image](https://user-images.githubusercontent.com/39869597/173807671-2d337fa6-03b6-4ba2-8f59-d89d72eba7fb.png)

### unit cases

I tried to add some unit test cases about uploading a big file. but there are some questions: 

1, if we want to upload a real 3GB file in unit test. the internal cache of request HTTPURLConnection must be closed and Data only can be copied to the upload stream by buffer. Otherwise OOM will occur. In this case, it will takes a long long time to upload such a large file. (maybe my local machine is too poor)

2, if we only construct header "Content-Length" for testing, In the defalut scenario sun.net.http.allowRestrictedHeaders restrict us from configuring the header “Content-Length”. and we check there if data length is smaller than the content length. maybe this test doesn't make much sense.

maybe it's not suitable for testing in unit tests. Should we add the test cases into integration test?

2022-06-15 11:56 UTC, Jackson-Wang-7 commented
I created a new PR in [here](https://github.com/Alluxio/alluxio/pull/15726)
maybe we review here, and close this one

2022-06-15 16:14 UTC, ZhuTopher commented
Thanks, will continue review in https://github.com/Alluxio/alluxio/pull/15726

2022-06-15 16:14 UTC, closed without merging