Allow Docker image file permissions to be modified at runtime
Alluxio/alluxio pull request #15898
Opened 2022-07-16 11:28 UTC by JiamingMai

### What changes are proposed in this pull request?

Rrefactor the Dockerfile's entrypoint script so that we can set permissions on a provided env/argument instead.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,

Currently in the Alluxio Dockerfile the USER, UID and GID are all hard-coded. Thus only way to change the file permissions is to recompile a Docker image with new values for the arguments.

This creates a problem for users of the Helm chart who try to modify the user / UID used to run the Docker container in k8s. The corresponding file permissions do not get updated to the new UID.

I suggest we should consider refactoring the Dockerfile's entrypoint script so that we can set permissions on a provided env/argument instead.

### Does this PR introduce any user facing changes?

No, it doesn't.

2022-07-18 19:31 UTC, beinan requested changes
looks good to me except the alluxio version

2022-07-18 19:31 UTC, beinan commented on integration/docker/Dockerfile
> +ARG ALLUXIO_TARBALL=https://downloads.alluxio.io/downloads/files/2.8.0/alluxio-2.8.0-bin.tar.gz
I think we need to keep the version to be 2.9.0-SNAPSHOT, which would be got updated for every release

2022-07-18 19:31 UTC, beinan commented on integration/docker/Dockerfile-dev
> +ARG ALLUXIO_TARBALL=https://downloads.alluxio.io/downloads/files/2.8.0/alluxio-2.8.0-bin.tar.gz
keep 2.9.0-SNAPSHOT

2022-07-18 20:55 UTC, ssz1997 reviewed
Looks like the docker default user now is root. According to @ZhuTopher we can do something like `su <username>` in the entrypoint.sh?

2022-07-19 02:53 UTC, JiamingMai commented
I have changed the alluxio tarball version from 2.8.0 to 2.9.0-SNAPSHOT. The alpine's version is also changed back to 3.10.2. https://github.com/Alluxio/alluxio/pull/15898/commits/4441c096fc504a33cb6106b121fdae7a71970e0e

2022-07-19 03:58 UTC, beinan approved these changes
lgtm

2022-07-20 00:36 UTC, ssz1997 commented
@JiamingMai After I run `docker exec -it alluxio-master bash` and `whoami` inside the container, it returns user `root`. Is it possible to run as user Alluxio by default  or the user specified through the environment variable? 
```
bash-5.0# ps aux
PID   USER     TIME  COMMAND
    1 a         0:00 bash /entrypoint.sh master
   74 root      0:00 bash
  326 a         0:12 /usr/lib/jvm/java-1.8-openjdk/bin/java -cp /opt/alluxio-2.9.0-SNAPSHOT/conf/::/opt/alluxio-2.9.0-SNAPSHOT/assembly/alluxio-server-2.9.0
  327 a         0:17 /usr/lib/jvm/java-1.8-openjdk/bin/java -cp /opt/alluxio-2.9.0-SNAPSHOT/conf/::/opt/alluxio-2.9.0-SNAPSHOT/assembly/alluxio-server-2.9.0
  667 root      0:00 ps aux
bash-5.0# whoami
root
```

2022-07-20 06:12 UTC, beinan commented
> @JiamingMai After I run `docker exec -it alluxio-master bash` and `whoami` inside the container, it returns user `root`. Is it possible to run as user Alluxio by default or the user specified through the environment variable?
> 
> ```
> bash-5.0# ps aux
> PID   USER     TIME  COMMAND
>     1 a         0:00 bash /entrypoint.sh master
>    74 root      0:00 bash
>   326 a         0:12 /usr/lib/jvm/java-1.8-openjdk/bin/java -cp /opt/alluxio-2.9.0-SNAPSHOT/conf/::/opt/alluxio-2.9.0-SNAPSHOT/assembly/alluxio-server-2.9.0
>   327 a         0:17 /usr/lib/jvm/java-1.8-openjdk/bin/java -cp /opt/alluxio-2.9.0-SNAPSHOT/conf/::/opt/alluxio-2.9.0-SNAPSHOT/assembly/alluxio-server-2.9.0
>   667 root      0:00 ps aux
> bash-5.0# whoami
> root
> ```

@JiamingMai , could you take a look at @ssz1997 's comments?  thanks!

2022-07-20 06:36 UTC, JiamingMai commented
> @JiamingMai After I run `docker exec -it alluxio-master bash` and `whoami` inside the container, it returns user `root`. Is it possible to run as user Alluxio by default or the user specified through the environment variable?
> 
> ```
> bash-5.0# ps aux
> PID   USER     TIME  COMMAND
>     1 a         0:00 bash /entrypoint.sh master
>    74 root      0:00 bash
>   326 a         0:12 /usr/lib/jvm/java-1.8-openjdk/bin/java -cp /opt/alluxio-2.9.0-SNAPSHOT/conf/::/opt/alluxio-2.9.0-SNAPSHOT/assembly/alluxio-server-2.9.0
>   327 a         0:17 /usr/lib/jvm/java-1.8-openjdk/bin/java -cp /opt/alluxio-2.9.0-SNAPSHOT/conf/::/opt/alluxio-2.9.0-SNAPSHOT/assembly/alluxio-server-2.9.0
>   667 root      0:00 ps aux
> bash-5.0# whoami
> root
> ```

You can docker exec -it -u user_name

2022-07-20 17:06 UTC, ssz1997 approved these changes
LGTM. Thanks for adding this functionality

2022-07-20 17:41 UTC, beinan commented
alluxio-bot, merge this please.

2022-07-20 17:41 UTC, merged

2022-07-29 17:54 UTC, ZhuTopher commented
Duplicating this comment for posterity: https://github.com/Alluxio/alluxio/pull/15980#discussion_r933496712

---

By the way forcing the Pod/Container to use the root user from https://github.com/Alluxio/alluxio/pull/15898 is slightly concerning from a security point-of-view (to put it lightly) 😅

Can we refactor the Dockerfile to create a different admin user with permission to create users/groups & assign file ownership (i.e: a sudo-er), but isn't root (uid=0, gid=0)? The rest will still be the same; after creating the alluxio user & group you run the process as that user. This is just so that the container image itself doesn't run with a root user (which is very dangerous if people can enter the container runtime somehow).

Example blogpost: https://blog.aquasec.com/rootless-containers-boosting-container-security