Fix an indentation problem
Alluxio/alluxio pull request #15915
Opened 2022-07-19 23:13 UTC by XuanlinGuan

### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

2022-07-19 23:27 UTC, beinan commented
@XuanlinGuan could you sign the CLA? I will review your pr very soon, thx!

2022-07-19 23:30 UTC, beinan requested changes

2022-07-19 23:30 UTC, beinan commented on core/common/src/main/java/alluxio/worker/block/BlockStore.java
> +      throws IOException;
The indentation is still not fully correct
```suggestion
      Protocol.OpenUfsBlockOptions options) throws IOException;
```

2022-07-20 01:04 UTC, beinan approved these changes
lgtm, thx!

2022-07-20 19:18 UTC, beinan commented
alluxio-bot, merge this please.

2022-07-20 19:53 UTC, Xenorith commented
signed cla has been received @Zijian-Zhu @HelloHorizon fya

2022-07-20 22:54 UTC, beinan commented
alluxio-bot, merge this please.

2022-07-20 22:54 UTC, merged