Fix RoundRobinPolicy
Alluxio/alluxio pull request #15964
Opened 2022-07-27 03:12 UTC by maobaolong

### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

2022-07-28 09:32 UTC, jiacheliu3 requested changes
Added  a high level comment, PTAL :)

2022-07-28 09:32 UTC, jiacheliu3 commented on core/client/fs/src/main/java/alluxio/client/block/policy/RoundRobinPolicy.java
> +  private static AtomicInteger mIndex = new AtomicInteger();
Does it make better sense if you just make this class a singleton?

2022-07-28 10:15 UTC, jiacheliu3 commented on core/client/fs/src/main/java/alluxio/client/block/policy/RoundRobinPolicy.java
> +  private static AtomicInteger mIndex = new AtomicInteger();
Basically using a static field to keep the state is a weird design, singleton is a better choice.

2022-08-11 16:16 UTC, maobaolong commented
@jiacheliu3 I totally agree your suggestion, just close this PR

2022-08-11 16:16 UTC, closed without merging