Fix snpashot replication test
Alluxio/alluxio pull request #15998
Opened 2022-08-02 18:09 UTC by tcrain

### What changes are proposed in this pull request?

Fixes snapshot replication test which could block sometimes by adding a timeout when GetInfo requests are disabled by mocking (as would happen they were not being mocked).

### Does this PR introduce any user facing changes?

No

2022-08-02 19:55 UTC, jenoudet requested changes

2022-08-02 19:55 UTC, jenoudet commented on core/server/common/src/test/java/alluxio/master/journal/raft/SnapshotReplicationManagerTest.java
> +        throw new IOException("get into disabled");
```suggestion
        throw new IOException("get info disabled");
```

2022-08-02 19:55 UTC, jenoudet approved these changes

2022-08-03 00:36 UTC, elega approved these changes
thanks for putting up the fix! :)

2022-08-03 07:07 UTC, Xenorith commented
alluxio-bot, merge this please

2022-08-03 07:07 UTC, merged