Support getMountTable without invoke ufs
Alluxio/alluxio pull request #16003
Opened 2022-08-03 15:14 UTC by maobaolong

### What changes are proposed in this pull request?

For some of operation come from client, it doesn't use the space related info about the mount point, meanwhile, invoke ufs to generate the space usage info is expensive for now,.

### Why are the changes needed?

User can pass an argument invokeUfs to specific whether invoke ufs.

### Does this PR introduce any user facing changes?

- Add an overload api for `getMountTable` with `invokeUfs` parameter.

2022-08-04 04:02 UTC, dbw9580 approved these changes
LGTM

2022-08-05 03:16 UTC, dbw9580 commented on core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
> +      boolean invokeUfs = request.hasInvokeUfs() ? request.getInvokeUfs() : true;
```
Set the invokeUfs default to true to include ufs usage info which requires talking to UFS and comes at a cost.
``

2022-08-05 03:53 UTC, maobaolong commented on core/server/master/src/main/java/alluxio/master/file/FileSystemMasterClientServiceHandler.java
> +      boolean invokeUfs = request.hasInvokeUfs() ? request.getInvokeUfs() : true;
Done

2022-08-05 03:54 UTC, maobaolong commented
@dbw9580 Thanks for your review and suggestion, push a new commit, PTAL

2022-08-23 04:04 UTC, dbw9580 approved these changes

2022-08-23 04:04 UTC, dbw9580 commented on core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
>    Map<String, MountPointInfo> getMountTable() throws IOException, AlluxioException;
This can actually be a default implementation that directly calls `getMountTable(true)`

2022-08-24 16:08 UTC, jiacheliu3 requested changes
Mostly LGTM with some minor comments. Thanks!

2022-08-24 16:08 UTC, jiacheliu3 commented on core/client/fs/src/main/java/alluxio/client/file/BaseFileSystem.java
> +  public Map<String, MountPointInfo> getMountTable(boolean invokeUfs)
invokeUfs -> checkUfs?

2022-08-24 16:08 UTC, jiacheliu3 commented on core/client/fs/src/main/java/alluxio/client/file/FileSystem.java
> +   * @param invokeUfs whether invoke ufs
```suggestion
   * @param checkUfs whether to get UFS usage info
```

2022-08-24 16:08 UTC, jiacheliu3 commented on core/client/fs/src/main/java/alluxio/client/file/FileSystemMasterClient.java
> +   * @return a map from String to {@link MountPointInfo}
```suggestion
   * @param checkUfs whether to get UFS usage info
   * @return a map from String to {@link MountPointInfo}
```

2022-08-24 16:08 UTC, jiacheliu3 commented on core/client/fs/src/main/java/alluxio/client/file/RetryHandlingFileSystemMasterClient.java
> +  public Map<String, alluxio.wire.MountPointInfo> getMountTable(boolean invokeUfs)
`boolean checkUfs`?

2022-08-24 16:08 UTC, jiacheliu3 commented on integration/fuse/src/test/java/alluxio/fuse/auth/AbstractAuthPolicyTest.java
> +      throw new UnsupportedOperationException();
```suggestion
      throw new UnsupportedOperationException("getMountTable() is not supported!");
```

2022-08-29 05:34 UTC, jiacheliu3 approved these changes
LGTM with some minor comments. Good to go once the minor comments and the conflict are resolved, thanks!

2022-08-29 05:34 UTC, jiacheliu3 commented on integration/fuse/src/test/java/alluxio/fuse/auth/AbstractAuthPolicyTest.java
> +      throw new UnsupportedOperationException();
^

2022-08-31 02:56 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2022-08-31 02:56 UTC, merged

2022-11-08 08:19 UTC, jiacheliu3 commented
@tcrain @elega @beinan  note this new API added, i'm actually thinking if this can be used in some existing client operations