Fix CSI nodeserver
Alluxio/alluxio pull request #16110
Opened 2022-08-29 18:18 UTC by ssz1997

Both `nodeID` and `volumeID` are needed for the fuse pod because:

1. If different volumes are used on the same node, we will create different fuse pod, so volume ID is needed.
2. If same volume is used across different nodes, we need to create fuse pods on every node, so node ID is needed.

2022-08-29 19:32 UTC, LuQQiu requested changes
Left some minor comments

2022-08-29 19:32 UTC, LuQQiu commented on integration/docker/csi/alluxio/nodeserver.go
> +	csiFusePodObj.Name = csiFusePodObj.Name + "-" + nodeId + "-" + req.GetVolumeId()
can we use strings.join(string[], "-")

2022-08-29 21:43 UTC, LuQQiu approved these changes
LGTM, thanks!

2022-08-29 21:44 UTC, LuQQiu commented
will our unit or integration tests touch CSI stuff?
or even kubernetes stuff?
Just feeling if not, the automated tests are pretty wasteful

2022-08-29 22:26 UTC, ssz1997 commented
Error: 9.808 [ERROR] Errors: 
Error: 9.809 [ERROR]   UpdateConfIntegrationTest » Runtime java.util.concurrent.TimeoutException: Tim...

2022-08-31 23:27 UTC, LuQQiu commented
alluxio-bot, merge this please

2022-08-31 23:27 UTC, merged