[WIP] Add an command to decommission a specific worker
Alluxio/alluxio pull request #16134
Opened 2022-09-01 14:25 UTC by YichuanSun

### What changes are proposed in this pull request?

A new command to decommission a single worker.

### Why are the changes needed?

https://github.com/Alluxio/alluxio/issues/15343
https://github.com/Alluxio/alluxio/pull/14000

Thanks for PR 14000, we want to give a more detailed version.

### Does this PR introduce any user facing changes?

Yes, I'll add them in the future.

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

2022-09-02 01:55 UTC, qian0817 commented
It looks like this PR has some duplication with the #15949 and #15956，Can you take a look and give some advice?

2022-09-02 02:10 UTC, qian0817 requested changes

2022-09-02 02:10 UTC, qian0817 commented on core/transport/src/main/proto/grpc/file_system_master.proto
> +  optional FileSystemMasterCommonPOptions commonOption = 3;
`FileSystemMasterCommonPOptions` is useless and I recommend moving this RPC to `block_master.proto`.

2022-09-02 16:19 UTC, YichuanSun commented
Thanks for advice of @qian0817😁👍! Today I have no time to modify more codes, I will deal with your comments this morning.

2022-09-03 13:35 UTC, jiacheliu3 commented
@dbw9580 @YichuanSun PTAL there's another existing PR with a similar ask (but not identical): https://github.com/Alluxio/alluxio/pull/15155
Just wanted to make sure we don't end up having multiple commands with overlapping functionality.

2022-10-04 06:47 UTC, jiacheliu3 reviewed
Good work! I left a few high level comments.

2022-10-04 14:21 UTC, YichuanSun commented on core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
> +  void decommissionWorker(String workerName, DecommissionWorkerContext decommissionWorkerContext)
Agreed. I confused the abstraction of BlockMaster and FileSystemMaster. I will modify them tomorrow. Thanks!

2022-10-05 01:20 UTC, jiacheliu3 commented on core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
> +  void decommissionWorker(String workerName, DecommissionWorkerContext decommissionWorkerContext)
The BlockMaster manages blocks therefore also manages all worker interactions. The FileSystemMaster manages the file abstraction including file system interface, inodes, and the inode tree structure. I guess that's how you can distinguish the two.

2022-10-11 01:01 UTC, YichuanSun commented
After rerethinking😅, the reboot method in AlluxioWorkerProcess is not thread-safe, I'll correct it.

2022-10-13 11:47 UTC, qian0817 commented on core/server/worker/src/main/java/alluxio/worker/AlluxioWorkerProcess.java
> +  public boolean rebootDataServer() throws IOException {
why need  to reboot data sever?

2022-10-13 11:53 UTC, qian0817 commented
Is there design doc for this feature, for some of the implemented code I don't understand why.

2022-10-17 08:37 UTC, YichuanSun commented
> Is there design doc for this feature, for some of the implemented code I don't understand why.

https://docs.google.com/document/d/1GDVghn_9AOViOoSDvt1sqR8tSdyUmZ6D8xKN9YmhRu0/edit#

2023-01-10 03:50 UTC, bzheng888 commented on core/server/master/src/main/java/alluxio/master/file/FileSystemMaster.java
> +  void decommissionWorker(String workerName, DecommissionWorkerContext decommissionWorkerContext)
@jiacheliu3 Little confused, the BlockMaster has not a object member filesystemmaster, but the filesystemmaster has a member object blockmaster, so maybe let the logic in filesystemmaster easier 🤔️?

2023-02-12 07:55 UTC, YichuanSun commented
> This pull request has been automatically marked as stale because it has not had recent activity. It will be closed in two weeks if no further activity occurs. Thank you for your contributions.

Do not stale it, I will improve this feature in the future.

2023-08-17 04:04 UTC, closed without merging