Add additional trie node functionality
Alluxio/alluxio pull request #16288
Opened 2022-10-10 20:53 UTC by tcrain

### What changes are proposed in this pull request?

Add additional trie node functionality.
- Store a typed value with each node
- A function to search an exact path
- A function to get the children of a path

### Why are the changes needed?

Additional functionality for new features.

### Does this PR introduce any user facing changes?

No

2022-10-11 21:59 UTC, jenoudet requested changes

2022-10-11 21:59 UTC, jenoudet commented on core/common/src/main/java/alluxio/conf/path/TrieNode.java
> +  public Stream<TrieNode<V>> getChildren(String path) {
```suggestion
  public Stream<TrieNode<V>> getLeafChildren(String path) {
```
Add `Leaf` or `Terminal` or some other identifier to the name of the function to indicate that it returns only terminal children.

2022-10-11 21:59 UTC, jenoudet commented on core/common/src/main/java/alluxio/conf/path/TrieNode.java
> +  public void clear() {
This method needs testing.

2022-10-11 23:21 UTC, jenoudet approved these changes

2022-10-12 09:10 UTC, jiacheliu3 reviewed
Oops isn't this one very similar to https://github.com/Alluxio/alluxio/pull/15578/files#diff-be4d1e03f8d902b61762f11e492379d838046277460ec713b9e18505545a58c8
Could you take a look and see if there's anything that can be reused/merged?

2022-10-13 19:01 UTC, yuzhu commented
alluxio-bot, merge this please

2022-10-13 19:01 UTC, merged