Add RPC call that keeps the client resource
Alluxio/alluxio pull request #16287
Opened 2022-10-10 20:40 UTC by tcrain

### What changes are proposed in this pull request?

Add an rpc call that keeps the client resource.

### Why are the changes needed?

Additional functionality needed for new rpc calls that must keep the connection open.

### Does this PR introduce any user facing changes?

No

2022-10-11 22:23 UTC, jenoudet requested changes

2022-10-11 22:23 UTC, jenoudet commented on core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
>     * and a null local block worker.
```suggestion
   * Creates a {@link FileSystemContext} with an empty subject
   * , a null local block worker, and the given master addresses.
```

2022-10-11 22:23 UTC, jenoudet commented on core/client/fs/src/main/java/alluxio/client/file/FileSystemContext.java
> +   * and a null local block worker, and the given .
```suggestion
   * and a null local block worker.
```

2022-10-11 23:21 UTC, jenoudet approved these changes

2022-10-13 19:00 UTC, yuzhu commented
alluxio-bot, merge this please

2022-10-13 19:00 UTC, merged