[DOCFIX] Add doc on how to deploy proxy in docker/k8s
Alluxio/alluxio pull request #16366
Opened 2022-10-19 23:22 UTC by ssz1997

Solves https://github.com/Alluxio/alluxio/issues/13137

2022-10-28 19:02 UTC, HelloHorizon requested changes
@ssz1997 thank you for doc! Left some minor comments

2022-10-28 19:02 UTC, HelloHorizon commented on docs/en/deploy/Running-Alluxio-On-Kubernetes.md
> +### Set up Alluxio Proxy server
```suggestion
### Start Alluxio Proxy server
```

2022-10-28 19:02 UTC, HelloHorizon commented on docs/en/deploy/Running-Alluxio-On-Kubernetes.md
> +### Set up Alluxio Proxy server
Set up is hard to follow. It will be better to change to sub-steps, like change configurations, start the proxy server, stop proxy server, etc.

2022-10-31 00:13 UTC, ssz1997 commented on docs/en/deploy/Running-Alluxio-On-Docker.md
> +### Set up Alluxio Proxy
I don't think we have a Proxy page...

2022-10-31 00:15 UTC, ssz1997 commented on docs/en/deploy/Running-Alluxio-On-Docker.md
> +configuration options for Alluxio proxy server.
The properties for proxy are all under "Common Configuration" and doesn't have its own section. I think it makes for proxy to has its own section

2022-10-31 16:11 UTC, HelloHorizon approved these changes
LGTM

2022-10-31 18:40 UTC, Xenorith commented
alluxio-bot, merge this please

2022-10-31 18:40 UTC, merged

2022-10-31 18:40 UTC, Xenorith commented
alluxio-bot, cherry-pick this to branch-2.9 please