Fix a bug in WorkerInfoField
Alluxio/alluxio pull request #16457
Opened 2022-11-02 13:10 UTC by YichuanSun

### What changes are proposed in this pull request?

enum `WorkerInfoField` in `GetWorkerReportOptions.java` has 10 fields, while the corresponding proto enum `WorkerInfoField` in `block_master.proto` has only 9 fields. The latter omits `BLOCK_COUNT`, this PR adds it, and changes the fields order of `WorkerInfoField` in `GetWorkerReportOptions.java`, to align their fields. Changing the fields order of `WorkerInfoField` in `block_master.proto` will have bad impact on the old design, so I change the order in `GetWorkerReportOptions.java`.

### Why are the changes needed?

If remain the bug, when someone set FieldRange `BLOCK_COUNT` and want to get it from master, RPC will throw exception "No enum constant alluxio.grpc.WorkerInfoField.BLOCK_COUNT".

### Does this PR introduce any user facing changes?

No.

2022-11-03 10:35 UTC, YichuanSun commented
@maobaolong FYI.

2022-11-05 11:40 UTC, dbw9580 approved these changes
LGTM

2022-11-05 11:44 UTC, dbw9580 commented
Can you please add some tests in `alluxio.cli.fsadmin.report.CapacityCommandTest`, since `CapacityCommand` is the major consumer of this API? This can come in a separate PR.

2022-11-05 13:30 UTC, dbw9580 requested changes

2022-11-05 13:30 UTC, dbw9580 commented on core/transport/src/main/proto/grpc/block_master.proto
> +  BLOCK_COUNT = 10;
You need to include the update `proto.lock`

2022-11-07 06:18 UTC, YichuanSun commented
> Can you please add some tests in `alluxio.cli.fsadmin.report.CapacityCommandTest`, since `CapacityCommand` is the major consumer of this API? This can come in a separate PR.

OK, I'll add the test later.

2022-11-14 06:09 UTC, dbw9580 approved these changes
LGTM

2022-11-14 06:57 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2022-11-14 06:57 UTC, merged