Add WorkerInfoField test in CapacityCommandTest
Alluxio/alluxio pull request #16507
Opened 2022-11-09 07:54 UTC by YichuanSun

### What changes are proposed in this pull request?

As the title. If Options has a WorkerInfoField which POptions does not have, or if POptions has a WorkerInfoField which Options does not have, this test will be failed. The latest test version can not check these two error, as shown in the PR below.

### Why are the changes needed?

[Add missing variant in gRPC WorkerInfoField](https://github.com/Alluxio/alluxio/pull/16457)

### Does this PR introduce any user facing changes?

No.

2022-11-09 07:55 UTC, YichuanSun commented
@dbw9580 PTAL.

2022-11-14 06:06 UTC, dbw9580 requested changes
On second thought, this should belong in its own unit test class. please create a new UT for `GetWorkerReportOptions` and add the test there.

2022-11-14 06:06 UTC, dbw9580 commented on shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
> +    GetWorkerReportOptions.defaults().toProto();
for a test to work, you need to encode the property being tested as an assertion, e.g.

```java
assertEquals(GetWorkerReportPOptions.getDefaultInstance(),
    GetWorkerReportOptions.defaults().toProto());
```

Ideally, you don't need to waste time writing comments explaining what is being tested, but rather the test code should be self-explanatory as if you are reading a plain English sentence. In this case, you can read it aloud as "the default value of a gRPC `GetWorkerReportOptions` equals the default value of the java instance returned by the `default` method and then converted to the gRPC representation."

2022-11-14 06:06 UTC, dbw9580 commented on shell/src/test/java/alluxio/cli/fsadmin/report/CapacityCommandTest.java
> +  public void workerInfoFieldCapacity() throws IOException {
give the test method a better name that directly reflects what is being tested.

2022-11-24 08:45 UTC, dbw9580 commented
@YichuanSun can you please address the review comments?

2022-11-28 03:04 UTC, dbw9580 approved these changes
LGTM

2022-11-28 03:04 UTC, dbw9580 commented on core/client/fs/src/test/java/alluxio/client/block/options/GetWorkerReportOptionsTest.java
> +  public void GetWorkerReportOptionsMapTest() {
```suggestion
  public void identicalFieldsForWorkerInfoAndRange() {
```

2023-02-21 07:18 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2023-02-21 07:18 UTC, merged