Ignore no_cache setting for "load" command
Alluxio/alluxio pull request #16544
Opened 2022-11-14 06:55 UTC by secfree

### What changes are proposed in this pull request?

Ignore no_cache setting for "load" command.

### Why are the changes needed?

Currently the "load" command behaviours strangely if the corresponding node/client has the setting

```
alluxio.user.file.readtype.default=NO_CACHE
```

It reports "loaded" every time repeatedly

```
$ ./bin/alluxio fs load /test/file.01
/test/file.01 loaded

$ ./bin/alluxio fs load /test/file.01
/test/file.01 loaded
```

After applying this PR, the behaviour changes to

```
$ ./bin/alluxio fs load /test/file.01
/test/file.01 loaded

$ ./bin/alluxio fs load /test/file.01
/test/file.01 already in Alluxio fully
```

### Does this PR introduce any user facing changes?

No

2022-11-14 23:29 UTC, maobaolong approved these changes
I totally agree to have this patch, `bin/alluxio fs load xxxx` with no cache related read type can make people confusing.

2022-11-17 23:17 UTC, LuQQiu commented
@jja725 PTAL, thanks

2022-11-28 21:36 UTC, jja725 requested changes
Thanks for the contribution!

2022-11-28 21:36 UTC, jja725 commented on shell/src/main/java/alluxio/cli/fs/command/LoadCommand.java
> +        openUfsBlockOptions = Protocol.OpenUfsBlockOptions.newBuilder(openUfsBlockOptions)
we want to keep the original OpenUfsBlockOptions information but only update the NoCache field.

2022-11-28 21:39 UTC, jja725 approved these changes

2022-11-28 22:41 UTC, Xenorith commented
alluxio-bot, merge this please

2022-11-28 22:41 UTC, merged