[DOCFIX] Update cn version of Architecture doc
Alluxio/alluxio pull request #16687
Opened 2022-12-30 03:37 UTC by 007DXR

What changes are proposed in this pull request?
Update cn version of Architecture doc.

Why are the changes needed?
The Chinese overview/Architecture document is not updated with the latest changes,
this PR synchronizes these updates.

Does this PR introduce any user facing changes?
Developers can get to know Alluxio in Chinese easily.

2023-01-03 03:51 UTC, Jackson-Wang-7 reviewed
Please remove unnecessary white spaces. Thanks! It's better to check the whole doc. there are many similar questions I don't mark.

2023-01-03 03:51 UTC, Jackson-Wang-7 commented on docs/cn/overview/Architecture.md
> +Alluxio 包含两种不同类型的master进程。一种是 **Alluxio Master**，Alluxio Master 服务所有用户请求并记录文件系统元数据修改情况。另一种是 **Alluxio Job Master**， 这是一种用来调度将在**Alluxio Job Workers**上执行的各种文件系统操作的轻量级调度程序。
why do some have whitespaces before `**Alluxio Job Master**` and some have no whitespaces?
there is no need for whitespace before "这是一种用来调度".

2023-01-03 03:51 UTC, Jackson-Wang-7 commented on docs/cn/overview/Architecture.md
> +Job service的设计使得所有与Job相关的进程不一定需要与其他Alluxio 集群位于同一位置。但是，为了使得RPC 和数据传输延迟较低，我们还是建议将job worker与对应的Alluxio worker并置 。
> 不一定需要与其他Alluxio 集群位于同一位置
> 为了使得RPC 和数据传输延迟较低

Remove unnecessary whitespaces

2023-01-09 09:25 UTC, Jackson-Wang-7 approved these changes
LGTM

2023-01-09 09:27 UTC, Jackson-Wang-7 commented
@HelloHorizon Please check it, I have reviewed it.

2023-01-09 18:06 UTC, LuQQiu commented
@HelloHorizon @Xenorith do you guys want to give a final pass before merging it?

2023-01-09 18:44 UTC, Xenorith approved these changes

2023-01-09 19:05 UTC, HelloHorizon requested changes
@007DXR Thanks for the great work! Leave some minor comments

2023-01-09 19:05 UTC, HelloHorizon commented on docs/cn/overview/Architecture.md
> +- 将数据从UFS加载到Alluxio
```suggestion
- 将数据从UFS(under file system)加载到Alluxio
```
Let's make some explanation here since it's the first time we mention UFS in this page.

2023-01-09 19:05 UTC, HelloHorizon commented on docs/cn/overview/Architecture.md
> +Alluxio worker负责管理分配给Alluxio的用户可配置本地资源（RAM、SSD、HDD 等）。Alluxio worker以block为单位存储数据，并通过在其本地资源中读取或创建新的block来服务client读取或写入数据的请求。worker只负责管理block, 从文件到block的实际映射都由master管理。
```suggestion
Alluxio worker负责管理分配给Alluxio的用户可配置本地资源（RAMDisk、SSD、HDD 等）。Alluxio worker以block为单位存储数据，并通过在其本地资源中读取或创建新的block来服务client读取或写入数据的请求。worker只负责管理block, 从文件到block的实际映射都由master管理。
```

2023-01-11 17:14 UTC, HelloHorizon approved these changes

2023-01-11 17:15 UTC, HelloHorizon commented
alluxio-bot, merge this please

2023-01-11 17:15 UTC, merged