Remove master/worker java opts from monitor java opts
Alluxio/alluxio pull request #16688
Opened 2022-12-30 05:19 UTC by humengyu2012

### What changes are proposed in this pull request?

1. Remove master/worker java opts from monitor java opts;
2. Add default value for monitor java opts.

### Why are the changes needed?

https://github.com/Alluxio/alluxio/issues/16657
https://github.com/Alluxio/alluxio/issues/10958
https://github.com/Alluxio/alluxio/issues/15168

### Does this PR introduce any user facing changes?
no

2023-01-03 17:27 UTC, LuQQiu commented
@humengyu2012 can you help sign the contribution license agreement (CLA)? Otherwise we do not have the permission to merge the PR, appreciate your help

2023-01-03 19:55 UTC, LuQQiu requested changes
Thanks for fixing the issue and contributing the code back, left some minor comments, otherwise LGTM

2023-01-03 19:55 UTC, LuQQiu commented on bin/alluxio-monitor.sh
> +  ALLUXIO_MONITOR_JAVA_OPTS_DEFAULT="-Xms256M -Xmx256M"
Why needs the default value?

2023-01-03 19:55 UTC, LuQQiu commented on conf/alluxio-env.sh.template
> +# Config properties set for Alluxio shell. (Default: "-Xms256M -Xmx256M")
Can we give more detailed description for when this opts is needed to be set?
e.g. # Config properties for the monitoring service used by Alluxio shell to monitor the healthiness of Alluxio master process.

2023-01-04 18:59 UTC, LuQQiu approved these changes
LGTM, thanks for the contribution

2023-01-04 19:00 UTC, LuQQiu commented
alluxio-bot, merge this please

2023-01-04 19:00 UTC, merged

2023-01-05 19:05 UTC, LuQQiu commented
@humengyu2012  the change is reverted because of fierce discussion internally. 

The old approach: able to reuse the address information and may be other information set by the main java opts (e.g. ALLUXIO_MASTER_MONITOR_JAVA_OPTS can reuse the information set by `ALLUXIO_MASTER_JAVA_OPTS`). This is especially helpful in Kubernetes environment where all the Alluxio configuration is set by Java opts.
The old approach has the bugs that you try to solve here.

Your new approach:
1. Improve correctness, definitely more correct
2. but reduce ease of use especially in Kubernetes environment. User may need to copy the ALLUXIO_MASTER_JAVA_OPTS into ALLUXIO_MASTER_MONITOR_JAVA_OPTS

The solution we want is a combination of both approaches:
1. Maintain the ease of use. Do not require user to copy the java opts and double the configuration file length.
2. Do not have the identified bugs

2023-01-05 21:33 UTC, ssz1997 commented
@LuQQiu 

Launching Alluxio in k8s doesn't use the monitor as k8s has its own readiness/liveness probe.

More specifically, `entrypoint.sh` directly calls `launch-process` which doesn't involve the monitor script. `alluxio-monitor.sh` is only called when alluxio is launched by using `alluxio-start.sh` script.

2023-01-10 21:05 UTC, jenoudet commented
According to [this post](https://stackoverflow.com/a/10958164/15160749) on Stack Overflow, options use the value specified last. We could append `-Xms256M -Xmx256M` to the current opts to override specifically the memory allocation opts.