[DOCFIX] Update cn version of Job Service doc
Alluxio/alluxio pull request #16686
Opened 2022-12-30 03:23 UTC by 007DXR

### What changes are proposed in this pull request?

Update cn version of Job Service doc.

### Why are the changes needed?

The Chinese overview/Job Service document is not updated with the latest changes,
this PR synchronizes these updates.

### Does this PR introduce any user facing changes?

Developers can get to know Alluxio in Chinese easily.

2023-01-03 20:54 UTC, LuQQiu requested changes
Thanks for updating the job service doc, left some comments

2023-01-03 20:54 UTC, LuQQiu commented on docs/cn/overview/JobService.md
> +title: 作业服务
@jja725 what's the translation for job service? 任务分配器？作业服务器？

2023-01-03 20:54 UTC, LuQQiu commented on docs/cn/overview/JobService.md
> +Load Job 作为`fs distributedLoad` CLI 命令的一部分，会按特定的副本数将文件加载到 Alluxio。
不需要直接翻译哈，可以意译
`fs distributedLoad` 分布式加载命令中使用了加载作业，按特定的副本数将文件加载到 Alluxio。

2023-01-03 20:54 UTC, LuQQiu commented on docs/cn/overview/JobService.md
> +Migrate Job 作为`fs distributedCp`  和 `fs distributedMv` CLI 命令的一部分，负责使用固定的 [WriteType]({{ '/en/overview/Architecture.html#data-flow-write' | relativize_url }}) 进行数据复制/移动。
同样，fs distributedCp` 和 `fs distributedMv` CLI 命令 使用 迁移任务，使用固定的。。。

2023-01-03 20:54 UTC, LuQQiu commented on docs/cn/overview/JobService.md
> +Persist Job 间接作为`fs persist` CLI 命令的一部分，在使用 ASYNC_THROUGH [WriteType]({{ '/en/overview/Architecture.html#data-flow-write' | relativize_url }}) 写入 Alluxio 时在后台进行持久化。
same here

2023-01-03 20:54 UTC, LuQQiu commented on docs/cn/overview/JobService.md
> +Persist Job 间接作为`fs persist` CLI 命令的一部分，在使用 ASYNC_THROUGH [WriteType]({{ '/en/overview/Architecture.html#data-flow-write' | relativize_url }}) 写入 Alluxio 时在后台进行持久化。
same for other jobs

2023-01-04 05:21 UTC, LuQQiu commented on docs/cn/overview/JobService.md
> +Migrate Job 作为`fs distributedCp`  和 `fs distributedMv` CLI 命令的一部分，负责使用固定的 [WriteType]({{ '/en/overview/Architecture.html#data-flow-write' | relativize_url }}) 进行数据复制/移动。
lol 我也在思考，应该作业或者任务都可以

2023-01-07 02:09 UTC, LuQQiu requested changes
Left some minor comments, otherwise LGTM

2023-01-07 02:09 UTC, LuQQiu commented on docs/cn/overview/JobService.md
> +`job stat -v <job_id>` 会列出某个作业的详细信息。（加 -v 表示包含worker上指定任务的信息）
backstick around `-v`

2023-01-07 02:09 UTC, LuQQiu commented on docs/cn/overview/JobService.md
> +### 加载
这些作业因为涉及了命令具体使用的英文，可以加上英文
比如
 标题： 加载 Load

2023-01-07 02:09 UTC, LuQQiu commented on docs/cn/overview/JobService.md
> +`fs persist` CLI命令间接使用了持久化作业，以ASYNC_THROUGH[写入类型]({{ '/en/overview/Architecture.html#data-flow-write' | relativize_url }})写入Alluxio时使用持久化作业在后台进行持久化。
backstick around ASYNC_THROUGH
for all the information that is code instead of human language, using backstick around the code to make it clearer

2023-01-07 02:09 UTC, LuQQiu commented on docs/cn/overview/JobService.md
> +作业服务器提供大量的巡检命令。
作业服务器提供以下一系列的巡检命令。

2023-01-09 20:16 UTC, LuQQiu approved these changes
LGTM, thanks for translating the doc!
@Xenorith Please help give a final pass

2023-01-09 20:23 UTC, Xenorith approved these changes

2023-01-09 20:31 UTC, merged