Metric doc
Alluxio/alluxio pull request #16701
Opened 2023-01-03 13:25 UTC by voddle

What changes are proposed in this pull request?
Update cn version of Metric doc.

Why are the changes needed?
There is no corresponding Chinese documentation for Metrics.

Does this PR introduce any user facing changes?
More Chinese users can access Alluxio documentation more easily.

2023-01-03 20:27 UTC, LuQQiu requested changes
Thanks for updating the metrics chinese doc! The translation is of really high quality. Left some minor comments, the translation overall LGTM

2023-01-03 20:27 UTC, LuQQiu commented on docs/cn/reference/Metric-doc.md
> +
remove extra empty line

2023-01-03 20:27 UTC, LuQQiu commented on docs/cn/reference/Metric-doc.md
> +* 合计指标由领头的 master 收集和计算的，并且在 web UI 下的指标标签下展示。
领头的 master -> can directly use "leading master" without translation

2023-01-03 20:27 UTC, LuQQiu commented on docs/cn/reference/Metric-doc.md
> +Metrics in Alluxio have the following format for master node metrics:
this line can be removed?

2023-01-03 20:27 UTC, LuQQiu commented on docs/cn/reference/Metric-doc.md
> +每个客户端度量将使用其本地主机名或配置的 alluxio.user.app.id 进行记录。
alluxio.user.app.id 可以加上 backstick

2023-01-03 20:30 UTC, LuQQiu commented
@voddle have you joined Alluxio slack channel? https://alluxio-community.slack.com/join/shared_invite/zt-ffbj8sli-wQlgpP0_Cr~4~kWmqcnnHQ#/shared-invite/email

most of our engineers are available on slack channel for discussing issues or developments. 
Could you join Alluxio slack channel and send a direct message to me? my slack name is Lu Qiu (Alluxio)

2023-01-07 02:11 UTC, LuQQiu commented
@voddle Thanks for translating all the metrics description!
@Xenorith if we want to keep cn in sync with en, probably need to have a maintainable way of updating metric key and property key.

2023-01-07 02:21 UTC, LuQQiu requested changes
Left some minor comments, otherwise LGTM

2023-01-07 02:21 UTC, LuQQiu commented on docs/cn/reference/Metric-doc.md
> +title: List of Metrics
Rename the file to Metric-List.md?

2023-01-07 02:21 UTC, LuQQiu commented on docs/cn/reference/Metric-doc.md
> +
remove the extra empty line? since the content is logically connected

2023-01-07 02:21 UTC, LuQQiu commented on docs/cn/reference/Metric-doc.md
> +* 合计指标由 leading master 收集和计算的，并且在 web UI 下的指标标签下展示。
we use either 合计指标 or 集群指标，and being consistent in the translation for cluster metrics

2023-01-07 02:21 UTC, LuQQiu commented on docs/cn/reference/Metric-doc.md
> +
remove the extra line so that the following line can belong to the format of the previous line. They are all belong to 进程指标

2023-01-07 02:21 UTC, LuQQiu commented on docs/cn/reference/Metric-doc.md
> +Alluxio 的主节点指标具有以下格式：
master node -> master 节点
专属名词可以不用翻译

2023-01-07 02:21 UTC, LuQQiu commented on docs/cn/reference/Metric-doc.md
> +Alluxio 的非主节点指标具有以下格式
非 master 节点

2023-01-07 02:22 UTC, LuQQiu commented
@Xenorith PTAL, thanks

2023-01-07 02:34 UTC, Xenorith commented
> @voddle Thanks for translating all the metrics description! @Xenorith if we want to keep cn in sync with en, probably need to have a maintainable way of updating metric key and property key.

since this is a generated doc, it should be ignored by the sync process. then we will have to remember to build both en and cn when regenerating docs

2023-01-07 02:36 UTC, LuQQiu commented
> > @voddle Thanks for translating all the metrics description! @Xenorith if we want to keep cn in sync with en, probably need to have a maintainable way of updating metric key and property key.
> 
> since this is a generated doc, it should be ignored by the sync process. then we will have to remember to build both en and cn when regenerating docs

we can autogenerate Chinese one as well?

2023-01-07 02:37 UTC, Xenorith commented
> > > @voddle Thanks for translating all the metrics description! @Xenorith if we want to keep cn in sync with en, probably need to have a maintainable way of updating metric key and property key.
> > 
> > 
> > since this is a generated doc, it should be ignored by the sync process. then we will have to remember to build both en and cn when regenerating docs
> 
> we can autogenerate Chinese one as well?

well... i guess we'd need to write some code but that is my opinion on how to maintain it properly

2023-01-07 09:53 UTC, jiacheliu3 requested changes
Thanks for the hard work! I added some comments.

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/client-metrics.yml
> +  '这个客户端短路写入到本地存储的字节总数'
```suggestion
  '客户端短路写入Alluxio缓存的字节总数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/client-metrics.yml
> +  '这是一项测量从远程 Alluxio worker 通过 RPC 框架以 chunk 的形式读取 block 数据的定时器统计信息。当 alluxio.user.block.read.metrics.enabled 设置为 true 时，才会记录此指标'
看情况，很多Client.XXX的metric都可以加上“这个客户端”

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/fuse-metrics.yml
> +  'JNI FUSE 操作调用的吞吐量。此指标表明 Alluxio Fuse 应用处理请求的繁忙程度'
吞吐量还是总数？

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/server-metrics.yml
> +  'JVM 睡眠且进行 GC 的总时间'
```suggestion
  'JVM 暂停的总时间，JVM暂停通常由GC或jstack等事件引发'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/client-metrics.yml
> +  '这个客户端写入到 Alluxio UFS 的字节数'
```suggestion
  '这个客户端写入 UFS 的字节数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/client-metrics.yml
> +  '由于客户端缓存未命中从外部存储读取的总字节数'
```suggestion
  '由于客户端缓存未命中从Alluxio集群读取的总字节数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/client-metrics.yml
> +  '客户端缓存命中时读取页面以纳秒为单位的时间'
```suggestion
  '客户端缓存命中时读取页面时间（ns）'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/client-metrics.yml
> +  '当缓存未命中时，从外部源读取数据所花费以纳秒为单位的时间'
```suggestion
  '当缓存未命中时，从外部源读取数据所花费时间（ns）'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/client-metrics.yml
> +  '向客户端缓存中防止缓存数据的失败次数'
```suggestion
  '向客户端缓存中放置缓存数据的失败次数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '由 worker 管理的活跃 read-RPC 数量'
```suggestion
  ' worker 上进行中的 read-RPC 数量'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '由 worker 管理的活跃 write-RPC 数量'
```suggestion
  'worker 上进行中的 write-RPC 数量'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '由所有客户端报告的短路读取的总字节数。每个客户端直接从与其配对的 worker 存储中读取数据'
```suggestion
  '由所有客户端报告的短路读取的总字节数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '从所有外部 RPC 的 worker 线程读取的字节数。数据存在于 worker 存储中或者由 worker 从 UFS 获取。这记录了 worker 内部调用（e.g. 嵌入在 worker 中的客户端）读取的数据。'
这两个这么长吗？

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '所有 worker 从所有 Alluxio UFS 读取的字节数总和'
```suggestion
  '所有 worker 从所有 UFS 读取的字节数总和'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '所有 worker 从所有 Alluxio UFS 每分钟读取的字节数吞吐量'
```suggestion
  '所有 worker 从所有 UFS 每分钟读取的字节数吞吐量'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '所有 worker 向所有 Alluxio UFS 写入的字节数总和'
```suggestion
  '所有 worker 向所有 UFS 写入的字节数总和'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '所有 worker 每分钟向所有 Alluxio UFS 写入字节的吞吐量'
```suggestion
  '所有 worker 每分钟向所有 UFS 写入字节的吞吐量'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '展示当前 leader id'
```suggestion
  '展示当前 primary master id'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '当前 leader 的 index'
```suggestion
  '当前 primary master 的序号'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '此 worker 中任意一个块可以被访问的总时间'
```suggestion
  '此 worker 中数据块被访问的总次数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '此 worker 读的本地块总数'
```suggestion
  '通过此 worker 本地读的数据块总数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '此 worker 读的远端块总数'
```suggestion
  '通过此 worker 远程读的数据块总数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '此 worker 读的 UFS 块总数'
```suggestion
  '通过此 worker 从 UFS 读取的数据块总数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '此 worker 从特定 Alluxio UFS 读取的总字节数'
```suggestion
  '此 worker 从特定 UFS 读取的总字节数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '此 worker 通过网络（RPC）读取的字节总数。数据存在于 worker 存储中或由该 worker 从底层 UFS 获取。这不包括短路本地读取和域套接字读取'
```suggestion
  '通过网络（RPC）远程读取此 worker 的字节总数。数据存在于 worker 存储中或由该 worker 从底层 UFS 获取。这不包括短路本地读取和域套接字读取'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '由此 worker 从 Alluxio UFS 读取字节的吞吐量'
```suggestion
  '由此 worker 从 UFS 读取字节的吞吐量'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '此 worker 通过域套接字写入的总字节数'
```suggestion
  '通过域套接字写入此 worker 的总字节数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '此 worker 通过域套接字写入字节的吞吐量'
```suggestion
  '通过域套接字写入此 worker 的吞吐量'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '此 worker 向特定 Alluxio UFS 写入的总字节数'
```suggestion
  '此 worker 向特定 UFS 写入的总字节数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '在特定 Alluxio worker 的所有层级上的总空闲字节'
```suggestion
  '此 Alluxio worker 的所有层级上的总空闲字节'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '在所有层次的特定 Alluxio worker 上以字节为单位的总容量'
```suggestion
  '此 Alluxio worker 在所有层次上以字节为单位的总容量'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/worker-metrics.yml
> +  '特定 Alluxio worker 所有层级上使用的总字节数'
```suggestion
  '此 Alluxio worker 所有层级上使用的总字节数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  'Alluxio 中独特块总数'
```suggestion
  'Alluxio 中数据块总数（不算副本）'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  'UFS 日志初始回放过程的持续时间。只在使用 UFS 日志时有效。它记录了第一次日志回放的持续时间。使用这个指标来监测你的 master 启动时间是否过长'
```suggestion
  '启动时 UFS 日志初始回放过程的持续时间。只在使用 UFS 日志时有效。它记录了第一次日志回放的持续时间。使用这个指标来监测你的 master 启动时间是否过长'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  'master RPC 调用的吞吐量。这个指标表明 master 服务客户端和 client 请求的繁忙程度'
```suggestion
  'master RPC 调用的吞吐量。这个指标表明 master 服务客户端请求的繁忙程度'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '这个指标通过汇总 Master.RocksBlockEstimatedMemUs age 和 Master.RocksInodeEstimatedMemUsage 的值，给出了 RocksDB 内存使用总量'
```suggestion
  '这个指标通过汇总 Master.RocksBlockEstimatedMemUsage 和 Master.RocksInodeEstimatedMemUsage 的值，给出了 RocksDB 内存使用总量的估计值'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '从元数据同步取消的预取任务数量'
```suggestion
  '从元数据同步取消的预取任务数量（由于重复的预取请求）'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '丢失独特块计数'
```suggestion
  '丢失数据块计数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '上一次备份的处理时间'
```suggestion
  '上一次备份的时间'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '当 leading master 初始化元数据时，从备份还原的条目总数'
```suggestion
  '当 primary master 初始化元数据时，从备份还原的条目总数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '失败状态任务数'
```suggestion
  '失败状态异步任务数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '运行中状态任务数'
```suggestion
  '运行中状态异步任务数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '取消状态任务数'
```suggestion
  '取消状态异步任务数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '完成状态任务数'
```suggestion
  '完成状态异步任务数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  'inode（inode 元数据）缓存的 miss 总数'
```suggestion
  'inode 缓存未命中总数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '描述将日志快照重放到主机状态机所需的时间。只有在使用嵌入式日志时才有效。使用此指标确定 Alluxio 重放日志快照文件时的性能。较高的数字可能表示磁盘或 CPU 竞争较慢'
```suggestion
  '描述将日志快照重放到主机状态机所需的时间。只有在使用嵌入式日志时才有效。使用此指标确定 Alluxio 重放日志快照文件时的性能。较高的数字可能表示磁盘性能低或 CPU 竞争大'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '描述从另一个主机安装下载的日志快照所需的时间。只有在使用嵌入式日志时有效。使用此指标可以确定 Alluxio 在从 leader 安装快照时的性能。较高的数字可能表明磁盘或 CPU 竞争较慢'
```suggestion
  '描述从另一个主机安装下载的日志快照所需的时间。只有在使用嵌入式日志时有效。使用此指标可以确定 Alluxio 在从 leader 安装快照时的性能。较高的数字可能表示磁盘性能低或 CPU 竞争大'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '主边锁池的大小'
```suggestion
  'Edge锁池的大小'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '块堆大小的估计值'
```suggestion
  '数据块元数据占JVM堆大小的估计值'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '审核日志条目阻塞队列的大小'
```suggestion
  '审核日志条目队列的大小'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '缺失缓存的缓存命中次数'
```suggestion
  'Absent cache（记录不存在的路径）的缓存命中次数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '缺失缓存的缓存未命中次数'
```suggestion
  'Absent cache（记录不存在的路径）的缓存未命中次数'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  '缺失缓存的大小'
```suggestion
  'Absent cache（记录不存在的路径）的大小'
```

2023-01-07 09:53 UTC, jiacheliu3 commented on docs/_data/table/cn/master-metrics.yml
> +  'Alluxio 维护了一个缺失 UFS 路径的缓存。这是正在处理的 UFS 路径数量。'
```suggestion
  'Alluxio 维护了一个Absent cache（记录不存在的路径），这是正在处理的 UFS 路径数量。'
```

2023-01-08 14:38 UTC, voddle commented on docs/_data/table/cn/client-metrics.yml
> +  '这是一项测量从远程 Alluxio worker 通过 RPC 框架以 chunk 的形式读取 block 数据的定时器统计信息。当 alluxio.user.block.read.metrics.enabled 设置为 true 时，才会记录此指标'
这样意思不会改变太多吗

2023-01-08 15:10 UTC, voddle commented on docs/_data/table/cn/fuse-metrics.yml
> +  'JNI FUSE 操作调用的吞吐量。此指标表明 Alluxio Fuse 应用处理请求的繁忙程度'
The English version is 'Throughput of JNI FUSE operation calls. This metrics indicates how busy the Alluxio Fuse application is serving requests', I'm confused as well.

2023-01-08 15:37 UTC, voddle commented on docs/_data/table/cn/cluster-metrics.yml
> +  '从所有外部 RPC 的 worker 线程读取的字节数。数据存在于 worker 存储中或者由 worker 从 UFS 获取。这记录了 worker 内部调用（e.g. 嵌入在 worker 中的客户端）读取的数据。'
看起来有，怎么简化一下比较好？

2023-01-09 10:10 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '从所有外部 RPC 的 worker 线程读取的字节数。数据存在于 worker 存储中或者由 worker 从 UFS 获取。这记录了 worker 内部调用（e.g. 嵌入在 worker 中的客户端）读取的数据。'
汇总在所有worker上不通过RPC读取的字节数。这记录了 worker 内部调用（e.g. 嵌入在 worker 中的客户端）读取的数据，数据存在于worker缓存中或由worker从UFS获取

2023-01-10 03:31 UTC, voddle commented on docs/_data/table/cn/cluster-metrics.yml
> +  '从所有外部 RPC 的 worker 线程读取的字节数。数据存在于 worker 存储中或者由 worker 从 UFS 获取。这记录了 worker 内部调用（e.g. 嵌入在 worker 中的客户端）读取的数据。'
这里 en/cluster-metrics.yml 就有错误，line 6 == line 8

2023-01-10 04:35 UTC, jiacheliu3 commented on docs/_data/table/cn/cluster-metrics.yml
> +  '从所有外部 RPC 的 worker 线程读取的字节数。数据存在于 worker 存储中或者由 worker 从 UFS 获取。这记录了 worker 内部调用（e.g. 嵌入在 worker 中的客户端）读取的数据。'
在这里我们把翻译改正吧，英文版本身的正确你可以之后开一个PR去改

2023-01-10 09:36 UTC, jiacheliu3 approved these changes
LGTM, thanks a lot for the work!

2023-01-10 09:37 UTC, jiacheliu3 commented
> > > > @voddle Thanks for translating all the metrics description! @Xenorith if we want to keep cn in sync with en, probably need to have a maintainable way of updating metric key and property key.
> > > 
> > > 
> > > since this is a generated doc, it should be ignored by the sync process. then we will have to remember to build both en and cn when regenerating docs
> > 
> > 
> > we can autogenerate Chinese one as well?
> 
> well... i guess we'd need to write some code but that is my opinion on how to maintain it properly

@Xenorith What is the next step on this PR? Are we merging this or we need some other automation? Thx :)

2023-01-10 17:20 UTC, Xenorith commented
> > > > > @voddle Thanks for translating all the metrics description! @Xenorith if we want to keep cn in sync with en, probably need to have a maintainable way of updating metric key and property key.
> > > > 
> > > > 
> > > > since this is a generated doc, it should be ignored by the sync process. then we will have to remember to build both en and cn when regenerating docs
> > > 
> > > 
> > > we can autogenerate Chinese one as well?
> > 
> > 
> > well... i guess we'd need to write some code but that is my opinion on how to maintain it properly
> 
> @Xenorith What is the next step on this PR? Are we merging this or we need some other automation? Thx :)

we can merge it first and worry about the automation later, if needed

2023-01-11 02:35 UTC, jiacheliu3 commented
Merging as all comments have been resolved. Should a better way of automation be discovered, that would be done on top of the translations added here.

2023-01-11 02:35 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2023-01-11 02:35 UTC, merged