[DOCFIX] Update cn version of Upgrade doc
Alluxio/alluxio pull request #16840
Opened 2023-02-02 04:57 UTC by voddle

What changes are proposed in this pull request?
Update cn version of Upgrade doc.

Why are the changes needed?
There is no corresponding Chinese documentation for upgrade.

Does this PR introduce any user facing changes?
More Chinese users can access Alluxio documentation more easily.

2023-02-07 23:32 UTC, LuQQiu commented
@voddle thanks for updating the doc

2023-02-12 14:10 UTC, jiacheliu3 requested changes
Added some minor comments, thanks for the work!

2023-02-12 14:10 UTC, jiacheliu3 commented on docs/cn/administration/Upgrade.md
> +正常情况下，用户可以直接关闭当前的 Alluxio 进程，将 Alluxio 二进制文件更改为更新的版本，同时还按之前的方式配置 Alluxio 集群，并使用现有的日志文件夹/地址来启动 Alluxio 进程
```suggestion
正常情况下，用户可以直接关闭当前的 Alluxio 进程，将 Alluxio 二进制文件更改为更高的版本，同时还按之前的方式配置 Alluxio 集群，并使用现有的日志文件夹/地址来启动 Alluxio 进程
```

2023-02-12 14:10 UTC, jiacheliu3 commented on docs/cn/administration/Upgrade.md
> +进行升级。Alluxio 可读取以前的日志文件并自动恢复 Alluxio 元数据。
```suggestion
进行升级。Alluxio 可读取以前的日志文件并从 Journal 日志中自动恢复 Alluxio 元数据。
```

2023-02-12 14:10 UTC, jiacheliu3 commented on docs/cn/administration/Upgrade.md
> +- 使用[内嵌日志]({{ '/cn/operation/Journal.html' | relativize_url}})的情况下从 Alluxio 2.3.x 及以下版本升级到 Alluxio 2.4.0 及以上版本
改成link到Journal.html#xxx embedded journal?

2023-02-12 14:10 UTC, jiacheliu3 commented on docs/cn/administration/Upgrade.md
> +Alluxio-1.8.1 版本引入了日志备份功能。
```suggestion
Alluxio-1.8.1 版本引入了日志备份（backup）功能。
```

2023-02-12 14:10 UTC, jiacheliu3 commented on docs/cn/administration/Upgrade.md
> +在运行 1.8.1 之前版本的 master 时，通过运行以下命令创建日志备份：
是不是只说了<=1.8.1版本时候怎么backup？那我觉得这里有点问题。用2.x版本的时候指令应该是一样的，你可以快速在自己电脑上验证一下，然后直接把“在运行 1.8.1 之前版本的 master 时”去掉

2023-02-12 14:10 UTC, jiacheliu3 commented on docs/cn/administration/Upgrade.md
> +如果要使用 Alluxio-2.x 客户端需升级所有应用程序 。
```suggestion
如果要使用 Alluxio-2.x 客户端需升级所有应用程序 中的Alluxio客户端。
```

2023-02-12 14:10 UTC, jiacheliu3 commented on docs/cn/administration/Upgrade.md
> +	如下所示：
缩进

2023-02-12 14:10 UTC, jiacheliu3 commented on docs/cn/administration/Upgrade.md
> +- **警告：** 该操作会对 Alluxio worker 上的内存虚拟硬盘进行格式化（即：删除其中的内容）。
```suggestion
- **警告：** 该操作会对 Alluxio worker 上的内存虚拟硬盘（ramdisk）进行格式化（即：删除其中的内容）。
```

2023-02-13 10:14 UTC, voddle commented on docs/cn/administration/Upgrade.md
> +- 使用[内嵌日志]({{ '/cn/operation/Journal.html' | relativize_url}})的情况下从 Alluxio 2.3.x 及以下版本升级到 Alluxio 2.4.0 及以上版本
中文文档好像还没有对应更新

2023-02-13 12:56 UTC, jiacheliu3 commented on docs/cn/administration/Upgrade.md
> +- 使用[内嵌日志]({{ '/cn/operation/Journal.html#Configuring Embedded Journal' | relativize_url}})的情况下从 Alluxio 2.3.x 及以下版本升级到 Alluxio 2.4.0 及以上版本
double check the URL, is it correct?

2023-02-15 09:21 UTC, jiacheliu3 approved these changes
LGTM, thanks!

2023-02-15 09:21 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2023-02-15 09:21 UTC, merged