Some errors occurred when formatting alloxio
Alluxio/alluxio pull request #16950
Opened 2023-02-27 08:39 UTC by jianghuazhu

### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

2023-02-27 09:28 UTC, jianghuazhu commented
After adding JAVA_HOME configuration, reformat alluxio. We found that everything works fine, here are some logs:
[2023-02-27 17:00:07][localhost] 2023-02-27 17:00:07,486 INFO  Format - Formatting worker data folder: /alluxioworker/
[2023-02-27 17:00:07][localhost] 2023-02-27 17:00:07,486 WARN  InstancedConfiguration - PropertyKey alluxio.worker.tieredstore.level0.dirs.path's type is LIST, please use proper getter method for the type, getString will no longer work for non-STRING property types in 3.0
[2023-02-27 17:00:07][localhost] 2023-02-27 17:00:07,486 INFO  Format - Formatting Data path for tier 0:/mnt/ramdisk/alluxioworker
[2023-02-27 17:00:07][localhost] 2023-02-27 17:00:07,501 INFO  Format - Formatting complete
[2023-02-27 17:00:07][localhost] Connection to localhost closed.

2023-02-27 09:53 UTC, jianghuazhu commented
@fuzhengjia @dbw9580, could you please help review this pr?
Thanks.

2023-02-28 01:25 UTC, maobaolong reviewed
@jianghuazhu If we define the JAVA_HOME in our os env, is this necessary to define it in `conf/alluxio-env.sh` again?

If not, you can add some condition description to explain what case to add `JAVA_HOME` manually.

2023-02-28 02:15 UTC, jianghuazhu commented
@maobaolong, thank you so much for your comments.
I set 'JAVA_HOME' in the /etc/profile file and still get these errors. Therefore, I think configuring JAVA_HOME in the alluxi-env.sh file should be considered in advance.

2023-02-28 09:13 UTC, dbw9580 requested changes
Thanks for the improvement. Only a minor comment, otherwise LGTM.

2023-02-28 09:13 UTC, dbw9580 commented on docs/cn/overview/Getting-Started.md
> +$ echo "JAVA_HOME=/usr/java/jdk1.8.0_171" >> conf/alluxio-env.sh
```suggestion
$ echo "JAVA_HOME=/path/to/java/home" >> conf/alluxio-env.sh
```

2023-02-28 09:13 UTC, dbw9580 commented on docs/en/overview/Getting-Started.md
> +$ echo "JAVA_HOME=/usr/java/jdk1.8.0_171" >> conf/alluxio-env.sh
also here

2023-02-28 09:29 UTC, JiamingMai reviewed
We should not use a specific jdk path in the docs.

2023-02-28 11:40 UTC, jianghuazhu commented on docs/cn/overview/Getting-Started.md
> +$ echo "JAVA_HOME=/usr/java/jdk1.8.0_171" >> conf/alluxio-env.sh
Thanks.
I will update soon.

2023-02-28 13:00 UTC, jianghuazhu commented
@dbw9580  @JiamingMai , I have updated, can you review this pr again?
thanks.

2023-03-01 02:32 UTC, maobaolong commented
@dbw9580 Did you met this issue? It run good without `JAVA_HOME` defined in our  `conf/alluxio-env.sh`

2023-03-01 04:49 UTC, jianghuazhu commented
@maobaolong, thanks for your comments.
Here is the environment in which I ran alluxio:
1. Operating system :Ubuntu 14.04LTS
2. In the /etc/profile file, set the JAVA_HOME and alluxio directories.
export JAVA_HOME=/usr/java/jdk1.8.0_171
export ALLUXIO_HOME = / home/jianghuazhu/alluxio/deplay/alluxio - 2.9.1
3. Check the java environment, java -version. The following information is displayed:
java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

2023-03-04 07:02 UTC, jianghuazhu commented
@maobaolong @dbw9580 @JiamingMai, can you review this pr again?

2023-03-06 02:53 UTC, elega commented
This looks good to me @JiamingMai @dbw9580 can you guys take a second look?

2023-03-06 02:54 UTC, JiamingMai approved these changes
LGTM

2023-03-06 02:57 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2023-03-06 02:57 UTC, merged