Fix the aggregate result problem in UfsIOBench
Alluxio/alluxio pull request #17063
Opened 2023-03-13 05:06 UTC by bzheng888

### What changes are proposed in this pull request?

Fix the aggregate result problem in UfsIOBench.

### Why are the changes needed?
The  UfsIOBench result summary calculates the total duration by summing each  points' result, and   compute the average speed based on total duration, actually the average can't  represent the system performance. 
For examples: 
An alluxio cluster with 1 job master and 3 job worker,  Run the UfsIOBench with 16 threads:
```
./bin/alluxio runUfsIOTest --path hdfs://hdfsCluster/tmp/ufsIoBanch --io-size 2G--threads 16 --cluster
```
<img width="701" alt="WeChatWorkScreenshot_14f71ae8-abe3-410f-bc45-5d31e45e1691" src="https://user-images.githubusercontent.com/42070967/224611735-d14d73bc-fcae-44ad-9c8e-ba9f233fb526.png">

the mTotalDurationSeconds is 16 * 3 *(points duration), but actually the 16 points read and write concurrently  and finished almostly at same time.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
No

2023-03-14 10:41 UTC, dbw9580 requested changes

2023-03-17 04:43 UTC, bzheng888 commented
@dbw9580 PTAL, thx!

2023-04-06 01:59 UTC, bzheng888 commented
@dbw9580 Any suggestion on this pr?

2023-04-07 03:21 UTC, dbw9580 commented on stress/common/src/main/java/alluxio/stress/worker/IOTaskSummary.java
>      public double mStdDev;
```suggestion
    // Max speed among all nodes
    public double mMaxSpeedMbps;
    // Min speed among all nodes
    public double mMinSpeedMbps;
    // Average speed of all nodes
    public double mAvgSpeedMbps;
    // Cluster-wide throughput
    public double mClusterAvgSpeedMbps;
    // Standard deviation of speed reported by each node
    public double mStdDev;
```

2023-04-07 03:21 UTC, dbw9580 approved these changes
LGTM

2023-04-10 09:17 UTC, bzheng888 commented
@jiacheliu3 PTAL!

2023-04-19 06:26 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2023-04-19 06:26 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2023-04-19 06:26 UTC, merged