Support position reader of OSS and COS, and update position reader of S3.
Alluxio/alluxio pull request #17414
Opened 2023-05-10 07:01 UTC by zhezhidashi

### What changes are proposed in this pull request?

Support Position Reader of Aliyun OSS and Tencent COS, and Update position reader of AWS S3.

### Why are the changes needed?

The original code lacked support for OSS and COS position reader, and this PR can support them.

### Does this PR introduce any user facing changes?

No

2023-05-10 10:48 UTC, dbw9580 requested changes

2023-05-10 10:48 UTC, dbw9580 commented on dora/core/common/src/main/java/alluxio/PositionReader.java
> +  default int readDataInternal(InputStream in, ReadTargetBuffer buffer,
why is this a default impl in `PositionReader`? The method reads from a `InputStream`, has nothing to do with `PositionReader`.

2023-05-10 10:48 UTC, dbw9580 commented on dora/core/common/src/main/java/alluxio/PositionReader.java
> +  default int readDataInternal(InputStream in, ReadTargetBuffer buffer,
I think what you need is something that is the equivalent of `MultiRangeObjectInputStream` but for `PositionReader`.

2023-05-10 10:48 UTC, dbw9580 commented on dora/underfs/oss/src/main/java/alluxio/underfs/oss/OSSPositionReader.java
> +      throw new IOException(errorMessage, e);
The common logic is to open an input stream, and then read data out of it and feed it into the output buffer. So you can extract these into an abstract Position reader that takes in an input stream and adapts as a position reader.

2023-05-15 04:04 UTC, dbw9580 requested changes

2023-05-15 04:04 UTC, dbw9580 commented on dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSPositionReader.java
> +      throw new IOException(errorMessage, e);
error message should be constructed in-place
```suggestion
      throw new IOException(String.format("Failed to get object %s in bucket %s", mPath, mBucketName, e);
```

2023-05-15 04:04 UTC, dbw9580 commented on dora/core/common/src/main/java/alluxio/underfs/ObjectPositionReader.java
> +  protected abstract InputStream getObjectInputStream(
use an actual verb to indicate that this is not a getter

```suggestion
  protected abstract InputStream openObjectInputStream(
```

2023-05-15 04:04 UTC, dbw9580 commented on dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSPositionReader.java
> +  protected COSClient mClient;
can be final

2023-05-15 04:04 UTC, dbw9580 commented on dora/underfs/cos/src/main/java/alluxio/underfs/cos/COSPositionReader.java
> +   * @param bucketNameInternal the bucket name
what's `bucketNameInternal`? if it's not the same thing as a bucket name, put the descriptions in the javadoc

2023-05-17 08:49 UTC, dbw9580 approved these changes
LGTM

2023-05-17 09:22 UTC, zhezhidashi commented
@JiamingMai @LuQQiu Please review this PR. Thanks :)

2023-05-19 03:22 UTC, JiamingMai commented
alluxio-bot, merge this please

2023-05-19 03:22 UTC, merged