[DOCFIX] Remove docs
Alluxio/alluxio pull request #17584
Opened 2023-06-09 23:10 UTC by LuQQiu

Remove dora unrelated docs

2023-06-13 18:37 UTC, Xenorith requested changes
can run `bin/alluxio docGen` still? could do it in a follow up PR if not updated yet

2023-06-13 18:37 UTC, Xenorith commented on docs/en/administration/Basic-Logging.md
> -
wondering why remove these sections?

2023-06-13 18:37 UTC, Xenorith commented on docs/en/administration/StressBench.md
stressbench does not work on dora?

2023-06-13 18:37 UTC, Xenorith commented on docs/en/contributor/Building-Alluxio-From-Source.md
i feel we should still keep the basic parts of this and remove the integration related sections

2023-06-13 18:37 UTC, Xenorith commented on docs/en/contributor/Code-Conventions.md
isn't all this still relevant? why remove

2023-06-14 18:32 UTC, LuQQiu commented
@Xenorith feel free to add back the sections you think it's useful
we are doing aggressive removing docs

2023-06-14 18:32 UTC, LuQQiu commented
Stressbench relies on job-service which should be removed

2023-06-14 18:43 UTC, Xenorith commented on docs/en/administration/Basic-Logging.md
> -
i leave this deleted

2023-06-14 19:47 UTC, Xenorith approved these changes

2023-06-14 21:19 UTC, Xenorith commented
alluxio-bot, merge this please

2023-06-14 21:19 UTC, merged