Add move request to job factory
Alluxio/alluxio pull request #17712
Opened 2023-06-29 19:57 UTC by ssyssy

### What changes are proposed in this pull request?

Add move job request

### Why are the changes needed?

Need for distMv command.

### Does this PR introduce any user facing changes?

na

2023-06-29 19:59 UTC, jja725 requested changes

2023-06-29 19:59 UTC, jja725 commented on dora/core/server/master/src/main/java/alluxio/master/job/MoveJobFactory.java
> +    return new CopyJob(src, mRequest.getDst(), overwrite, user, UUID.randomUUID().toString(),
Copy??

2023-06-29 22:04 UTC, jja725 approved these changes
LGTM

2023-06-30 00:27 UTC, ssyssy commented
alluxio-bot, merge this please

2023-06-30 01:47 UTC, ssyssy commented
alluxio-bot, merge this please

2023-06-30 01:47 UTC, merged