[DOCFIX] Update Glossary Page & minor changes
Alluxio/alluxio pull request #17773
Opened 2023-07-14 01:52 UTC by ccmao1130

### What changes are proposed in this pull request?

Added more terms to glossary page

### Why are the changes needed?

update terms list & definitions

### Does this PR introduce any user facing changes?

yes

2023-07-14 01:56 UTC, Xenorith requested changes

2023-07-14 01:56 UTC, Xenorith commented on docs/en/Overview.md
> +See [Install Alluxio on Kubernetes]({{ '/en/kubernetes/Install-Alluxio-On-Kubernetes.html' | relativize_url }}) on how to install Alluxio (Dora) on Kubernetes via
```suggestion
See [Install Alluxio on Kubernetes]({{ '/en/kubernetes/Install-Alluxio-On-Kubernetes.html' | relativize_url }}) on how to install Alluxio on Kubernetes via 
```

2023-07-14 01:56 UTC, Xenorith commented on docs/en/Overview.md
> +[Helm](https://helm.sh/), a kubernetes package manager, and [Operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/), a kubernetes extension for managing applications.
```suggestion
[Helm](https://helm.sh/), a Kubernetes package manager, and [Operator](https://kubernetes.io/docs/concepts/extend-kubernetes/operator/), a Kubernetes extension for managing applications.
```

2023-07-14 01:56 UTC, Xenorith commented on docs/en/introduction/Glossary.md
> +: Alluxio incorporates fault tolerance mechanisms to ensure dat availability and reliability. It replicates data across different notes in the cluster, providing resilience against node failures. [Se
```suggestion
: Alluxio incorporates fault tolerance mechanisms to ensure data availability and reliability. It replicates data across different notes in the cluster, providing resilience against node failures. [See Fault Tolerance in Dora Cache]({{ '/en/core-services/Data-Caching.html#fault-tolerance-and-client-side-ufs-fallback' | relativize_url }})
```

2023-07-14 02:33 UTC, Xenorith approved these changes

2023-07-14 17:41 UTC, Zijian-Zhu approved these changes

2023-07-17 05:59 UTC, apc999 commented
@ccmao1130 is this PR ready to merge?

2023-07-17 18:54 UTC, Zijian-Zhu commented
alluxio-bot, merge this please

2023-07-17 18:54 UTC, merged