Add generate subcommand to CLI
Alluxio/alluxio pull request #17790
Opened 2023-07-17 10:02 UTC by twalluxio

Add generate commands to golang CLI as part of #17522 

bin/alluxio docGen -> bin/cli generate docs
bin/alluxio bootstrapConf -> bin/cli generate template

to read ALLUXIO_CONF_DIR, also conducted a minor change on env variables.

2023-07-17 21:42 UTC, ChunxuTang commented
Hi @twalluxio, could you sign the CLA and let us know when it's done?

2023-07-18 02:02 UTC, twalluxio commented
Hello Chunxu,

Thank you for reminding me! I have signed CLA and e-mailed it back to
***@***.*** today. Please tell me if you have any other questions.

On Tue, Jul 18, 2023 at 5:43 AM Chunxu Tang ***@***.***>
wrote:

> Hi @twalluxio <https://github.com/twalluxio>, could you sign the CLA and
> let us know when it's done?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/Alluxio/alluxio/pull/17790#issuecomment-1638927030>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BBFJIBEWNEYAWAPMTR3O6IDXQWWW5ANCNFSM6AAAAAA2MWOQUI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-07-19 01:10 UTC, Xenorith requested changes
also see comments in https://github.com/Alluxio/alluxio/pull/17797

2023-07-19 01:10 UTC, Xenorith commented on cli/src/alluxio.org/cli/cmd/generate/template.go
> +					fmt.Println(targetDir + " is created.")
use `log` instead of `fmt` to print to console. check how existing commands are printing to console as an example

2023-07-19 01:10 UTC, Xenorith commented on cli/src/alluxio.org/cli/cmd/generate/template.go
> +			targetDir := env.ConfAlluxioConfDir.EnvVar + "alluxio-site.properties"
use `filepath.Join` for file paths instead of concat/adding strings together

2023-07-19 23:12 UTC, Xenorith commented on cli/src/alluxio.org/cli/cmd/generate/template.go
> +			}
```suggestion
```
remove this since it will be checked by `Args:  cobra.ExactArgs(1),` and the argument description is part of the `Use`

2023-07-19 23:13 UTC, Xenorith commented on cli/src/alluxio.org/cli/cmd/generate/template.go
> +					if e != nil {
```suggestion
					if err := ioutil.WriteFile(targetDir, []byte(content), 0644); err != nil {
```
this creates a new variable named `err` that exists only within the scope of the if statement's code.

2023-07-19 23:27 UTC, Xenorith commented on cli/src/alluxio.org/cli/cmd/generate/template.go
> +			if _, err := os.Stat(targetDir); err != nil {
we can reorganize this logic a little bit to make it less nested and easier to understand
current:
```
if statError
	if not exists
		write file
		if cannot write
			error writing file and return
		log file written and return
	else
		error reading and return
else
	warn file exists and return
```

one less nested level and less return statements:
```
_, statErr := os.Stat(targetDir)
if file exists => os.IsExist(err)
	warn file exists
else if file not exists => os.IsNotExist(err)
	write file
	if cannot write
		error writing file
	log file written
else
	error reading
(and naturally return at end of function)
```

2023-07-20 20:25 UTC, Xenorith approved these changes

2023-07-25 09:24 UTC, Kai-Zhang commented
alluxio-bot, merge this please

2023-07-25 09:25 UTC, Kai-Zhang commented
alluxio-bot, merge this please

2023-07-25 09:25 UTC, merged