Improve pom for shade plugin
Alluxio/alluxio pull request #17824
Opened 2023-07-23 07:23 UTC by apc999

### What changes are proposed in this pull request?

Improve POM for shade plugin

### Why are the changes needed?

Code hygiene 

### Does this PR introduce any user facing changes?

No

2023-07-24 19:33 UTC, Xenorith requested changes
i checked the other ufs module pom.xml. for the ones with a dependency on alluxio-underfs-hdfs, their shade plugin configuration usually contains this filter entry:
```
                <filter>
                  <artifact>org.alluxio:alluxio-underfs-hdfs</artifact>
                  <excludes>
                    <!-- Because this module depends on alluxio-underfs-hdfs, eliminate HDFS factory implementation -->
                    <exclude>alluxio/underfs/hdfs/HdfsUnderFileSystemFactory.*</exclude>
                    <exclude>META-INF/services/alluxio.underfs.UnderFileSystemFactory</exclude>
                  </excludes>
                </filter>
```

the following diff makes them all consistent:
```
diff --git a/dora/underfs/cephfs-hadoop/pom.xml b/dora/underfs/cephfs-hadoop/pom.xml
index 89d409a60c..fccb21bee9 100644
--- a/dora/underfs/cephfs-hadoop/pom.xml
+++ b/dora/underfs/cephfs-hadoop/pom.xml
@@ -64,6 +64,7 @@
                   <artifact>org.alluxio:alluxio-underfs-hdfs</artifact>
                   <excludes>
                     <!-- Because this module depends on alluxio-underfs-hdfs, eliminate HDFS factory implementation -->
+                    <exclude>alluxio/underfs/hdfs/HdfsUnderFileSystemFactory.*</exclude>
                     <exclude>META-INF/services/alluxio.underfs.UnderFileSystemFactory</exclude>
                   </excludes>
                 </filter>
diff --git a/dora/underfs/ozone/pom.xml b/dora/underfs/ozone/pom.xml
index 8babf6aae2..9b9411c53a 100644
--- a/dora/underfs/ozone/pom.xml
+++ b/dora/underfs/ozone/pom.xml
@@ -147,6 +147,8 @@
                 <filter>
                   <artifact>org.alluxio:alluxio-underfs-hdfs</artifact>
                   <excludes>
+                    <!-- Because this module depends on alluxio-underfs-hdfs, eliminate HDFS factory implementation -->
+                    <exclude>alluxio/underfs/hdfs/HdfsUnderFileSystemFactory.*</exclude>
                     <exclude>META-INF/services/alluxio.underfs.UnderFileSystemFactory</exclude>
                   </excludes>
                 </filter>
```

2023-08-14 06:33 UTC, apc999 commented
@Xenorith comment addressed. PTAL

2023-08-14 08:59 UTC, Xenorith approved these changes

2023-08-14 15:43 UTC, apc999 commented
alluxio-bot, merge this please

2023-08-14 15:43 UTC, merged