[DOCFIX] remove a space
Alluxio/alluxio pull request #17837
Opened 2023-07-26 08:06 UTC by thu-david

### What changes are proposed in this pull request?

Please outline the changes and how this PR fixes the issue.

### Why are the changes needed?

Please clarify why the changes are needed. For instance,
  1. If you propose a new API, clarify the use case for a new API.
  2. If you fix a bug, describe the bug.

### Does this PR introduce any user facing changes?

Please list the user-facing changes introduced by your change, including
  1. change in user-facing APIs
  2. addition or removal of property keys
  3. webui

2023-07-26 08:06 UTC, thu-david commented
remove a space for pr

2023-07-26 08:26 UTC, thu-david commented
/check-cla

2023-07-28 07:21 UTC, apc999 requested changes

2023-07-28 07:21 UTC, apc999 commented on docs/cn/ufs/Azure-Data-Lake-Gen2.md
> +  {:toc}
why space here?

2023-07-28 07:21 UTC, apc999 commented on docs/cn/ufs/Azure-Data-Lake-Gen2.md
> +在将 Azure 数据湖存储与 Alluxio 一起运行前，请在 [Azure 帐户中创建一个新的 Data Lake Storage](https://learn.microsoft.com/zh-cn/azure/storage/blobs/create-data-lake-storage-account) 或使用现有的 Data Lake Storage。这里还应指定需使用的 direct
`）` vs `)` ? Full-width with half-width characters

2023-08-01 07:04 UTC, apc999 commented
@thu-david could you please address the comments? thanks

2023-08-14 07:12 UTC, thu-david commented
单纯为了提pr

2023-08-14 07:12 UTC, closed without merging