Fix to support update new key
Alluxio/alluxio pull request #17856
Opened 2023-07-30 14:07 UTC by maobaolong

### What changes are proposed in this pull request?

Fix to support update new key, for example, template key.

### Why are the changes needed?

Without this PR, we cannot update template key or any other key didn't exist in PropertyKeys.

### Does this PR introduce any user facing changes?

No.

2023-08-01 19:20 UTC, lucyge2022 commented
@jiacheliu3  can you help take a look at this? I'm assuming propertykey doesn't allow unregistered templated key to be created for a reason.

2023-10-13 01:36 UTC, jiacheliu3 requested changes
Thanks for the work! PTAL

2023-10-13 01:36 UTC, jiacheliu3 commented on tests/src/test/java/alluxio/client/cli/fsadmin/command/UpdateConfIntegrationTest.java
> +    // Support update non-existing key
typo?
```suggestion
    // Do not support update non-existing key
```

2023-10-13 01:36 UTC, jiacheliu3 commented on shell/src/main/java/alluxio/cli/fsadmin/command/UpdateConfCommand.java
> +        System.err.printf("argument %s must contains \"=\"", arg);
return -1?

2023-10-13 01:36 UTC, jiacheliu3 commented on shell/src/main/java/alluxio/cli/fsadmin/command/UpdateConfCommand.java
> +        properties.put(PropertyKey.Builder.stringBuilder(kv[0]).buildUnregistered(), value);
Do you intend to support setting all kinds of unknown keys in Alluxio? Or it's only a templated key? I think the logic here allows any key and it's probably not good?
```suggestion
        PropertyKey property = PropertyKey.Builder.stringBuilder(kv[0]).buildUnregistered();
        System.out.format("Setting property %s to %s%n", property, value);
        properties.put(PropertyKey.Builder.stringBuilder(kv[0]).buildUnregistered(), value);
```

2023-10-13 01:36 UTC, jiacheliu3 commented on core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
> +            LOG.debug("Cannot get old value for the given key {}", key.getName());
warning

2023-10-13 09:47 UTC, jiacheliu3 requested changes
added two minor comments, mostly LGTM

2023-10-13 09:47 UTC, jiacheliu3 commented on core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
> +        key = PropertyKey.fromString(entry.getKey());
```suggestion
        // Build template key if possible, an IllegalArgumentException will be thrown for unknown key
        // The exception will be caught and client will receive the failure
        key = PropertyKey.fromString(entry.getKey());
```

2023-10-13 09:47 UTC, jiacheliu3 commented on shell/src/main/java/alluxio/cli/fsadmin/command/UpdateConfCommand.java
> +        properties.put(PropertyKey.Builder.stringBuilder(kv[0]).buildUnregistered(), value);
Ok got it, we send whatever key to the master, but the master only accepts templated keys. I've updated my suggested change above, PTAL.

2023-10-16 00:16 UTC, maobaolong commented on core/server/master/src/main/java/alluxio/master/meta/DefaultMetaMaster.java
> +            LOG.debug("Cannot get old value for the given key {}", key.getName());
done

2023-10-16 00:17 UTC, maobaolong commented on shell/src/main/java/alluxio/cli/fsadmin/command/UpdateConfCommand.java
> +        System.err.printf("argument %s must contains \"=\"", arg);
done

2023-10-16 00:37 UTC, maobaolong commented
@jiacheliu3 Thanks for the previous review, I've addressed all of your suggestion, PTAL

2023-10-26 01:31 UTC, jiacheliu3 approved these changes
LGTM, thanks for the work!

2023-10-26 01:31 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2023-10-26 01:31 UTC, merged