Change name of NoopMembershipManager
Alluxio/alluxio pull request #18097
Opened 2023-09-01 19:15 UTC by lucyge2022

### What changes are proposed in this pull request?

Change name of NoopMembershipManager to MasterMembershipManager.

### Why are the changes needed?

N/A

### Does this PR introduce any user facing changes?

N/A

2023-09-04 04:52 UTC, apc999 commented on dora/core/common/src/main/java/alluxio/membership/MembershipManager.java
>          case NOOP:
don't we need to change NOOP to MASTER?
```suggestion
        case MASTER:
```

2023-09-04 04:52 UTC, apc999 requested changes
don't we need to change the `enum` ?

2023-09-05 18:24 UTC, lucyge2022 commented on dora/core/common/src/main/java/alluxio/membership/MembershipManager.java
>          case NOOP:
done

2023-09-05 18:24 UTC, lucyge2022 commented
> don't we need to change the `enum` ?

thanks for catching, fixed

2023-09-07 23:11 UTC, apc999 approved these changes

2023-09-08 03:07 UTC, lucyge2022 commented
alluxio-bot, merge this please.

2023-09-08 03:07 UTC, merged