fix: fix abstract filesystem memory leak.
Alluxio/alluxio pull request #18480
Opened 2024-01-02 06:59 UTC by qian0817

### What changes are proposed in this pull request?

Fix #18479

### Why are the changes needed?

Fix the memory leak issue when the client accesses Alluxio through Hadoop FileContext API.

### Does this PR introduce any user facing changes?

No.

2024-01-02 07:03 UTC, qian0817 commented on core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
> +  protected void finalize() throws Throwable {
The `hadoop-azure` module also uses the finalize method to handle this situation. https://issues.apache.org/jira/browse/HADOOP-10840
Any better suggestions are welcome.

2024-02-02 03:05 UTC, jiacheliu3 commented
@qian0817 I'm not sure if the `core/client/hdfs/src/main/java/alluxio/hadoop/AlluxioFileSystem.java` is only used in YARN and does not impact other hadoop-based apps like Spark/Presto/Impala. Could you confirm on that? Thanks!

2024-02-23 02:56 UTC, qian0817 commented
I search FileContext keyword under the spark, presto, and impala repositories and find spark will use filecontext. https://github.com/apache/spark/blob/master/sql/core/src/main/scala/org/apache/spark/sql/execution/streaming/CheckpointFileManager.scala#L308-L312
presto and impala will not use.

2024-03-06 03:51 UTC, jiacheliu3 requested changes
Mostly LGTM with one minor comment. Good to merge once the comment is resolved. Thanks a lot for the fix!

2024-03-06 03:51 UTC, jiacheliu3 commented on core/client/hdfs/src/main/java/alluxio/hadoop/AbstractFileSystem.java
> +  private boolean mIsClosed = false;
i think you need a `volatile` here?

2024-03-06 06:26 UTC, jiacheliu3 approved these changes
LGTM, thanks for the work!

2024-03-06 07:07 UTC, jiacheliu3 commented
alluxio-bot, merge this please

2024-03-06 07:07 UTC, merged