TOS Integration
Alluxio/alluxio pull request #18621
Opened 2024-06-07 03:19 UTC by thu-david

### What changes are proposed in this pull request?

Created an interface for TOS, enabling Alluxio to operate and cache data specifically for TOS.

### Why are the changes needed?

Tested the creation, deletion, metadata retrieval, and directory information retrieval for files of sizes 1MB, 64MB, 1GB, and 10GB. This can support the most basic TOS query requests.

### Does this PR introduce any user facing changes?

This implementation continues to follow Alluxio's API. To use it, you only need to provide the TOS information in the configuration file.

2024-06-07 03:40 UTC, Jackson-Wang-7 requested changes
Mostly looks good, left some comments to fix, thanks for your contribution!

2024-06-07 03:40 UTC, Jackson-Wang-7 commented on core/common/src/main/java/alluxio/conf/PropertyKey.java
> +          .setDescription("The region name of TOS bucket.")
please align to the previous line.

2024-06-07 03:40 UTC, Jackson-Wang-7 commented on underfs/tos/pom.xml
> +            <version>2.7.1</version>
define the version in the root pom.xml, not here

2024-06-07 03:40 UTC, Jackson-Wang-7 commented on underfs/tos/src/main/java/alluxio/underfs/tos/AlluxioTosException.java
> +      case HttpURLConnection.HTTP_BAD_REQUEST:  // 400
have you verified the error code in your tests?

2024-06-07 03:40 UTC, Jackson-Wang-7 commented on underfs/tos/src/main/java/alluxio/underfs/tos/TOSInputStream.java
> + * A stream for reading a file from COS. This input stream returns 0 when calling read with an empty
```suggestion
 * A stream for reading a file from TOS. This input stream returns 0 when calling read with an empty
```

2024-06-07 03:40 UTC, Jackson-Wang-7 commented on underfs/tos/src/main/java/alluxio/underfs/tos/TOSOutputStream.java
> + * A stream for writing a file into COS. The data will be persisted to a temporary directory on the
```suggestion
 * A stream for writing a file into TOS. The data will be persisted to a temporary directory on the
```

2024-06-07 03:40 UTC, Jackson-Wang-7 commented on underfs/tos/src/main/java/alluxio/underfs/tos/TOSUnderFileSystem.java
> +    }
add the method for `hasNextChunk()`
```
    @Override
    public Boolean hasNextChunk() {
      return mOutput.isTruncated();
    }
```

2024-06-07 03:40 UTC, Jackson-Wang-7 commented on underfs/tos/src/main/java/alluxio/underfs/tos/TOSUnderFileSystem.java
> +      return null;
please check the exception, if it's 404 not found, then return null, otherwise throw a exception

2024-06-07 03:40 UTC, Jackson-Wang-7 commented on underfs/tos/src/main/java/alluxio/underfs/tos/TOSUnderFileSystemFactory.java
> +    String err = "TOS Credentials not available, cannot create TOS Under File System.";
```suggestion
    String err = "TOS Credentials or configurations not available, cannot create TOS Under File System.";
```

2024-06-07 13:12 UTC, Jackson-Wang-7 approved these changes
LGTM, just remove the OSS code change

2024-06-07 13:12 UTC, Jackson-Wang-7 commented on underfs/oss/src/main/java/alluxio/underfs/oss/OSSUnderFileSystemFactory.java
> +    String err =
@thu-david this is the OSS UnderFileSystem Factory, please remove this line

2024-06-07 13:12 UTC, Jackson-Wang-7 commented on underfs/tos/src/main/java/alluxio/underfs/tos/AlluxioTosException.java
> +      case HttpURLConnection.HTTP_BAD_REQUEST:  // 400
TODO

2024-06-11 09:53 UTC, JiamingMai commented
alluxio-bot, merge this please.

2024-06-11 09:53 UTC, merged